### ISSUE TITLE
Icon extension

### ISSUE THREAD

**Issue by dbtek** [showdownjs/showdown#100]
Hi,
I created an icon extension for Showdown here: https://github.com/dbtek/showdown-icon. Supports glyphicon and font-awesome icon sets. You may want to mention it or add to the repository.
Thanks for the awesome work.

**Comment by pdeschen** [comment]
That's interesting. Not clear how the dep over fa and glyphicon is handled. Adding test case would be nice.

@tivie what do you about adding a wiki page to list extensions? We could link to it from the readme and move extension related details in there.

**Comment by tivie** [comment]
@pdeschen I think it's a very good idea.

**Comment by dbtek** [comment]
@pdeschen dependencies should be managed through bower. Fontawesome has its own bower repo. However, glyphicons is used with Bootstrap. This may have to depend on Bootstrap too.

**Comment by pdeschen** [comment]
@dbtek as you see fit. We'll create a section in the extensions wiki for a list of available extension including yours.

**Comment by pdeschen** [comment]
Done. Added to [Extensions wiki](extensions#community)

**Comment by pdeschen** [comment]
Closing
