### ISSUE TITLE
Command line interface usage.

### ISSUE THREAD

**Issue by cirosantilli** [showdownjs/showdown#101]
Is it possible to use showdown from the command line out of the box, e.g.: 

    showdown file.md

or as:

    echo 'a' | showdown

?

If not, feature request. If yes, I recommend documenting it on the README.

I want this to make it easier to use it on the Markdown Testsuite https://github.com/karlcow/markdown-testsuite

**Comment by tivie** [comment]
That's an interesting feature. I will have a look into it as soon as I'm able to.

**Comment by tivie** [comment]
Commit d079154260f80ed71e9dbadbcf9613f2a2eb6d62 introduces a cli tool.
