### ISSUE TITLE
What happened to showdownjs.com?

### ISSUE THREAD

**Issue by foto-andreas** [showdownjs/showdown#1020]
showdownjs.com
Este domínio expirou.

**Comment by EliasPereirah** [comment]
I realized this today, if they don't do anything there is a risk that the administrator will lose the site domain

**Comment by foto-andreas** [comment]
I hope that not a sign of a dying project

**Comment by tivie** [comment]
I will renew it shortly. It's quite expensive and we haven't got many donations lately.

**Comment by EliasPereirah** [comment]
> I will renew it shortly. It's quite expensive and we haven't got many donations lately.

This project has never been as relevant as it is now, with AI generating responses in markdown; we need to convert it to HTML. I use it together with highlight.js, and it's perfect.

**Comment by foto-andreas** [comment]
> It's quite expensive and we haven't got many donations lately.

if you give me some info what is needed for hosting, I'll ask our CEOs at SET GmbH in Hannover, if we can provide the virtual server and domain.

Andreas

**Comment by tivie** [comment]
thanks. Should be working now.
