### ISSUE TITLE
Seeking Maintainers for Showdown

### ISSUE THREAD

**Issue by coreyti** [showdownjs/showdown#114]
With apologies, I've long been unable to stay up with maintaining Showdown on Github. As such, I've moved the repository to the "showdownjs" organization. I'm seeking maintainers to take over ownership of that organization and the Showdown project.

Please respond here if interested.

**Comment by tivie** [comment]
@al-the-x I should be able to release a very alpha version of the re-factored version of showdown in the next couple of days. I would really appreciate your help and @tracend too, if @coreyti agrees.

**Comment by tivie** [comment]
I've just pushed a very very alpha version of the showdown refactoring. Love if you could have a look.

https://github.com/showdownjs/showdown/tree/showdown2

**Comment by pdeschen** [comment]
@tivie would you mind opening a PR? I'll give it a shot at reviewing

**Comment by pdeschen** [comment]
@tivie @all maybe it's time we open a google group for general discussion (both dev and user)?

**Comment by SyntaxRules** [comment]
I'd like to help out as well- specifically on the AngularJs integration side.

**Comment by SyntaxRules** [comment]
I'd also be happy to help migrating from grunt to gulp(v4.0 when its released) task automation.

**Comment by tivie** [comment]
@SyntaxRules I'm fine with you coming aboard, if @pdeschen and @coreyti agree. 

Regarding migrating to gulp, my question is: why?! The best thing would be dropping grunt (or gulp, or brocolli, or whatever) altogether and switch to pure NPM based tasks. =P

**Comment by SyntaxRules** [comment]
@tivie Thanks. An advantage of gulp over grunt is speed. Its hard for me to say how much of a speed up you would get by migrating (if any) because I don't know all the specifics of how this project uses grunt. 

I can see the argument for [just using npm modules](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/) and I totaly agree this works out well for simple projects. So maybe that applies here.

**Comment by ohjames** [comment]
> switch to pure NPM based tasks

Not enough power, no incremental rebuilds etc. etc.

**Comment by gtanyware** [comment]
After I used Showdown on my own project I've written a Dev.to article about extending it:
https://dev.to/gtanyware/how-to-customize-markdown-4geo

**Comment by FridayCandour** [comment]
Am also interested.
