### ISSUE TITLE
extra new line when working with prism.js

### ISSUE THREAD

**Issue by idiotWu** [showdownjs/showdown#126]
It seems to append a new line when highlighted with prism.js.

eg:
![example](https://cloud.githubusercontent.com/assets/6022672/5599974/df601bb6-930b-11e4-8f7d-fc1a5d33477a.png)

**Comment by tivie** [comment]
Can you provide a little more context?

**Comment by idiotWu** [comment]
Hello tivie,

When I attempting to use prism.js to highlight code for my Ghost blog, it appends an extra new line in code blocks.

For example, when I type in ghost like this:

<pre>
```css
body {
    display: none;
}
```
</pre>

it will be compiled to:

```html
<pre><code class="language-css">body {
    display: none;
}
</code></pre>
```

and once I try to highlighted it with prism.js, an extra new line was rendered as I've showed above.

I looked up at the source code and find showdown.js will add a new line for code blocks https://github.com/showdownjs/showdown/blob/master/src/showdown.js#L997, seeming that **prism.js will add a new line again** while rendering.

**Comment by tivie** [comment]
Well, Showdown follows the markdown specification which, as stated by its creator, adds a line before the ending tags of `code`. ([you can check the original spec here](http://daringfireball.net/projects/markdown/syntax#precode)). I don't really see the reason behind that, but we try to adhere to the specification as much as possible.

I can, however, add a feature to skip the line addition. Maybe through showdown's options. I will think about it and post something as soon as I can.

**Comment by tivie** [comment]
Feature added in version 1.0.0 https://github.com/showdownjs/showdown/commit/e6f40e19
