### ISSUE TITLE
V 0.3.3 compressed breaks in Ember

### ISSUE THREAD

**Issue by ericyoungberg** [showdownjs/showdown#128]
It doesn't appear that the _src/showdown.js_ file has been changed in the latest version, but I get an error when trying to use the compressed versions in Ember 1.8.1. 

I get an "Uncaught ReferenceError: angular is not defined" traced from an anonymous function.

Previous compressed Showdown versions worked with the same Ember version.

**Comment by tivie** [comment]
Thanks for the report. The error was caused by the angular integration module. Should be fixed now.

**Comment by ericyoungberg** [comment]
Great! Thanks
