### ISSUE TITLE
Respect semver

### ISSUE THREAD

**Issue by ldez** [showdownjs/showdown#133]
Version 0.3.4 is not compatible with version 0.3.x because the files have shift case.

\compressed\showdown.js -> 
\compressed\Showdown.js 

http://semver.org/

**Comment by ldez** [comment]
Note that \compressed\Showdown.js is no longer compressed.

**Comment by tivie** [comment]
Nice catch. We will add a note to the release referring this.

**Comment by herby** [comment]
Wouldn't it be better just not to uppercase them? It broke things on our side as well. Or, release as 0.4.0, as suggested.

**Comment by tivie** [comment]
@herby The change in case was a mistake (i'm not sure why it happened). The next release will revert back to lowercase. Also, dist files will live in a "dist" directory instead of "compressed".

**Comment by herby** [comment]
Thanks.

Estevão Soares dos Santos wrote:

**Comment by scmx** [comment]
Hi @tivie, it seems this is still a problem. `compressed/Showdown.js` is still there.

**Comment by tivie** [comment]
Sorry for the delayed response (been extra busy at work). Seems this is a problem with SopurceTree on Windows (does not respect the case of the files). I will fix this as soon as possible.

**Comment by tivie** [comment]
This is indeed weird. As you can see, the files are lowercased in local branch but get uppercase in remote.

![image](https://cloud.githubusercontent.com/assets/1608730/7276686/6dad92b6-e903-11e4-9ae6-b86ad5fdba7e.png)

**Comment by scmx** [comment]
Copy the contents, remove the files, create new files with lowercase naming and paste in the contents.
Since windows NTFS filesystem is case insensitive I sometimes has problems with detecting when a file changes name from `Showdown` to `showdown`. I'm not sure that what I wrote above will solve this, but I recognised what you describes as something I've run into before. Git should pick up the change.

**Comment by tivie** [comment]
Yeah, I need a comment without dist files though. Seems git ignores case in windows.

**Comment by tivie** [comment]
Should be fixed now, in [release 0.5.0](https://github.com/showdownjs/showdown/releases/tag/0.5.0)
