### ISSUE TITLE
Odd behaviour for multiple consecutive lists

### ISSUE THREAD

**Issue by ErisDS** [showdownjs/showdown#142]
![](http://puu.sh/gD3FW.png)

Showdown will convert a bulleted list, followed by an ordered list, into one big ordered list with paragraphs in certain items. I believe that this is not really what most people would expect the output to be.

According to [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+List+Item%0A*+Other+List+Item%0A%0A1.+New+list%0A2.+More+list+items) this behaviour comes from the original Markdown.pl library, however the majority of markdown libraries tested by Babelmark have changed the behaviour to output the two lists as a bulleted list followed by an ordered list.

You can also see in [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+Item+1%0A2.+Item+2%0A%0A*+Item%0A*+Item) that the same is true for the inverse - the majority of markdown libraries have changed away from the original behaviour.

I realise changing this would be backwards incompatible, but I believe it's unlikely many people rely on the existing behaviour - therefore I'd like to propose the behaviour be changed to match the behaviour that Babelmark shows:

That is 

```
* Item 1
* Item 2

1. Item 1
2. Item 2
```

Converts to this in showdown currently:

```
<ul>
    <li>Item 1</li>
    <li>
        <p>Item 2</p>
    </li>
    <li>
        <p>Item 1</p>
    </li>
    <li>Item 2</li>
</ul>
```

I propose it ought to output:

```
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
</ul>
<ol>
    <li>Item 1</li>
    <li>Item 2</li>
</ol>
```

**Comment by tivie** [comment]
Yeah, this is a known issue. We still haven't come to an agreement if we should stick to the original behaviour or not.

Personally I think this should be seen as a bug, as it doesn't really make sense. (same goes for adding paragraphs in lists)

**Comment by tivie** [comment]
related to https://github.com/showdownjs/showdown/issues/41

**Comment by ErisDS** [comment]
I completely understand that making changes to markdown behaviour when the library is following the original implementation is a tricky decision. I don't suggest going against the original lightly :)

In this particular case, I think the current output is very clearly unexpected behaviour and therefore the original behaviour can be classified as incorrect / a bug. Also as I mentioned, I think the particularly odd nature of this means it's very very unlikely anyone is relying on this behaviour.

I'd also add that using babelmark to test snippets often comes up with quite a wide range of different implementations and in this particular case it's very clear that the majority of parsers have opted to classify the original behaviour as incorrect. Therefore I think it is pretty safe to follow suit, lest showdown become the only library still following the old way.

Nonetheless, I fully respect that this is not an easy decision to make. Some parsers have a normal version, and a 'strict' version for this sort of thing, but I do believe that's overkill in this particular case.

**Comment by pdeschen** [comment]
@ErisDS I like your idea of `strict` mode. Or maybe `quirks` would be more appropriate. But then again, which of the rendering is the quirk one? :smile:

**Comment by tivie** [comment]
So, I've tried to reach John Gruber by email to ask what it's opinion on this particular issue but he didn't answer (go figures =P). So I say we fix this in the next release.

@pdeschen @SyntaxRules what's your take on this?

**Comment by tivie** [comment]
@ErisDS The commit 0bdd02b partially fixes the issue. 

Now

```md
* item 1
* item 2

1. item 1
2. item 2
```

is parsed into

```html
<ul>
    <li>Item 1</li>
    <li><p>Item 2</p></li>
</ul>
<ol>
    <li><p>Item 1</p></li>
    <li>Item 2</li>
</ol>
```

I couldn't pinpoint the origin of the issue with the extra paragraphs, I will have a look as soon as possible

**Comment by tivie** [comment]
7720c88 now totally fixes this issue.

```
* item 1
* item 2

1. item 1
2. item 2
```

gets parsed into

```
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
</ul>
<ol>
    <li>Item 1</li>
    <li>Item 2</li>
</ol>
```
