### ISSUE TITLE
image support for resize

### ISSUE THREAD

**Issue by Dexus** [showdownjs/showdown#143]
hi some markdown dialects support sizes (like the following)

`![](./pic/pic1_50.png =100x20)`

is ther a plan to support it?

**Comment by tivie** [comment]
Hello @Dexus. Although it is a nice feature, the original specification does not include it. I believe this should be implemented as post-processing extension and not in the core library.

**Comment by pdeschen** [comment]
@tivie as it is not a breaking change addition, maybe it could be part of core?

**Comment by fir3pho3nixx** [comment]
I strongly disagree. Images should have first class support.

**Comment by tivie** [comment]
This will probably make it in the next release, as an opt in feature.( means you have to enable it explicitly)

**Comment by tivie** [comment]
Through options

**Comment by tivie** [comment]
Added this feature as an opt in. To enable it you must use the option `parseImgDimensions`

example:
```js
var conv = new showdown.Converter({parseImgDimensions: true});
```

**Comment by fir3pho3nixx** [comment]
Great stuff, thank you :)

**Comment by bansalvks** [comment]
is it possible that we set the `height `only and the `width` will be auto calculated accordingly so that the image does not look awkward?

**Comment by rgpd-2018** [comment]
@bansalvks you can do it by specifying a star (*) for example : 
![my image](foo.jpg =200x* "some title")
![my image](foo.jpg =*x200 "some title")

**Comment by charlesthk** [comment]
@bansalvks you can do it by specifying a star (*) for example : 
![my image](foo.jpg =200x\* "some title")
![my image](foo.jpg =*x200 "some title")
