### ISSUE TITLE
Allow id generation to be disabled or customized

### ISSUE THREAD

**Issue by Lusito** [showdownjs/showdown#145]
Having ids generated will create conflicts with other elements in the html that might use the same id.
In my case, I never need the generated ids, so I'd like to be able to completely remove them.

**Comment by pdeschen** [comment]
Disabling would be a nice addition. What about an id prefix as well? Something like 'showdown-' or  'sdn-'

**Comment by tivie** [comment]
Related to https://github.com/showdownjs/showdown/issues/82.
Id clash should be solved in https://github.com/showdownjs/showdown/commit/c367a4b9a18530ac662bb67ca4b09419680f0c34 
(from v2 branch)

Worth backporting to legacy, maybe?
