### ISSUE TITLE
Mess with id's of headers

### ISSUE THREAD

**Issue by chtixof** [showdownjs/showdown#151]
Hello.
`# Title` generates `<h1 id="title">Title</h1>`
Well... This is very annoying if the page already have a tag with id="title".
Is it possible not to add those id's ?
For ever or just with a parameter.
Other suggestion: add a prefix to the id (for example "showdown-")
Thanks.

**Comment by pdeschen** [comment]
Related to #145 which is related to #82. Should be fixed once merged.

**Comment by chtixof** [comment]
OK, Merci Pascal.
