### ISSUE TITLE
Table Format?

### ISSUE THREAD

**Issue by johnjelinek** [showdownjs/showdown#152]
| The | Nice | Table |
| ----- | ------ | -------- |
| This should render | as a table | in html |

```
| The | Nice | Table |
| ----- | ------ | -------- |
| This should render | as a table | in html |
```

**Comment by jcbrand** [comment]
It already exists as an extension, see here: https://github.com/showdownjs/showdown/blob/master/src/extensions/table.js

**Comment by tivie** [comment]
@jcbrand is right. Closing

**Comment by pdeschen** [comment]
@johnjelinek do you have suggestion regarding the documentation setup that we could improve in order for people like you to easily spot extensions besides our [wiki page](https://github.com/showdownjs/showdown/wiki/extensions#list-of-known-extensions)

**Comment by johnjelinek** [comment]
table is a little strange as an extension, isn't it?

**Comment by tivie** [comment]
@johnjelinek Not at all. This type of table syntax is non-standard. In fact, the [original markdown spec](http://daringfireball.net/projects/markdown/) does not include tables at all (just through html inclusion). Showdown core library tries to follow this spec as much as possible. This is why tables are provided as an extension, not int he core

**Comment by johnjelinek** [comment]
oic. I think in terms of docs, I wasn't expecting to search for extensions to find tables.

**Comment by 8Miles-Mai** [comment]
Where can I get the extension, the follow url is missing now.
https://github.com/showdownjs/showdown/blob/master/src/extensions/table.js
