### ISSUE TITLE
1.0.2 breaks my instantiation of converter

### ISSUE THREAD

**Issue by JonathanHayward** [showdownjs/showdown#157]
I recently upgraded the version of Showdown in my webapp from 0.9.x to 1.0.2; my inclusion now reads:

    <script
      src="//cdnjs.cloudflare.com/ajax/libs/showdown/1.0.2/showdown.js">
    </script>

However, when in my code I called as per http://showdownjs.github.io/showdown/:

  var converter = new Showdown.converter();

it ceased working with either (s)howdown or (S)howdown. (S)howdown was not defined; when I changed my code to reference (s)howdown, the error changed to "undefined is not a function", apparently because showdown.converter is not defined.

Did 1.x include API changes that the page is out of sync with? If "var converter = new Showdown.converter();" is out of sync with 1.x, what should I be doing to get a new converter / instead of getting a new converter? If there's not a ready answer, what would be a good older cdnjs URL to revert to?

Thanks,

**Comment by pdeschen** [comment]
@JonathanHayward Hum interesting. You just cut us in the middle of our release, where we have component that haven't been updated completed and hence the out of sync issue you're facing. Hang in tight, we'll resolve those bumps shortly.

New instance from 1.x are now using the following construction

```
var converter = new showdown.Converter();
```

That being said, I thought we were backward compatible in terms of API. @tivie ?

**Comment by JonathanHayward** [comment]
Thanks! My code runs without crashing now.

Thanks...

**Comment by tivie** [comment]
@JonathanHayward  v 1.0.0 breaks compatibility in a few key points.
[see CHANGELOG.md](https://github.com/showdownjs/showdown/blob/master/CHANGELOG.md). 

@pdeschen maybe we should add CHANGELOD.md contents to the webpage? make it visible so that people can find it easily?

**Comment by pdeschen** [comment]
@tivie Right forget about those bits. I just added a link to the changelog into the Help section of the website. Key here was to at least have the code sample in the "Use It" section to be valid. My bad!
