### ISSUE TITLE
Table of Contents extension [toc]

### ISSUE THREAD

**Issue by ravisorg** [showdownjs/showdown#159]
I threw one together for a project and thought others might find it useful as well. If anyone would find use for such a think, it exists here:

[showdown-toc](https://github.com/ravisorg/showdown-toc)

**Comment by tivie** [comment]
Interesting extension. Seems the code can be simplified a bit to remove the dependency on jquery.
Thanks for the contribution

**Comment by ravisorg** [comment]
That's a very good point and something that somehow completely slipped my mind while writing it. I want to make a couple enhancements / changes when I have a moment, and I'll add "remove jQuery" to that list.

**Comment by tivie** [comment]
If you need help let me know. you may also want to check the extension boilerplate. Although it's not really ready, (we're building it for the next release of showdown that will contain major changes to the extension mechanism) it can help you speed up development, specially with tests

github.com/showdownjs/extension-boilerplate

**Comment by JanLoebel** [comment]
Hi there, I started to write a TOC-Extension by myself. Have a look at: https://github.com/JanLoebel/showdown-toc   I ussed @tivie 's showdown-footnote-repository as a template. It's my first extension, if you have any problems or ideas please let me know :)
