### ISSUE TITLE
Overwrite element converter function

### ISSUE THREAD

**Issue by theking-laptop** [showdownjs/showdown#161]
Sometimes, I need to decorate transformed markdown element. For example,
```
# heading

-> <h1 my-attr="my-value">heading</h1>
```

I used [marked](https://github.com/chjj/marked) and it lets me do that. Would you want to expose a way to overwrite default converter function of all markdown element types?

**Comment by tivie** [comment]
@theking-laptop this is already possible. You can use two methods:
  - the documented one, by using a showdown (output) extension.
  - the undocumented one, by overriding a subparser completely.

You can override a subparser by redifining it. Check https://github.com/showdownjs/showdown/tree/master/src/subParsers
for the available parsers. If you need help with a specific question let me know.


The extension mechanism is also being rewritten and simplified. Those changes will prolly make it to the next release in the next couple of weeks.

**Comment by tivie** [comment]
Closing as there was no reply in 6 days
