### ISSUE TITLE
Include Github Flavored Markdown(GFM) in core as an option

### ISSUE THREAD

**Issue by tivie** [showdownjs/showdown#164]
## Introduction

Showdown tries to follow vanilla markdown (with all its quirks and perks) as much as possible but several related issues (see #96, #152, for instance) were raised requesting showdown to fully support GFM. 

(**See GFM differences from traditional Markdown [here](https://help.github.com/articles/github-flavored-markdown/#differences-from-traditional-markdown)**).

 Some features of GFM are already available from within showdown:

 - fence styled code blocks work by default
 - strikethrough (with `~~word~~`) is available as an extension: ([github-extension](https://github.com/showdownjs/github-extension))
 - tables are available as an extension ([table-extension](https://github.com/showdownjs/table-extension))
 - code highligth is available as an extension ([prettify-extension](https://github.com/showdownjs/prettify-extension))

However, other features require changing showdown's core parsers:

 - Multiple underscores in words - Markdown explicitely accepts in-word emphasis using underscores. GFM does not. To support both we would need to change the emphasis parser and add an option to enable/disable in-word emphasis.
 - URL autolinking - Markdown uses `<http://www.example.com>` autolink style. GFM autolinks `http://www.example.com`(no need to wrap in <>). A output extension might be able to take care of this, but the regex used would have to be complex to properly parse edge cases (for instance, a link inside a code block, or in a src attribute, etc...)

## Options

We have 2 options to deal with these requests:

 - Make extensions more "powerful" and allow them to override the core sub-parsers
 - Include those changes directly into core and add option(s) to activate/deactivate them.

and the third option... use both.

Thoughts?

**Comment by tivie** [comment]
Bumping @pdeschen @SyntaxRules

**Comment by SyntaxRules** [comment]
I think Adding in the [GFM](https://help.github.com/articles/github-flavored-markdown/) features is smart, and an easy way to compete with other parser's out there. 

[Marked](https://github.com/chjj/marked) does this via on option, but i would discourage putting it as an option in Showdown. The advantage Showdown has over Marked is that it is easily extendable. I think all of these quirky features should got in a GFM plugin. This plugin could depend upon other plugins. This way someone could pick and choose which items they want in there markdown.

If we feel strongly about including GFM features, we could include them by default.

**Comment by tivie** [comment]
@SyntaxRules Yeah, I agree. The only thing is that some features have to be included directly in core, since they would need to be run in a specific order, something that showdown extensions don't support.

**Comment by grofit** [comment]
A bit confused by this, I see in the documentation on the front page it mentions that `tables` and `strikethrough` are valid options for a convertor, which imply that showdown supports them by default. However looking on the wiki and at this issue imply that they are actually separate addons, so are the docs wrong or is there some mix up?

**Comment by tivie** [comment]
In short:
GFM is supported by showdown via options. Those options are disable by default. No extra extensions are needed.

-----------------------

> I see in the documentation on the front page it mentions that tables and strikethrough are valid options for a convertor, which imply that showdown supports them by default. 

Showdown supports them if you activate them via options. Else, you get vanilla markdown. Give it a try.

> However looking on the wiki and at this issue imply that they are actually separate addons, so are the docs wrong or is there some mix up?

Where in the wiki? Please add a link so we can update to make things a bit more clear.

This issue might confuse people since it refers to "plugins" which isn't accurate. Extra markdown features are implemented in separate subParsers. This means they can easily be turned on/off at will. That's what SyntaxRules was talking about.

**Comment by grofit** [comment]
https://github.com/showdownjs/showdown/wiki/extensions

That lists the extensions for table etc.

I did try to use the options and they didnt seem to change anything.

```
new showdown.Converter({
        simplifiedAutoLink: true,
        strikethrough: true,
        tables: true
    });
```

Then if I were to add
```
| *foo* | **bar** | ~~baz~~ |
|:------|:-------:|--------:|
| 100   | [a][1]  | ![b][2] |
```

as shown in the example, it does not get processed, it just outputs it within a `p` tag, unless I am doing something wrong.

**Comment by tivie** [comment]
Are you using version 1.2.0 ?

Enviado do meu iPhone

No dia 20/07/2015, às 16:22, LP <notifications@github.com> escreveu:

**Comment by grofit** [comment]
Sorry for the afk-ness, no I am on 1.1.0, but I only got that like a week or so ago, has it already changed so much? will go get latest and see what happens.

**Comment by ifeltsweet** [comment]
I'm actually for both options, but if have to choose only one then probably the first.
