### ISSUE TITLE
Test coverage for helpers.js

### ISSUE THREAD

**Issue by jeromecovington** [showdownjs/showdown#167]
Is there test coverage for `helpers.js`? And a related question: has there ever been talk of adding [underscore](https://github.com/jashkenas/underscore) as a dependency? This way showdown would get things like `isString`, `isArray`, etc. in addition to the test coverage maintained by that library.

**Comment by tivie** [comment]
Thanks @jeromecovington for the suggestion. We actually thought of using lodash as a dependency.However, we decided against it for the time being. 

The problem of having a dependency on a monolithic library such as underscore/lodash is that it can make showdown incompatible with other libraries that use a different version of said library in a browser environment.

One way of preventing version clash is to use the modularized version of lodash, using only the functions you really need and then embedding them directly into showdown, in their own namespace.

We will probably do that in the future, when we have the time.

**Comment by adam-beck** [comment]
@tivie Couldn't this be solved by bundling showdown? Then it shouldn't matter what version showdown uses vs the user. I agree, however, that only necessary functions should be pulled from the library.
