### ISSUE TITLE
Ghost's custom extensions broke on latest version

### ISSUE THREAD

**Issue by Sophie-OS** [showdownjs/showdown#173]
I'm using [ghost](https://ghost.org/) that comes with an old version of showdown bundled. I tried to update it to showdown's latest version but some of ghosts custom extensions broke.

I've checked your changelog and there is no mention of dropping support for old extensions. When did this happen? What is the right procedure to enable support for old extensions?

**Comment by tivie** [comment]
We still maintain support for old extensions, nothing changed. But from what I could gather, it seem ghost is using a fork from an old version of showdown, that made a couple of changes directly into core. 

Your best bet is to ask directly in the [ghost project issue tracker](https://github.com/TryGhost/Ghost/issues)

**Comment by Sophie-OS** [comment]
The lastest Ghost showdown is broken as they have a couple of nasty issues that couldn't fix yet.

I think Showdown being used as Ghost MD engine has increased showdown's popularity, as Ghost is a very popular blog system nowadays. 

Maybe Showdown's and Ghost's teams could work together to bring the latest awesome features in showdown to ghost?

I've managed to fix some issues in my local dev machine I can publish that might give a jump start in the project.

**Comment by tivie** [comment]
Ghost's Showdown is too far behind (and different) to backport all modifications and improvements.

However, I had a good look at Ghost's source code and it shouldn't be too hard to use Showdown (original!?) instead of showdown-ghost.

**Comment by tivie** [comment]
@Sophie-OS follow up on https://github.com/ErisDS/showdown/issues/5

Closing issue here
