### ISSUE TITLE
Core table functionality not working as expected?

### ISSUE THREAD

**Issue by grofit** [showdownjs/showdown#179]
So I have got 1.2.0 and have enabled tables option and used the example markup

<pre>
| *foo* | **bar** | ~~baz~~ |
|:------|:-------:|--------:|
| 100   | [a][1]  | ![b][2] |
</pre>

and it generates

![Image](https://dl.dropboxusercontent.com/u/98595151/ShareX/EMBERSOFT1/2015-07-21_08-35-53.png)

Now I was expecting that the headers would have their `*` and `~~` parsed into styling, however it just translates them directly, same with the output content. I am assuming it should be taking the styling in the headers into account?

**Comment by tivie** [comment]
Actually, this is by design since it follows md tables spec1. However spec 2 does allow span elements in the titles. see https://michelf.ca/projects/php-markdown/dingus/

I will add a milestone and implement it in a future release.

**Comment by grofit** [comment]
no worries, it just seemed odd that the example on the website included this if it is not supported.

**Comment by tivie** [comment]
Ah, good catch

**Comment by tivie** [comment]
Fixed it in the README.md

**Comment by tivie** [comment]
give it a shot 

https://github.com/showdownjs/showdown/pull/180

**Comment by grofit** [comment]
Just got the latest showdown.js from the dist folder on master and it still seems to be acting the same, the commit says its against master, could it just be that the dist was not updated?

**Comment by tivie** [comment]
you need to use the tivie-patch-1 branch

**Comment by grofit** [comment]
ah kk, will give it another go shortly, thanks again for the quick turn around.
