### ISSUE TITLE
merged lists

### ISSUE THREAD

**Issue by SimonButtazzi** [showdownjs/showdown#185]
Hey,
writing something like this:

*&nbsp;foo
*&nbsp;bar

test

1.&nbsp;foo
2.&nbsp;bar

works fine: Creates &lt;ul&gt; followed by "test" and &lt;ol&gt;.
But doing something like this:

*&nbsp;foo
*&nbsp;bar

1.&nbsp;foo
2.&nbsp;bar

merges the two lists into one using style of the first one. In this case it will be &lt;ul&gt;.

**Comment by tivie** [comment]
@SimonButtazzi What version are you using?

Check [http://showdownjs.github.io/demo/](http://showdownjs.github.io/demo/). It uses showdown latest (currently v 1.2.2) and is working properly with your example

**Comment by SimonButtazzi** [comment]
@tivie you are right.
this was included in another package and very outdated.

Sorry, definitively my mistake.

Simon
