### ISSUE TITLE
simplifiedAutoLink with Mail Links

### ISSUE THREAD

**Issue by ColinFrick** [showdownjs/showdown#187]
With simplifiedAutoLink mail addresses in the text are not parsed correctly:
```
 example@example.com
```
is parsed to
```
 <a href="example@example.com">example@example.com</a>
```
instead of
```
 <a href="mailto:example@example.com">example@example.com</a>
```

simplifiedAutoLink does not use the internal replaceMail function.

**Comment by tivie** [comment]
should be fixed now

**Comment by ColinFrick** [comment]
Thanks!
