### ISSUE TITLE
remove root paragraph

### ISSUE THREAD

**Issue by soubok** [showdownjs/showdown#189]
I would like to use showdown to convert small markdown strings and I would like to remove single surrounding paragraph tags.
Currently I use a regexp to achieve this but I wondering if there is a more elegant way to do this.
Is your extension mechanism suitable for it ?
Thanks.

**Comment by tivie** [comment]
Yes, a lang extension would be suitable for this. 

For instance, if all you want is to parse span elements (suchs as bold, italics, inline code, etc...) you can create a lang extension that catches all text and then passes it through spanGamut subSparser.

**Untested code**
```js
showdown.extension('myExt', function() {
  return [{
    type: 'lang',
    regex: /[\s\S]*/g,
    replace: function(txt) {
        var globals = {
          gHtmlBlocks: [],
          gUrls: {},
          gTitles: {},
          gDimensions: {}
        };
        return showdown.subParser('spanGamut')(txt, {}, globals);
    }
  }];
});
```

This is just a crude example, but you get the idea.

**Comment by tivie** [comment]
Another **less** hackish way is to use an output extensions that replaces the `<p>` tags


**untested code: works only in browser**
For this to work on node, you must use a DOM parser
```js
showdown.extension('myExt', function() {
  return [{
    type: 'output',
    filter: function(txt, conv, opts) {
      var div = document.createElement('div');
      var finalTxt = '';
      div.innerHTML = txt;
      for (var i=0; i<div.children.length; ++i) {
      if (div.children[i].tagName.toLowerCase() === 'p') {
        finalTxt += div.children[i].innerHTML;
      }
      return finalTxt;
    }
  }];
});
```

**Comment by soubok** [comment]
Thanks for your response. In fact I just want to make ```markdownConverter.makeHtml('hello **world**')``` to return ```'hello <strong>world</string>'``` instead of ```'<p>hello <strong>world</string></p>'```. (I am using showdown with nodejs)

**Comment by tivie** [comment]
@soubok Then the solutions I gave you should work.

**Comment by tivie** [comment]
No follow up in over 2 months, closing this up
