### ISSUE TITLE
Get converter options in extension

### ISSUE THREAD

**Issue by d-sko** [showdownjs/showdown#190]
Hi, I have a question about lang extensions: it is possible to get the current converter options (not the global default options, but the options passed to the converter-constructor or set by `converter.setOption()`) in the replace function?

**Comment by tivie** [comment]
@d-sko In the replace function no. But you can get them in the filter function

example:

```js
showdown.extension('myExt', function() {
  return [
    type: 'lang', //or output
    filter: function(txt, conv, opts) {
      var rgx = /someRx/g;
      txt.replace(rgx, function(matches) {
        //do something with opts
        return matches;
      });
    }
  ];
});
```

**Comment by d-sko** [comment]
@tivie that solved my problem, thank you :+1:
