### ISSUE TITLE
Plans to support Inline Attribute Lists? 

### ISSUE THREAD

**Issue by alanguir** [showdownjs/showdown#195]
My favorite feature from kramdown/jekyll is Inline Attribute lists, which look like this:

```
What a great paragraph
{: .panel}
```

Spec here: http://kramdown.gettalong.org/syntax.html#inline-attribute-lists. 

Has any work been done to support this kind of thing? I haven't found a single *.js implementation that brings this functionality over from the various ruby libraries that support it. I'm happy to lend a hand in making it happen.

**Comment by tivie** [comment]
@alanguir Thanks for the suggestion. Showdown tries to keep faithful to the original spec. The new features and changes we introduced were always as "opt-in" and based on the discussions found at the "official" markdown mailing list.

However, showdown is extensible exactly with the purpose of letting people create and use non standard features. It shouldn't be very hard to implement *inline attribute lists* a lang extension.

If you're up to it, I can give you a hand.

**Comment by alanguir** [comment]
I'll give it a go - can you point me towards a reasonable starting point in the codebase? I haven't had time yet to get familiar with how showdown is structured.

**Comment by tivie** [comment]
you can use this extension as boilterplate: https://github.com/showdownjs/youtube-extension/blob/master/src/showdown-youtube.js

**Comment by obedm503** [comment]
any update one this? I'm also willing to help out.

**Comment by urmilparikh** [comment]
+1

**Comment by obedm503** [comment]
can anyone point me to the best way to achieve this?
