### ISSUE TITLE
Wrongly successively encoding entities in code blocks in nested lists 

### ISSUE THREAD

**Issue by twitwi** [showdownjs/showdown#196]
When using an entity (or a character that gets encoded as an entity) in a code block in a list, showdown seems to escape the entity multiple times, depending on the depth in the list.

Here is an example, where all & (using explicitly &amp; does not change the problem) inside code blocks get escaped too much:
http://showdownjs.github.io/demo/#/%23%23%20Test%20pre%20in%20a%20list%0A-%20%26%0A-%20%60%26%60%0A%20%20%20%20-%20%26%0A%20%20%20%20-%20%60%26%60%0A%20%20%20%20%20%20%20%20-%20%26%0A%20%20%20%20%20%20%20%20-%20%60%26%60%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%26%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%60%26%60

I discovered the problem outside the demo (i.e., I think the problem does not come from the demo code).

I'll have a quick look but I'm not familiar with the showdown code so I will most probably not manage to solve the problem.

**Comment by twitwi** [comment]
NB: markdown seems to require escaping "&" and "<", but, as mentioned above, the problem is also visible with characters that lead to non-mandatory entity encoding such as ">" as in this example:
http://showdownjs.github.io/demo/#/%23%23%20Test%20pre%20in%20a%20list%0A-%20%3E%0A-%20%60%3E%60%0A%20%20%20%20-%20%3E%0A%20%20%20%20-%20%60%3E%60%0A%20%20%20%20%20%20%20%20-%20%3E%0A%20%20%20%20%20%20%20%20-%20%60%3E%60%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%60%3E%60

**Comment by tivie** [comment]
This bug was introduced recently. I'm still trying to figure out which commit introduced this.
I expect to be able to fix this in 3 weeks or so.

**Comment by tivie** [comment]
I've tracked the problem to version 1.2.1

**Comment by tivie** [comment]
This should be fixed in the latest develop

**Comment by twitwi** [comment]
Great, thanks. (not tested yet)
