### ISSUE TITLE
literalMidWordUnderscores changes behavior of '*'

### ISSUE THREAD

**Issue by twitwi** [showdownjs/showdown#198]
This is probably not a first priority issue.

Considering the following markdown: `pointer *ptr *thing​` (I'm not sure how it should be interpreted).
Toggling the `literalMidWordUnderscores` options unexpectedly changes the rendering:
- without the option, stars remain un-transformed
- with the option, stars are considered as emphasis

**Comment by tivie** [comment]
@twitwi thanks. I will look into this as soon as possible.

**Comment by twitwi** [comment]
No problem, it's more something I stumbled upon in a very special situation.
Actually #196 happens more often in my use cases (but might be trickier, from my first experiments with showdownjs source code)
