### ISSUE TITLE
Should sourceMappingURL comments be included in bower distributions?

### ISSUE THREAD

**Issue by nikz** [showdownjs/showdown#200]
Hi Team!

First off, thanks for Showdown - it's a really useful package. :+1: 

I'm having a bit of trouble when integrating the bower package into my workflow though, specifically with the `sourceMappingURL` comments (see [my comment on the ember-cli-uglify](https://github.com/ember-cli/ember-cli-uglify/issues/4#issuecomment-140712858) package for more detail).

In short, the bower package doesn't include any of the `src/` files, but the files in `dist/` have generated source maps that point to those files (and the comments that in turn point to those map files).

Would you folks be open to a change to the gruntfile in order to not generate source maps when building a package for distribution? Or would you prefer an alternate solution?

Thanks!

Nik

**Comment by tivie** [comment]
Hey @nikz. Thank you for your kind words.

It seems the best way is not to include a src map for the concatenated files in the bower package (it does not make much sense since it points to non existent files).

The regular package would keep them.

**Comment by nikz** [comment]
@tivie: OK, great - would you like me to make the grunt modifications to exclude the map files? I can potentially handle that. :)

**Comment by tivie** [comment]
@nikz No grunt modifications needed. The only thing needed is to make bower ignore map files. Although I'm kind of conflicted about it since map files are extremely useful for debugging.

**Comment by nikz** [comment]
@tivie definitely agree, but without the files in `src` they aren't so useful? So we should either exclude the map files or include the source files?

**Comment by tivie** [comment]
@nikz If we remove the map files from bower but keep the sourcemap comments, would it fix the problem?

**Comment by nikz** [comment]
@tivie I'm not 100% sure - I've just been removing the comments :) Let me give that a go today and get back to you?

**Comment by nikz** [comment]
@tivie I just end up getting a message like the following:

```Warning: ignoring input sourcemap for bower_components/showdown/dist/showdown.js because ENOENT, no such file or directory '/Users/nik/Projects/gelato/ember/tmp/concat_with_maps-input_base_path-WJdhcaUE.tmp/0/bower_components/showdown/dist/showdown.js.map```

But everything works! :+1:

**Comment by tivie** [comment]
OK, so after some thought I think it might be better to include the src files in bower distributions. It increases download size a bit but, apart from that, I don't see any inconveniente.

@nikz What do you think?!

**Comment by nikz** [comment]
@tivie I think that would be fine, so long as they aren't getting built for distribution or anything like that. Means that the source map URLs have something to point to!

**Comment by tivie** [comment]
Should be fixed now.
