### ISSUE TITLE
Code blocks that parse the language correctly on GitHub don't parse with Showdown

### ISSUE THREAD

**Issue by PaulBGD** [showdownjs/showdown#203]
Basically all of the code blocks that use 3 ` don't set the language correctly For example, this works here:
```javascript
foo.bar();
```
But if I inputted the markdown into showdown it would set the language as `javascript

**Comment by PaulBGD** [comment]
Oh, and after the code block it leaves a single
`

**Comment by tivie** [comment]
Hey @PaulBGD 

I could not reproduce the issue. Take a look at [the demo](http://showdownjs.github.io/demo/#/%60%60%60javascript%0Afoo.bar()%3B%0A%60%60%60). It seems to parse correctly.

Are you using any extensions?

**Comment by PaulBGD** [comment]
I apologize, turns out I accidentally used 4 `
