### ISSUE TITLE
Code render error

### ISSUE THREAD

**Issue by yaniswang** [showdownjs/showdown#205]
http://showdownjs.github.io/demo/

	````html
	<script type="text/javascript" src="htmlhint.js"></script>
	<script type="text/javascript">
		var messages = HTMLHint.verify('<ul><li></ul>', {'tag-pair': true});
	</script>
	````
Place the code in the demo, you will see a tailer in end.

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/10335328/77438ddc-6d22-11e5-93b9-e6536be6d7dd.png)

**Comment by tivie** [comment]
Fenced code blocks (aka github code blocks) should use **3 accents** and not 4 accents like you're using in the exemple

**Comment by tivie** [comment]
````html
<script type="text/javascript" src="htmlhint.js"></script>
<script type="text/javascript">
    var messages = HTMLHint.verify('<ul><li></ul>', {'tag-pair': true});
</script>
````

**Comment by tivie** [comment]
Github ignores the extra tick but it is not the correct syntax

**Comment by tivie** [comment]
See example here http://showdownjs.github.io/demo/#/Test%0A%0A%60%60%60html%0A%3Cscript%20type%3D%22text%2Fjavascript%22%20src%3D%22htmlhint.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20type%3D%22text%2Fjavascript%22%3E%0A%20%20%20%20var%20messages%20%3D%20HTMLHint.verify('%3Cul%3E%3Cli%3E%3C%2Ful%3E'%2C%20%7B'tag-pair'%3A%20true%7D)%3B%0A%3C%2Fscript%3E%0A%60%60%60

**Comment by yaniswang** [comment]
Tks
