### ISSUE TITLE
ReferenceError: getDefaultOpts is not defined

### ISSUE THREAD

**Issue by jack-nie** [showdownjs/showdown#212]
I'm using 1.3.0 with webpack.
I try `npm install --save-dev showndown`, and require it in my source file.
All the builds are fine,but when i run my app, It says `ReferenceError: getDefaultOpts is not defined`,
what's wrong?

**Comment by tivie** [comment]
I believe `npm install --save-dev showndown` is a typo since the library is called showdown

Regardless, more information is  needed. What file is "required" by webpack? Are you using the dist files or src files?

Can you post the relevant part of your code?

**Comment by jack-nie** [comment]
var Showdown = require("showdown");

var converter = new Showdown.converter();
var Comment = React.createClass({
  render: function() {
    var rawMarkup = converter.makeHtml(this.props.children.toString());
    return (
      <div className="comment">
        <h2 className="commentAuthor">
          {this.props.author}
        </h2>
        <span dangerouslySetInnerHTML={{__html: rawMarkup}} />
      </div>
    );
  }
});

package.json:

  "devDependencies": {
    "react-hot-loader": "~1.3.0",
    "babel-core": "~5.8.25",
    "babel-loader": "~5.3.2",
    "showdown": "~1.3.0",
    "fs": "0.0.2",
    "jquery": "~2.1.4"
  },
  "dependencies": {
    "react-dom": "~0.14.0",
    "react": "~0.14.0",
    "showdown": "~1.3.0",
    "jquery": "~2.1.0"
  }

**Comment by jack-nie** [comment]
it's my spelling mistake..sorry!
