### ISSUE TITLE
Version 1.3.0 not working (globals.converter._dispatch is not a function)

### ISSUE THREAD

**Issue by Kreozot** [showdownjs/showdown#213]
Actually there is simple makeHtml call which breaks after 1.3.0 release.

You can view an example in mdoc:
Original issue: https://github.com/millermedeiros/mdoc/issues/50
Using showdown: https://github.com/millermedeiros/mdoc/blob/master/src/js/parser.js

**Comment by Kreozot** [comment]
Sorry, it was my fault: I'm not bind makeHtml method properly.

**Comment by tivie** [comment]
@Kreozot  no prob, glad I could help
