### ISSUE TITLE
Escaped markdown characters seem to break parsing

### ISSUE THREAD

**Issue by hbCyber** [showdownjs/showdown#214]
I'm using Showdown with the strikethrough option enabled.

Example input that works:
`Your friend ~~[**test**](www.google.com)~~ (~~[*@test*](www.google.com)~~) updated his/her description.`

Correctly results in:
`<p>Your friend <del><a href="www.google.com"><strong>test</strong></a></del> (<del><a href="www.google.com"><em>@test</em></a></del>) updated his/her description.</p>`

However, this input, where the username includes an asterisk, won't work:
`Your friend ~~[**test\***](www.google.com)~~ (~~[*@test*](www.google.com)~~) updated his/her description.`

It will result in messed up `<del>` tags and leaves some `~~` characters in the result:
`<p>Your friend ~~<a href="www.google.com"><strong>test*</strong></a><del> (</del><a href="www.google.com"><em>@test</em></a>~~) updated his/her description.</p>`

**Comment by tivie** [comment]
@hbCyber thanks. Bug confirmed! 

http://showdownjs.github.io/demo/#/Your%20friend%20~~%5B**tes%5C*t**%5D(www.google.com)~~%20(~~%5B*%40test*%5D(www.google.com)~~)%20updated%20his%2Fher%20description

**Comment by tivie** [comment]
Should be fixed in 5669317

**Comment by hbCyber** [comment]
Thanks! Well done!
