### ISSUE TITLE
iframe Support

### ISSUE THREAD

**Issue by iamchairs** [showdownjs/showdown#217]
Please add iframe support for markdown. Not to add new tags to support iframes (though that would work) but not to exclude iframes. Currently have a mix of markdown and iframes I need to support.

**Comment by tivie** [comment]
showdown does not exclude iframes. You can see an example here:

http://showdownjs.github.io/demo/#/%3Ciframe%20src%3D%22http%3A%2F%2Fwww.w3schools.com%22%3E

What version are you using?

**Comment by iamchairs** [comment]
Using BTF-Markdown for angular which it looks like it's using version `~0.3.1` of showdown.

**Comment by tivie** [comment]
That version is very outdated (current version is 1.3.*)
You should ask BTF to use a more updated version.

Alternatively, you might want to check ng-showdown (https://github.com/showdownjs/ng-showdown) the official angular integration for showdown.

**Comment by adarmanto** [comment]
> showdown does not exclude iframes. You can see an example here:
> 
> http://showdownjs.github.io/demo/#/%3Ciframe%20src%3D%22http%3A%2F%2Fwww.w3schools.com%22%3E
> 
> What version are you using?

It doesn't work anymore, any idea?
