### ISSUE TITLE
How can I prevent my converter from escaping HTML?

### ISSUE THREAD

**Issue by heejongahn** [showdownjs/showdown#218]
I guess showdown automatically escape HTML special characters, such as '<' or '&', in my codeblock. And I don't want that.

So it goes like this. When I write something like this in markdown:
<img width="677" alt="ss 2015-11-11 at 11 40 41 pm" src="https://cloud.githubusercontent.com/assets/6768840/11093520/0752fd42-88ce-11e5-831d-cfcda9d19e77.png">

It turns out to something like this(see those &amp?):
<img width="734" alt="ss 2015-11-11 at 11 40 56 pm" src="https://cloud.githubusercontent.com/assets/6768840/11093525/0def2950-88ce-11e5-8b6e-89c86ca8125f.png">

First I thought it has sth to do with my DB encoding so I checked it, and there's no problem. Also, this doesn't happen for other HTML tags like h1 or so. 

In fact, I found out that this problem occurs only when showdown renders codeblock. I tried to figure out why but I couldn't so I'm posting this.

1. Am I doing something wrong here?
2. If not, is this behavior intended one?
3. If so, is there anything I can do to turn that option off? **or** If not, are you have any plans to fix it?

I'll be waiting for your answer. Thank you in advance.

P.S.) I'm using showdown as a markdown renderer for my own blog and I'm really satisfied with it. Thanks for making this!

**Comment by tivie** [comment]
Hey @heejongahn. Thank you!

Regarding your issue, Maybe I'm miss-understanding you but I couldn't reproduce it. I've tested with every release from 1.0.0 onward and could not reproduce the behavior you describe.

You can test it yourself with [our demo](http://showdownjs.github.io/demo/#/foo%0A%0A%60%60%60%0A%23!%2Fbin%2Fsh%0Aunset%20GIT_DIR%20%26%26%20cd%20%2Fhome%2Fme%2Fmyproject%20%26%26%20git%20pull%20%26%26%20foo%20bar%20--destination%20%2Fvar%2Fwww%2Fmyproject%2F%0A%60%60%60)

**Comment by heejongahn** [comment]
@tivie Well that's strange..

I'm using showdown 1.2.3, serving my service using flask(python3) + uWSGI + nginx at Ubuntu 14.04. Mayyyybe it could be because of Jinja2 template engine, but the thing is when I delete markdown rendering code below:

```
<script>
var md = $(".markdown.postbody").html();
var converter = new showdown.Converter();
converter.setOption('strikethrough', true);
var html = converter.makeHtml(md);
$(".markdown.postbody").html(html);
</script>
```

the page has no problem showing '&' and '>' and all that stuff. So I guessed it has something to do with showdown prolly.. but as you said so, I'll try to figure this out. I'll let you know if I find what was wrong. Thanks for your quick and kind reply! :+1:

**Comment by heejongahn** [comment]
I also checked that variable `html ` up there itself is containing `&amp;` using `console.log`. Still have no idea.

... and after I wrote that sentence above, I checked the value of `md` with console, and found out it's escaped too. So it was jQuery, not showdown or jinja2... Stupid of me. I'll close this issue :( Thanks anyway!

**Comment by tivie** [comment]
no problem glad you worked it out

**Comment by ngodichat** [comment]
I am encountering the same problem with showdown 1.9.1.
The text is "# FAQ - Frequently Asked Questions & Answers"
the text after using converter.makeHtml('# FAQ - Frequently Asked Questions & Answers') changed the & to &amp;
Can you show me how to fix it? Thank you!

**Comment by tivie** [comment]
@ngodichat in html, `&` must be escaped as an HTML entity because it's a special character,
