### ISSUE TITLE
HTML broke markdown parsing

### ISSUE THREAD

**Issue by ferllings** [showdownjs/showdown#220]
Hello,

I ran into an issue when having multiple HTML raw code inside a long Markdown document.

I reduced the code into the minimal reproductible sample:

```
Title 1
-------

<div></div>

# Title 2

<div>
</div>
```

It produce
```
Title 1
# Title 2
```
The Title 2 is not converted to html

You can try it on [http://showdownjs.github.io/demo/](http://showdownjs.github.io/demo/#/Title%201%0A-------%0A%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%0A%23%20Title%202%0A%0A%3Cdiv%3E%0A%3C%2Fdiv%3E)

**Comment by ferllings** [comment]
Hello,

Any confirmation about this bug?

**Comment by tivie** [comment]
Yes, I'm currently looking into it, I expect to have a fix soon.

**Comment by ferllings** [comment]
Thanks a lot!

**Comment by tivie** [comment]
Ok, this issue took a lot longer than expected. I had to make quite some changes in hashHTMLBlock in order to make it work smarter.

This issue should be fixed now in commit 2746949. 

@ferllings Do you mind testing it a bit further?

**Comment by matatk** [comment]
Of course we should leave it to @ferllings, as the OP, to confirm, but I thought I'd say that this fix does seem to work very well from my perspective; thank you!

**Comment by tivie** [comment]
thanks @matatk
