### ISSUE TITLE
Dedicated Page for Showdown Syntax

### ISSUE THREAD

**Issue by jmuharsky** [showdownjs/showdown#223]
While the demo site is handy, the inclusion of installation instructions makes it a less than optimal choice for linking "Here's how Showdown Markdown works".  Recommend taking the formatting-related content from the demo page, and making a wiki page out of it.

I've already done this on my project site (which implements Showdown), and you're welcome to copy it.

https://github.com/GoogleCloudPlatform/PerfKitExplorer/wiki/Showdown-Markdown-Syntax

**Comment by tivie** [comment]
I've updated showdown's syntax wiki page.

https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax

If you feel there's something missing please let me know
