### ISSUE TITLE
Extensions "DEPRECATION WARNING" but no documentation

### ISSUE THREAD

**Issue by approxit** [showdownjs/showdown#224]
I just realized that I'm getting `DEPRECATION WARNING: some_extension is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!` with my extensions, but there is no documentation how to make it in "new way".

**Comment by tivie** [comment]
You're absolutely right. I will update the documentation as soon as possible.

**Comment by ErisDS** [comment]
Just an FYI here - I would also really appreciate some info about what's changing and how to use it! 😁

**Comment by tivie** [comment]
My fault. [I've updated the wiki to reflect the new extension loading mechanism.](https://github.com/showdownjs/showdown/wiki/Extensions/)

Regardless, is some boilerplate code for extensions, with conditional loading and showdown's new proper loading mechanism.

```js
(function (extension) {
  if (typeof showdown !== 'undefined') {
    // global (browser or nodejs global)
    extension(showdown);
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['showdown'], extension);
  } else if (typeof exports === 'object') {
    // Node, CommonJS-like
    module.exports = extension(require('showdown'));
  } else {
    // showdown was not found so we throw
    throw Error('Could not find showdown library');
  }

}(function (showdown) {

  // loading extension into shodown
  showdown.extension('myext', function () {
    var myext = { /* ... actual extension code ... */ };
    return [myext];
  });
}));
```
