### ISSUE TITLE
Inline markdown table is not working

### ISSUE THREAD

**Issue by imaayush** [showdownjs/showdown#226]
Normal  markdown  is working fine but inline markdown table is not working.
![screenshot from 2015-12-29 12 26 08](https://cloud.githubusercontent.com/assets/8547523/12030643/e76fac12-ae27-11e5-966f-3a2e19b70111.png)

**Comment by tivie** [comment]
The lines must start and end with `|`

http://showdownjs.github.io/demo/#/%7C%20Markdown%7Cless%7CPreety%7C%0A%7C---%7C---%7C---%7C%0A%7C*still*%7Crenders%7C**nicely**%7C%0A%7C1%7C2%7C3%7C

**Comment by tivie** [comment]
https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax

**Comment by tivie** [comment]
Should be fixed in f58f014
