### ISSUE TITLE
HTML code tag on the same line with starting code block breaks everything

### ISSUE THREAD

**Issue by DoumanAsh** [showdownjs/showdown#229]
Noticed strange behavior of parser while testing with this [fixture](https://github.com/sindresorhus/generate-github-markdown-css/blob/master/fixture.md)

Try to parse text under **Code and Syntax Highlighting** section
http://i.imgur.com/7JWC4Cv.png

It happens when you have starting ```<code>``` and ``` on the same line.
If you separate it by newline everything will be fine

I saved this bad section on my google drive also:
https://docs.google.com/document/d/1AU-BEsR4bUnSXFtkuJfCylOaBrLmadCk7tqEzAThfS4/edit?usp=sharing

**Comment by tivie** [comment]
Thanks @DoumanAsh 

You are correct, the bug is verified. (can see in [demo page here][aa])

I will post a fix as soon as possible.


[aa]: http://showdownjs.github.io/demo/#/%3Cpre%20lang%3D%22no-highlight%22%3E%3Ccode%3E%0A%0A%60%60%60javascript%0Avar%20s%20%3D%20%22JavaScript%20syntax%20highlighting%22%3B%0Aalert(s)%3B%0A%60%60%60%0A%0A%60%60%60python%0As%20%3D%20%22Python%20syntax%20highlighting%22%0Aprint%20s%0A%60%60%60%0A%0A%60%60%60%0ANo%20language%20indicated%2C%20so%20no%20syntax%20highlighting.%0ABut%20let's%20throw%20in%20a%20%26lt%3Bb%26gt%3Btag%26lt%3B%2Fb%26gt%3B.%0A%60%60%60%0A%3C%2Fcode%3E%3C%2Fpre%3E

**Comment by DoumanAsh** [comment]
Glad to hear. I'm planning to replace ```marked``` in my simple client-side parser with ```Snowdown``` :)

**Comment by DoumanAsh** [comment]
Please note that markdown code symbols are missing inside of html ```<code>```.
Please check after fix that it will be corrected too :)

**Comment by tivie** [comment]
@DoumanAsh 

> Please note that markdown code symbols are missing inside of html <code>.

What do you mean?

**Comment by DoumanAsh** [comment]
See this [example](http://showdownjs.github.io/demo/#/%3Cpre%20lang%3D%22no-highlight%22%3E%3Ccode%3E%0A%0A%60%60%60javascript%0Avar%20s%20%3D%20%22JavaScript%20syntax%20highlighting%22%3B%0Aalert(s)%3B%0A%60%60%60%0A%0A%60%60%60python%0As%20%3D%20%22Python%20syntax%20highlighting%22%0Aprint%20s%0A%60%60%60%0A%0A%60%60%60%0ANo%20language%20indicated%2C%20so%20no%20syntax%20highlighting.%0ABut%20let's%20throw%20in%20a%20%26lt%3Bb%26gt%3Btag%26lt%3B%2Fb%26gt%3B.%0A%60%60%60%0A%0A%3C%2Fcode%3E%3C%2Fpre%3E)

Note that there are ```<code>``` blocks inside another ```<code>``` blocks.
At least in case of Github and marked markdown is not parsed inside html ```<code>``` block.
But i'm not sure what is right behavior though

**Comment by tivie** [comment]
@DoumanAsh I thought that was the issue you were talking about.

**Comment by DoumanAsh** [comment]
Sorry, there are actually two issues :)
[First](http://showdownjs.github.io/demo/#/%3Cpre%20lang%3D%22no-highlight%22%3E%3Ccode%3E%60%60%60javascript%0Avar%20s%20%3D%20%22JavaScript%20syntax%20highlighting%22%3B%0Aalert(s)%3B%0A%60%60%60%0A%0A%60%60%60python%0As%20%3D%20%22Python%20syntax%20highlighting%22%0Aprint%20s%0A%60%60%60%0A%0A%60%60%60%0ANo%20language%20indicated%2C%20so%20no%20syntax%20highlighting.%0ABut%20let's%20throw%20in%20a%20%26lt%3Bb%26gt%3Btag%26lt%3B%2Fb%26gt%3B.%0A%60%60%60%0A%0A%3C%2Fcode%3E%3C%2Fpre%3E)
[Second](http://showdownjs.github.io/demo/#/%3Cpre%20lang%3D%22no-highlight%22%3E%3Ccode%3E%0A%0A%60%60%60javascript%0Avar%20s%20%3D%20%22JavaScript%20syntax%20highlighting%22%3B%0Aalert(s)%3B%0A%60%60%60%0A%0A%60%60%60python%0As%20%3D%20%22Python%20syntax%20highlighting%22%0Aprint%20s%0A%60%60%60%0A%0A%60%60%60%0ANo%20language%20indicated%2C%20so%20no%20syntax%20highlighting.%0ABut%20let's%20throw%20in%20a%20%26lt%3Bb%26gt%3Btag%26lt%3B%2Fb%26gt%3B.%0A%60%60%60%0A%0A%3C%2Fcode%3E%3C%2Fpre%3E)

In these cases parser has different misbehavior

**Comment by tivie** [comment]
Both are consequence of the same issue that is the fact that GitHub code blocks insede HTML Code blocks get parsed by markdown engine while they shouldn't.

**Comment by tivie** [comment]
Should be fixed now

**Comment by DoumanAsh** [comment]
Looks great! Thanks

**Comment by DoumanAsh** [comment]
Should we close issue then?

**Comment by DoumanAsh** [comment]
Since it is fixed on develop branch i'm closing issue. No sense in leaving it opened?
