### ISSUE TITLE
Incorrect parsing of GFM tables with missing leading/trailing pipes

### ISSUE THREAD

**Issue by DoumanAsh** [showdownjs/showdown#230]
If you have missing leading or/and trailing ```|``` then table will not be rendered correctly

Example
```
|Markdown | Less | Pretty
|--- | --- | ---
|*Still* | `renders` | **nicely**
|1 | 2 | 3
```

**Comment by tivie** [comment]
https://github.com/showdownjs/showdown/issues/226

**Comment by DoumanAsh** [comment]
Oh sorry. It would be good to have that as feature, but if it is not possible since it conflicts with Snowdown specs then please feel free to close issue

**Comment by tivie** [comment]
You should be able to use GH spec with tables now

**Comment by DoumanAsh** [comment]
Great! Will it be part of default behavior or it is intended as optional feature?

**Comment by tivie** [comment]
default

**Comment by DoumanAsh** [comment]
Thanks
