### ISSUE TITLE
Block quotes not working as intended

### ISSUE THREAD

**Issue by Gacnt** [showdownjs/showdown#232]
I'm trying to use block quotes, I have

\> Blah blah

and then my JS to parse it is like:
```
$('.md').each((i, x) => {
        let converter = new showdown.Converter();
        $(x).html(converter.makeHtml($(x).html()));
    });
```

then it comes out like

\<p> > blah blah \</p>

Everything else works though, like images, headers, so on  so forth but block quotes don't seem to work

**Comment by tivie** [comment]
Couldn't [reproduce in the demo page][1]

can you provide a demo with the issue?



[1]:http://showdownjs.github.io/demo/#/%3E%20Blah%20blah

**Comment by Gacnt** [comment]
I'm saving plain textarea into the database as markdown, then loading it through the database and escaping the markdown to the page using jade template, and using that jquery loop to parse any divs labeled markdown. I see it does work on that demo, I'm not sure why it's not working on my end, feel free to close till I can reproduce it, but I'm not sure if I will be able to.

**Comment by tivie** [comment]
@Gacnt Check on each step if changes are being made to the text.

Maybe the > character is being escaped prior to markdown rendering
