### ISSUE TITLE
Is it possible to pick and choose only certain things to markdown?

### ISSUE THREAD

**Issue by jaesung2061** [showdownjs/showdown#238]
I would like for the converter to only parse bold, italics and strike-through tags. Is it possible to do this?

**Comment by tivie** [comment]
Out of the box no.

But you can try to hack around the subparsers with extensions.

1. Create a lang extension that calls the following subparsers:
    - italicsAndBold
    - strikethrough
2. Store the parsed text in a var and return empty string from that extension
3. Create an otp ext that returns the stored text


## Fiddle

https://jsfiddle.net/tivie/053f2j7z/

## Extension code

```js
showdown.extension('myext', function () {
  var store = '';
  var lngExt = function (text, converter, options) {
    var globals = {converter: converter};
    options.strikethrough = true;
    text = showdown.subParser('italicsAndBold')(text, options, globals);
    text = showdown.subParser('strikethrough')(text, options, globals);
    store = text;
    return "";
  };
  var otpExt = function (text, converter, options) {
    return store;
  };
  return [
    {
      type: 'lang',
      filter: lngExt
    },
    {
      type: 'output',
      filter: otpExt
    }
  ];
});
```
