### ISSUE TITLE
Add showdown-footnotes to the extension index

### ISSUE THREAD

**Issue by Kriegslustig** [showdownjs/showdown#240]
[`showdown-footnotes`](https://github.com/Kriegslustig/showdown-footnotes) is a showdown extension I wrote that adds footnote support. The implemented syntax is the most popular i could find<sup>0</sup>. Could you **add the extension to the wiki**?

<sup>0</sup>: The syntax is the same as in a [PHP-Markdown extension](http://rephrase.net/box/word/footnotes/syntax/), a [python markdown extension](https://pythonhosted.org/Markdown/extensions/footnotes.html), similar to [kramdown](http://kramdown.gettalong.org/syntax.html#footnotes),  [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#footnotes) and many more.

**Comment by pdeschen** [comment]
thanks @Kriegslustig . Done. Can you also add a link from your readme to this repo?

**Comment by Kriegslustig** [comment]
Thanks @pdeschen, I added the link :)
