### ISSUE TITLE
How to ignore/disable certain tags?

### ISSUE THREAD

**Issue by joemunriq** [showdownjs/showdown#241]
Is there a simple way to ignore/disable certain tags from being rendered (e.g. headings)?

For example, have plain text `# something` pass through the original content, rather than generating `<h1>something</h1>`.

Thanks!

**Comment by tivie** [comment]
Depends on your definition of simple.

You would have to create a lang extension that escapes `#` characters. See [fiddle][1]

```javascript
showdown.extension('myext', function() {
  return [{ type: 'lang', regex: /^#/gm, replace: '\\#' }];
});
```


[1]: https://jsfiddle.net/tivie/ws1c6v92/

**Comment by joemunriq** [comment]
Thanks for the quick response!

Wouldn't it be more efficient if there was a way to disable the parser?  Any chance you think it would make sense to add this functionality as options?  (e.g. taking in a list of enabled or disabled elements)

(Reason I'm proposing this is because I would only need a very small subset of the features. My concern is that it would be more bug-prone to have to write a new extension/regex for every disabled tag.)

Thanks!

**Comment by tivie** [comment]
The parsers depend on one another and the inorder they're called so, at the moment, it's not possible to cherry pick.

**Comment by joemunriq** [comment]
Thanks for the info

**Comment by joemunriq** [comment]
Ah, totally missed #238.  (Sorry for the dupe question.)
