### ISSUE TITLE
Unable to get tables rendered

### ISSUE THREAD

**Issue by socrates58** [showdownjs/showdown#242]
I built the node.js web page as in the tutorial, and my script.js looks like:
```
window.onload = function() {
    var converter = new showdown.Converter({tables: true});
    
options = converter.getOptions();
console.log(options);
    
    var pad = document.getElementById('pad');
    var markdownArea = document.getElementById('markdown');   

    var convertTextAreaToMarkdown = function(){
        var markdownText = pad.value;
        html = converter.makeHtml(markdownText);
        markdownArea.innerHTML = html;
    };

    pad.addEventListener('input', convertTextAreaToMarkdown);

    convertTextAreaToMarkdown();
};
```
when I input text like:

```
#### Server 1

| Server Name | Addresses | IP 1 | IP 2 |
| :---: | :---: | :---: | :---: |
| myServer | 10.1.2.3 | 10.2.3.4 | 10.3.4.5 |
```
my table doesn't get rendered, I just get text out. The options appear correct in the console.
Any ideas what I'm doing wrong?

**Comment by tivie** [comment]
What tutorial are you referring to?

Anyways, it's working fine with me. Check the [fiddle](https://jsfiddle.net/tivie/cocoso7y/)

**Comment by socrates58** [comment]
Estevão, thanks for the quick response. I downloaded the tutorial from the wiki, and the table gets rendered, though the header line isn't colored and there're a few other quibbles. I seem to be having version issues, with different behaviors from the CDN. We can close this.
Thanks again for the excellent response.
