### ISSUE TITLE
Can't load converter that will makeHTML()

### ISSUE THREAD

**Issue by JonathanHayward** [showdownjs/showdown#245]
In my source, I have a slightly old version of Showdown:

    <script src="//cdnjs.cloudflare.com/ajax/libs/showdown/1.0.2/showdown.js"></script>

In my code I attempt to call:

                var preprocess = function(raw)
                    {
                    if (!raw)
                        {
                        return '';
                        }
                    var workbench = '';
                    for(var index = 0; index < raw.length; index += 1)
                        {
                        workbench += raw[index];
                        }
                    workbench = workbench.replace(/&/g, '&amp;');
                    workbench = workbench.replace(/"/g, '&quot;');
                    workbench = workbench.replace(/'/g, '&apos;');
                    workbench = workbench.replace(/\\\\/g, '\\\\\\\\');
                    workbench = workbench.replace(/</g, '&lt;');
                    workbench = workbench.replace(/>/g, '&gt;');
                    return converter.makeHTML(workbench);
                    };

I get an error in the log saying, "converter.makeHTML is not a function".

What should I be doing to convert Markdown to HTML using Showdown?

Thanks,

**Comment by tivie** [comment]
## Short version

You miss typed the function's name. It's `converter.makeHtml`


## A bit longer version

You're using an outdated version of showdown. You should be using the latest:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/showdown/1.3.0/showdown.js"></script>
```

Secondly, you don't really need to encode html entities, since showdown does that for you.

Check a [working fiddle here](https://jsfiddle.net/tivie/na3yfg2g/)
