### ISSUE TITLE
makeHtml table Converted into <p></p>

### ISSUE THREAD

**Issue by khahux** [showdownjs/showdown#250]
$scope.markdownText
`| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| **col 3 is**  | right-aligned | $1600 |
| col 2 is      | *centered*    |   $12 |
| zebra stripes | ~~are neat~~  |    $1 |
| zebra stripes | ~~are neat~~  |    $1 |
| zebra stripes | ~~are neat~~  |    $1 |`

$converter.makeHtml($scope.markdownText);
`<p>| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| <strong>col 3 is</strong>  | right-aligned | $1600 |
| col 2 is      | <em>centered</em>    |   $12 |
| zebra stripes | ~~are neat~~  |    $1 |
| zebra stripes | ~~are neat~~  |    $1 |
| zebra stripes | ~~are neat~~  |    $1 |</p>`

[screenshots](http://v2.freep.cn/3tb_1604201836288e7c512293.png)

**Comment by tivie** [comment]
Hi

Did you activate table support in the options, [as stated in the documentation?](https://github.com/showdownjs/showdown/blob/master/README.md#valid-options)

**Comment by tivie** [comment]
Closing as no update for 8 days
