### ISSUE TITLE
Extend showdown to allow embedding selected scripts

### ISSUE THREAD

**Issue by ishankhare07** [showdownjs/showdown#252]
> This is more a question than a bug/feature request, I understand not many will be in favor of allowing `<script>` tags in the markdown

I need to enable this for my own blog project, particularly for embedding code samples from

1. gist.github.com
2. repl.it

Both of the above support only `scripts` for the embedding feature, I would like to know how I must extend the current codebase to allow embedding scripts, which i can then limit to only the above mentioned domain named (probably using regexes etc.)

**Comment by tivie** [comment]
Showdown allows for any html tag to be embedded. This includes `<script>` tags. [see demo][1]

In order to limit the scripts to specific domains, (or any kind of other filter), you need to create an output extension that checks for script tags.

[1]: http://showdownjs.github.io/demo/#/bla%0A%0A%3Cscript%3E%0Aalert('foo');%0A%3C/script%3E%0A%0Abar

**Comment by ishankhare07** [comment]
@tivie the demo is an inline script, whereas the services which I mentioned use external scripts like in case of gist.github.com: 
```html
<script src="https://gist.github.com/ishankhare07/fb586cf159e5c4d18c2d.js"></script>
```

I tried this with the demo -> [here](http://showdownjs.github.io/demo/#/%23%20A%20github%20gist%0A%0A%3Cscript%20src%3D%22https%3A%2F%2Fgist.github.com%2Fishankhare07%2Ffb586cf159e5c4d18c2d.js%22%3E%3C%2Fscript%3E%0A%0Anot%20visible)

**Comment by tivie** [comment]
Ah, but that is not showdown's fault but rather the browser's.

[innerHTML does not allow execution at runtime of inserted scripts][1]. That is to mitigate XSS attacks.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#Security_considerations

**Comment by tivie** [comment]
If you wish the script to be embeded and ran, showdown's output but be reloeaded as part of the DOM, at page loading. This will probably require a trip to the server

**Comment by tivie** [comment]
@ishankhare07 Closing as there is no update.

Check http://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml
