### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by fkorak** [showdownjs/showdown#253]
Hi,

would there be any possibility of getting an official current NuGet-Package? There is one already existing, but it's on version 0.9 and was last updated 2012-10-01. I ask because I'm currently going through the tutorial for ReactJS.NET and one of the steps is installing showdown. Alternatively how does this project feel about unofficial packages submitted by volunteers?

Thank you very much for your time.

**Comment by tivie** [comment]
hi @fkorak 
I don't have anything against having unofficial (or semi-official) showdown nuget packages. In fact, I think it might be the best option.

Are you voluntering? =P

**Comment by tivie** [comment]
Bump

**Comment by fkorak** [comment]
I finally got around to doing one. You can find it at [showdownjs nuget](https://www.nuget.org/packages/showdownjs/1.4.2), after NuGet indexing is done. I'll try keeping it updated in a timely manner (having set it up once, I'll probably just need to replace the js-files), I have a mail notification on the Changelog.md. Have a look on whether the copyright information is filled out correctly.

I ran the ReactJS.Net-Tutorial to test the package out, runs fine (for anyone doing the same: change the showdown-object to lowercase and the Converter-Call to uppercase)

**Comment by tivie** [comment]
@fkorak Thank you very much. 

I will add a referecence to the NuGet package in the wiki and readme.md so people know about it.
