### ISSUE TITLE
parsing markdown inside of an extension

### ISSUE THREAD

**Issue by ciel** [showdownjs/showdown#255]
I've written a very barebones extension for `showdownjs` like this;

````
    showdown.extension('notice', () => {
        return {
            type: 'lang',
            regex: /([^\s]* > )(.*)/g,
            replace: `<div class="notice notice-$1">$2</div>`
        };
    });
````
And it works beautifully - but the text that gets put between the two `<div>` layers is not parsed. It comes out verbatim as it is typed. Is there a way to render it?

If I register it as an `output` and provide a function ,it gets parsed;
````
    showdown.extension('notice', () => {
        return {
            type: 'output',
            regex: /([^\s]* > )(.*)/g,
            filter: (text: string,
                     converter: Showdown.Converter,
                     options: Showdown.ConverterOptions) => {
                return text.replace(/([^\s]* > )(.*)/g,
                    `<div class="notice notice-$1">$2</div>`);
            }
        };
    });
```
but this seems to run against every text, which strikes me as resource wasteful.

I can put a function in the `lang` extension and parse it by manually creating a converter, but then it wraps everything in a `<p></p>` tag.

**Comment by tivie** [comment]
Since showdown version 1.4.0, to enable parsing inside an html block, you can use the attribute markdown (or data-markdown).

```
replace: '<div markdown="1" class="notice notice-$1">$2</div>'
```

**Comment by ciel** [comment]
This __does__ work, but the output gets wrapped in `<p></p>`. Is there any way around that? It throws off the formatting considerably.

```
Showdown.extension('notice', () => {
            return {
                type: 'lang',
                regex: /^(^\S+)\s+(>)\s+(.*)/gmi,
                replace: (text: string, css: string, method: string, message: string) => {
                    return text.replace(/^(^\S+)\s+(>)\s+(.*)/gmi,
                             `<div markdown class="notice notice-${css}" >$3</div>`);
                }
            };
        });
```

**Comment by ciel** [comment]
Really loving showdown, by the way. It's beautifully designed, and so much easier than `marked` to use.

**Comment by tivie** [comment]
@ciel Thanks!

You mean, the text inside the div gets wrapped inside a paragraph right? Something like this:

```html
<div markdown class="notice">
<p>some long text</p>
</div>
```

**Comment by ciel** [comment]
Yes, that is correct. It would be ideal if I could get it to render without wrapping it in the paragraph tags.

**Comment by tivie** [comment]
That is a pickle indeed. Since the default markdown behavior is to treat blocks of text as paragraphs, that can't easily be changed.
However, I can think of two ways around it:

- Leave the `<p>` tags and format them with css. Example:

   ```css
   .notice p {
      line-height: normal;
      margin-bottom: 0;
   }
```

- Use an output extension to remove the `<p>` tags inside `<div class="notice">`

```js
showdown.extension('myext', [{
  type: 'output',
  filter: function(text) {
    var replacement = function (wholeMatch, inner, left, right) {
      return left + inner.replace(/^\s*<p>/, '').replace(/<\/p>\s*$/, '') + right;
    };
    return showdown.helper.replaceRecursiveRegExp(text, replacement, '<div markdown class="notice.*">', "</div>", "gi");
  }
}]);
```

The first approach only "styles" the issue. However, it is semantically correct to have p tags inside divs. And it's a lot simpler and faster.

The second approach removes the p tags altogether but is a bit slower. However, it's a lot faster than the output extension you proposed, since it only parses the appropriate divs.

**Comment by ciel** [comment]
Thanks. Both of these seem reasonable. I’ll likely go with the first one, and just style them inside the corresponding output.
