### ISSUE TITLE
Table rendering no longer working with 1.4.x

### ISSUE THREAD

**Issue by shaddockh** [showdownjs/showdown#256]
Table rendering is no longer working with the latest version.  With the test code:

```javascript
var showdown  = require('showdown'),
    converter = new showdown.Converter({tables: 'true'}),
    text      = ['|key|value|',
                 '|--|--|',
                 '|My Key|My Value|'].join('\n');
    html      = converter.makeHtml(text);

console.log(html);
```

The latest version ```showdown@^1.4.0``` generates:
```
<p>|key|value|
|---|---|
|My Key|My Value|</p>
```

The prior version```showdown@~1.3.0``` generates it correctly as:
```
   <table>
   <thead>
   <tr>
   <th>key</th>
   <th>value</th>
   </tr>
   </thead>

   <tbody>
   <tr>
   <td>My Key</td>
   <td>My Value</td>
   </tr>

   </tbody>
   </table>
```

**Comment by tivie** [comment]
It seems the new tables regexes make table header separators require 3 dashes instead of 2.

This should work properly:

```md
|key|value|
|---|---| 
|My Key|My Value|
```

This behavior was not intended, and I will release a fix as soon as possible.

**Comment by tivie** [comment]
Issue should be fixed now

**Comment by tivie** [comment]
New release for this fix https://github.com/showdownjs/showdown/releases/tag/1.4.1

**Comment by shaddockh** [comment]
Confirmed.  Thanks!

**Comment by tschmit** [comment]
with the following text, the table is not rendered within the fiddle :

| fsf | sdfsdf |
|---|---|
| == | rechercher les dossiers dont les sous-types **sont** inclus dans ceux sélectionnés.|
| != | rechercher les dossiers dont les sous-types **ne sont pas** inclus dans ceux sélectionnés.|
