### ISSUE TITLE
import showdown is not supported like require(showdown)

### ISSUE THREAD

**Issue by ayyash** [showdownjs/showdown#258]
I am using meteor, I added showdown from npm, then added this line at the top:
`import {showdown} from 'showdown';`

Now that brings back "undefined" value for `showdown`, but when I tried

`var showdown  = require('showdown'); `

It worked. Am I missing anything or is showdown not quite an exported module?

**Comment by wifiextender** [comment]
> Rename the showdown package to markdown.

https://github.com/meteor/meteor/blob/devel/History.md#api-changes

https://github.com/meteor/meteor/blob/devel/packages/showdown/package.js

**Comment by tivie** [comment]
The issue is with meteor and not showdown.
Meteor uses it's own fork of showdown, based on an old deprecated version of our library.
