### ISSUE TITLE
issues with es6 template strings

### ISSUE THREAD

**Issue by jhicken** [showdownjs/showdown#259]
Imagine a function like this...

```
function masterRunner(){
  var conv = new showdown.Converter()
  return conv.makeHtml(`
    ## markdown doc
    you can use markdown for card documentation
    - foo
    - bar
  `)
}
```

this is the output
```
<pre><code>## markdown doc
you can use markdown for card documentation
- foo
- bar
</code></pre>
```

It means i always have to untab my markdown.

I understand why but it seams ungood.

**Comment by tivie** [comment]
I see your point. However, I can't think of any sane way showdown core can ignore tabs smartly without breaking the tab code blocks.

Do you have any suggestions?

An extension, for your specific case, might do the trick.

Or even some kind of pre parser function

**Comment by tivie** [comment]
To fix your specific issue, however, you have several options:

### Move es6 template strings to a new line

You can fix the issue by moving the es6 opening mark to a new line that respects your indentation:

```js
function masterRunner() {
  var conv = new showdown.Converter()
  return conv.makeHtml(
    `## markdown doc
     you can use markdown for card documentation
      - foo
      - bar`);
}
```

### Use a wrapper function

you can also use a wrapper function, although I think is really an overkill and potentially breaks tab code blocks:

```js
function masterRunner(){
  var conv = new showdown.Converter()
  return conv.makeHtml(t(`
    ## markdown doc
    you can use markdown for card documentation
    - foo
    - bar
  `));
}

function t(txt) {
  return txt.replace(/^\s+/gm, '');
}
```


### Make the above t function a lang extension

This would remove the need to pre-parse the text but, again, I think is an overkill.

**Comment by jhicken** [comment]
Hey thanks for the response.

So If i use option 1 (Move es6 template strings to a new line)

This is what i get. The first line is converted and nothing else.

```
<h2 id="markdowndoc">markdown doc</h2>

<pre><code>  you can use markdown for card documentation
  - foo
  - bar
</code></pre>
```

the alternative is
```
function masterRunner() {
  var conv = new showdown.Converter()
  return conv.makeHtml(`
## markdown doc
you can use markdown for card documentation
- foo
- bar
  `);
}
```
Which is also not super great. (this is what im currently doing)

Using something like option 2 up above would work but would need some major testing to make sure you don't remove white space from unintended lines.

My proposal is that showdown could let you pass an argument that would try to intelligently fix your es6 string.

Is that crazy?

**Comment by tivie** [comment]
> My proposal is that showdown could let you pass an argument that would try to intelligently fix your es6 string.

Yeah, but how would we accomplish that? Right trimming would not work as it would remove important right whitespaces. 
Passing the indentation level would be kind of useless since it would tighly couple the text with the code style, which is crazy!!

The only way I can think of is guessing by the the "indentation" level of the first line of the text, but that would also break under some circumstances such as:

 - first line of text not indented but the rest is
 - a list or a code block as first element in a string
 - etc...

**Comment by tivie** [comment]
Check 261f127 and see if it fixes your problem,

Its on it's own branch since I would like further testing before introducing this feature on core.
This type of "smart" indentation fixing is problematic and I don't think we can create a system that reliably can identify indented text.

**Comment by tivie** [comment]
@jhicken  Have you had time to check and test 261f127 ?

**Comment by jhicken** [comment]
I have not.  Sorry been super busy.  I'll try and get to it tonight.  Ps thanks for working on this.
