### ISSUE TITLE
How to save/get metadata?

### ISSUE THREAD

**Issue by IonicaBizau** [showdownjs/showdown#260]
I'm looking how to save/read metadata like below:

``` md

---
Title:   My awesome markdown file
Author:  Me
Scripts:
    - js/doStuff.js
    - js/doMoreStuff.js
...

##Header
Regular text and stuff goes here.
```

**Comment by timaschew** [comment]
This is not part of a markdown parser usually.
You need a parse step before you run your markdown parser.
Here is module to fetch these data and split them into properties and the markdown body

https://github.com/jxson/front-matter

**Comment by tivie** [comment]
the bit at the top is YAML so you need a yaml parser

**Comment by IonicaBizau** [comment]
@timaschew @tivie Thanks! I built [`mdify`](https://github.com/IonicaBizau/mdify) which uses `js-yaml` to parse the YAML stuff and `showdown` to htmlify the markdown code. 😁

**Comment by tivie** [comment]
I've decided that a simple metadata parser would be useful in markdown documents.

The syntax is:

 1. `---` or `«««` at the beginning of the markdown document
 2. optionally followed by a alphanumeric
 2. followed by key value pairs separated by a colon and a space `: `
 3. Closed by `---` or `»»»`

like this:

```md
---
title: document title
some meta name: some meta content
---

# my markdown document

rest of the document
```

or

```md
«««
title: document title
some meta name: some meta content
»»»

# my markdown document

rest of the document
```

or even this:

```md
---YAML
title: document title
some meta name:
 - a list
 - of values
---

# my markdown document

rest of the document
```


To enable metadata parsing, one must enable the option `metadata`.

```js
var conv = new showdown.Converter({metadata: true});
```

Showdown will expose a method for retrieving the document's metadata after parsing:

```js
var conv = new showdown.Converter({metadata: true});
var html = conv.makeHtml(someMd);
var metadata = conv.getMetadata(); // returns an object with the document metadata
```

Note that showdown won't support YAML (or any other data format) out of the box, but you can retrieve the raw metadata and parse it yourself.

```js
var conv = new showdown.Converter({metadata: true});
var html = conv.makeHtml(someMd);
var metadata = conv.getMetadata(true); // returns a string with the raw metadata
var metadataFormat = conv.getMetadataFormat(); // returns the format of the metadata

// do stuff with the metadata var
```

**Comment by tivie** [comment]
This feature should be implemented now

> ## Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at pledgie.com](https://pledgie.com/campaigns/35166.png?skin_name=chrome)](https://pledgie.com/campaigns/35166)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/35166) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by bradburydoom** [comment]
Does the demo not have this implemented?

http://demo.showdownjs.com/
