### ISSUE TITLE
Reference style image after inline style image doesn't work correctely

### ISSUE THREAD

**Issue by ye-will** [showdownjs/showdown#261]
failed:

    ![sd-inline](https://raw.githubusercontent.com/showdownjs/logo/master/dist/logo.readme.png) ![sd-ref][sd-logo]

ok:

    ![sd-ref][sd-logo] ![sd-inline](https://raw.githubusercontent.com/showdownjs/logo/master/dist/logo.readme.png)

**Comment by tivie** [comment]
@ye-will should be fixed now in 73206b0, develop branch

**Comment by ye-will** [comment]
@tivie nice work.
