### ISSUE TITLE
Is it possible to get jsonML out of this?

### ISSUE THREAD

**Issue by jahtalab** [showdownjs/showdown#263]

**Comment by tivie** [comment]
@jahtalab more information needed please

**Comment by jahtalab** [comment]
@tivie , I need to parse the markdown to some sort of tree to extract extra information about it.
[markdown-js](https://github.com/evilstreak/markdown-js) does this by parsing into jsonML.

**Comment by tivie** [comment]
@jahtalab Can you give a concrete example?

**Comment by jahtalab** [comment]
@tivie ,
For example I want to extract meta data about the markdown, something like this

```
Title:  A New MultiMarkdown Document  
Author: Fletcher T. Penney  
        John Doe  
Date:   July 25, 2005  
```

This meta data shouldn't be rendered (or it might) but I want to have the info when I parse the markdown, for instance to find all articles after some date.

**Comment by tivie** [comment]
I think your issue is related to this one https://github.com/showdownjs/showdown/issues/260
