### ISSUE TITLE
Line breaks between list not keeping

### ISSUE THREAD

**Issue by rabeesh** [showdownjs/showdown#265]
The line space between two list not rendering as a two list.
```
var markdown = '*   one\n*   two\n*   three\n*   four  \n\n \n\n' +
'*   another1\n*   another2\n*   another3\n'
```

Expected result , see this in http://dillinger.io/
```
<ul>
    <li>dfadsadddd</li>
    <li>assdfasdas</li>
    <li>sdfsdfs</li>
    <li>dfsdf</li>
</ul>
<ul>
    <li>dfadsadddd</li>
    <li>assdfasdas</li>
    <li>sdfsdfs</li>
    <li>dfsdf</li>
</ul>
```

But showdown giving me one single list, and li with contains < p > tag.

**Comment by tivie** [comment]
This is one of the (not so) edge cases in which the original markdown spec is omissive. This means each implementation out there parses this specific case differently differently. [see comparison here ][1]

While showdown follows the original markdown spec as much as possible, dillinger seems to follow the Common mark spec (which is not markdown, but rather a variant!!!).

Regardless, internally we've debated this extensively, and couldn't come to an agreement. However, I think it's possible to add an option to treat consecutive lists separated by 3 or 4 linebreaks as separated lists.

Right now, you can work around this by adding a silent element in between the lists


```md
 - a
 - b
 - c

<!-- -->

 - bla
 - bli
 - blu
```


[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+++one%0A*+++two%0A*+++three%0A*+++four%0A%0A%0A*+++another1%0A*+++another2%0A*+++another3

**Comment by tivie** [comment]
For instance, github does not separate lists like that:

```
1. a
1. b
1. c





1. d
```

1. a
1. b
1. c





1. d
