### ISSUE TITLE
Autolinking - URL surrounded by parentheses

### ISSUE THREAD

**Issue by joemunriq** [showdownjs/showdown#266]
Input:
`(https://www.something.com/1234)`

Results in:
`(<a href="https://www.something.com/1234)">https://www.something.com/1234)</a>`

Note that the trailing paren is included in the target URL.

**Comment by wifiextender** [comment]
@joemunriq 

>(https://www.something.com/1234)

Input: 

```html
https://www.something.com/1234
```

Once parsed it becomes:

```html
<a href="https://www.something.com/1234">https://www.something.com/1234</a>
```

---

Input:

```markdown
[link]

[link]: https://www.something.com/1234
```

Once parsed it becomes:

```html
<a href="https://www.something.com/1234">link</a>
```

**Comment by wifiextender** [comment]
Input:

```markdown
[link](https://www.something.com/1234)
```

Once parsed it becomes:

```html
<a href="https://www.something.com/1234">link</a>
```

---

Input:

```html
( https://www.something.com/1234 )
```

Once parsed it becomes:

```html
( <a href="https://www.something.com/1234">https://www.something.com/1234</a> )
```

**Comment by joemunriq** [comment]
@wifiextender  Thank you for the info... but I'm calling out one specific buggy behavior using Showdown's GFM auto-linking feature, which automatically creates a link when it identifies a URL (without using Markdown's link syntax).  If the URL is contained within parens (without spaces), it will include the closing paren as part of the anchor's HREF.

**Comment by joemunriq** [comment]
It looks like GitHub and RedCarpet (the MD parser that GitHub uses) handles this case specifically.  It looks for enclosing parens:

https://github.com/vmg/redcarpet/blob/00d4e02a2cc3ada39c2547529b29fb2f871a83fb/ext/redcarpet/autolink.c

(Example: https://github.com/vmg/redcarpet/blob/00d4e02a2cc3ada39c2547529b29fb2f871a83fb/ext/redcarpet/autolink.c#L115)

Can we get these same rules applied to Showdown?

Thanks!

**Comment by tivie** [comment]
This is a tricky situation because parenthesis are allowed in urls and there can be situations where the rules used by RedCarpet will wrongly exclude the parentehsis from the url.

For instance:

The url is `http://www.example.com/a/link/that/ends/parenthesis)`

So this:

```md
(http://www.example.com/a/link/that/ends/parenthesis) is a link with parentehsis)
```

gets converted into this:

(http://www.example.com/a/link/that/ends/parenthesis) is a link with parentehsis)

```html
<p>(<a href="http://www.example.com/a/link/that/ends/parenthesis">http://www.example.com/a/link/that/ends/parenthesis</a>) is a link with parentehsis)</p>
```

which is wrong.

Sure, this is a really edge case, and it's highly unlikely that an URL with end in a single unpaired parenthesis but...

**Comment by tivie** [comment]
on the other hand, it's really easy to workaround this issue:

```md
(<https://www.something.com/1234>)
```

**Comment by tivie** [comment]
Regardless, since we have a "GitHub flavored markdown", I will create an option that implements the rules of github, regarding parentehsis.

This option will be disabled by default, and you would need to explicitely enable it.

**Comment by tivie** [comment]
This was added as a new option called `excludeTrailingPunctuationFromURLs`. Enabling this option will remove trailing punctuation and parenthesis from URL parsing in auto linking.
