### ISSUE TITLE
[solved] electron load support/issue 

### ISSUE THREAD

**Issue by aaroncalderon** [showdownjs/showdown#269]
When using [electron](http://electron.atom.io/) with showdown, showdown is loaded with the [`CommonJS/nodeJS loader`](https://github.com/showdownjs/showdown/blob/master/src/loader.js#L3-L5), but I expect it to be loaded with [`Regular Browser loader`](https://github.com/showdownjs/showdown/blob/master/src/loader.js#L14-L17), so I can then use the [`angular-markdown-filter`](https://github.com/vpegado/angular-markdown-filter) without modification.

I was able to make `angular-markdown-filter` work by changing [`markdown.js#L10-L11`](https://github.com/vpegado/angular-markdown-filter/blob/master/markdown.js#L10-L11) to the below lines: 

``` javascript
// I have installed showdown with bower to a custom directory `lib`
global.showdown = require('../lib/showdown/dist/showdown'); 
return new window.showdown.Converter(opts);
```

But, it feels like a hackish solution.

Any suggestions to address this issue? ~~Should I file a bug with electron?~~ I [filed a bug with electron](https://github.com/electron/electron/issues/6204) and created an electron app that [reproduces the issue](https://github.com/aaroncalderon/ea-todo/tree/electron-uml-issue).

**Comment by tivie** [comment]
I will keep an eye on both issues

**Comment by aaroncalderon** [comment]
Turns out that if I run create a window  with the `nodeIntegration: false` option, behaviour is as expected. However, I rely on the integration with node for other features, so I'm looking for any suggestions to overcome the issue.

**Comment by aaroncalderon** [comment]
# Solution

I was able to use [`preload: 'absolute/path/to/preload.js'`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) (search for 'preload') with [`event-loaded`](https://github.com/electron/electron/blob/master/docs/api/process.md#event-loaded) to solve the issue.

**Comment by gbaumgart** [comment]
same here, can please check that its electron ?
  
```
var _window = typeof window !== 'undefined' ? window : null;
  var isElectron = _window && _window.process && _window.process.type === "renderer";
// CommonJS/nodeJS Loader
  if (typeof module !== 'undefined' && module.exports && !isElectron) {

```

**Comment by gbaumgart** [comment]
electron support added in [PR](https://github.com/showdownjs/showdown/pull/303)

**Comment by aaroncalderon** [comment]
The behaviour I experienced was by design. 

I'm not sure if specific support for __electron__ is needed. 

However, that little piece of code is a clever approach. However, to make a difference every javascript library that uses UML (Universal Module Loading) will need to adopt this approach.

**Comment by tivie** [comment]
I've never used Electron so i'm far from being an expert but:

Wouldn't forcing showdown to load "browser style" in Electron context create problems for other modules (like nodejs modules) that expect showdown to load via CommonJS?

**Comment by aaroncalderon** [comment]
__short answer__

@tivie I think it would.

__other thoughts__

With the current implementation when loading __showdownjs__ on a nodejs environment, it will behave as expected and the `require` command will work just fine.

When using electron, on the other hand, on the renderer process (the chromium part of it) has nodejs integration enabled by default, making the renderer process behave like a nodejs environment.

In my case, I was developing an app that behaves more like a web app, and thus the nodejs integration was trowing off my asuptions about how to load _all_ my libraries. 

So, in my case, using the the [`nodeIntegration: false`] (https://github.com/aaroncalderon/ea-todo/blob/electron-uml-issue-node-int-off/app/main.js#L86) parameter when creating the renderer process solved my issue. Ofcourse, I had to rewrite some bits of the application to provide the functionality I needed from nodejs to my renderer process through the [preload](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) parameter.

**Comment by gbaumgart** [comment]
i am afraid pre-load won't lazy loaded components. and supporting as next a mixed env. like electron isn't too unusual. i did this patch in a few libs already. its 1-2 lines only and will do its job til fine, til they fixed the concepts of js loaders i guess.

anyway, i am ok with my fork; i saw some other things to be changed too, so its fine with me to close this here. 
thanks btw. for your work, it helps me a lot to build perfectly integrated and interactive documentation!

**Comment by tivie** [comment]
@gbaumgart I've just tested showdown with your PR under Electron. With another library, **IonicaBizau/github-portfolio**, it fails since showdown is no longer loaded via "require".

Like I said, I'm no Electron wizard so I might be doing something wrong.

@gbaumgart Would you mind testing this also? with this 2 libraries?

**Comment by gbaumgart** [comment]
@tivie I see, I guess that library want's to load showdown via electron's require. In my case i want it loaded on the client side. So to make this right, we need something to tell showdown how to export it self. I don't know better than doing this with some variable in global/window. You have a better idea ? 

g

**Comment by tivie** [comment]
Not really no. But alas, poluting the global namespace with variables does not seem a good solution too.
This really has to be addressed from Electron side. I don't see another way.
