### ISSUE TITLE
Support for lists (or html) in table cells

### ISSUE THREAD

**Issue by coiouhkc** [showdownjs/showdown#272]
Could you please add support for following syntax:
```
| | |
|---|---|
| Cell1| <ul><li>item 1</li><li>item 2</li></ul>|
```
?
Doesn't seem to work in  [1.4.1]("https://cdnjs.cloudflare.com/ajax/libs/showdown/1.4.1/showdown.min.js)

**Comment by coiouhkc** [comment]
Somehow it works on the demo page (http://showdownjs.github.io/demo/) but not when using following snippet
```
converter.setOption('tables', true);
var html = converter.makeHtml(md);
```

**Comment by tivie** [comment]
I couldn't reproduce the issue you refer to. Both in demo and in this fiddle is working properly.

 - [demo][demo]
 - [fiddle][fiddle]


[demo]: http://showdownjs.github.io/demo/#/%7C%20%7C%20%7C%0A%7C---%7C---%7C%0A%7C%20Cell1%7C%20%3Cul%3E%3Cli%3Eitem%201%3C%2Fli%3E%3Cli%3Eitem%202%3C%2Fli%3E%3C%2Ful%3E%7C
[fiddle]: https://jsfiddle.net/3q1z52ns/
