### ISSUE TITLE
Support from HTML+Markdown to HTML

### ISSUE THREAD

**Issue by xserrat** [showdownjs/showdown#273]
Hi,

First of all, congratulations for this library, very useful. I have a question about support conversions from HTML mixed with Markdown to HTML.

If support exists, I found an issue when I try to put some words with bold, italian or header styles. But these words aren't converted to the corresponding tags in HTML when these words are between `<p></p>` tags.

I show you an example using your demo page:

![Possible issue](https://cloud.githubusercontent.com/assets/5933658/16417575/ba6b2206-3d46-11e6-83cc-201030546af7.png)

Thanks!!

**Comment by tivie** [comment]
You need to add the property markdown to the tag In order to allow markdown parsing inside a specific html tag.

    <p markdown="1">this is **bold**</p>

**Comment by xserrat** [comment]
Thank you very much @tivie ! I close this issue 👍
