### ISSUE TITLE
showdown freezes for specific input

### ISSUE THREAD

**Issue by libHive** [showdownjs/showdown#276]
Hey

I got this when trying to parse this markdown -
```
<!-- This extra line is necessary for table to render properly. -->
|                                                                          |      DNSChain      | X.509 PKI with [Certificate Transparency][ct] |
|--------------------------------------------------------------------------|--------------------|-----------------------------------------------|
| __MITM-proof'ed [Internet connections][mitm]__                           | :white_check_mark: | :x:                                           |
| __Secure and simple [GPG key distribution][gpg]__                        | :white_check_mark: | :x:                                           |
| __MITM-proof RESTful [API to blockchain][api]__                          | :white_check_mark: | :x:                                           |
| __Free and [actually-secure][free] SSL certificates__                    | :white_check_mark: | :x:                                           |
| __Stops many [denial-of-service attacks][dos]__                          | :white_check_mark: | :x:                                           |
| __Certificate revocation [that actually works][rev]__                    | :white_check_mark: | :x:                                           |
| __DNS-based [censorship circumvention][cens]__                           | :white_check_mark: | :x:                                           |
| __Prevents [domain theft][theft] ("seizures")__                          | :white_check_mark: | :x:                                           |
| __Access blockchain [domains like `.bit`, `.p2p`, `.nxt`, `.eth`][use]__ | :white_check_mark: | :x:                                           |
| __Certificate transparency (publicly auditable log of certs)__           | :white_check_mark: | :white_check_mark: ([maybe][ct])              |
```
(it's taken from https://github.com/okTurtles/dnschain/blob/master/README.md)

I'm not sure of there are any markdown errors here but showdown totally freezes and locks up the thread. Using this in nodejs means my process is effectively stuck and in the showdown demo page (browser) the thread/tab is also frozen.

**Comment by tivie** [comment]
it also freezes in the demo.

**Comment by tivie** [comment]
I will look into it as soon as possible

**Comment by tivie** [comment]
Ok, after further inspection, it seems the problem lied with a regex lookahead that was taking too long to complete. The regex was modified and simplified and the issue seems fixed now.

**Comment by tivie** [comment]
Issue is fixed, check [this link][demo]


[demo]: http://showdownjs.github.io/demo/#/%3C!--%20This%20extra%20line%20is%20necessary%20for%20table%20to%20render%20properly.%20--%3E%0A%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20DNSChain%20%20%20%20%20%20%7C%20X.509%20PKI%20with%20%5BCertificate%20Transparency%5D%5Bct%5D%20%7C%0A%7C--------------------------------------------------------------------------%7C--------------------%7C-----------------------------------------------%7C%0A%7C%20__MITM-proof'ed%20%5BInternet%20connections%5D%5Bmitm%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Secure%20and%20simple%20%5BGPG%20key%20distribution%5D%5Bgpg%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__MITM-proof%20RESTful%20%5BAPI%20to%20blockchain%5D%5Bapi%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Free%20and%20%5Bactually-secure%5D%5Bfree%5D%20SSL%20certificates__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Stops%20many%20%5Bdenial-of-service%20attacks%5D%5Bdos%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Certificate%20revocation%20%5Bthat%20actually%20works%5D%5Brev%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__DNS-based%20%5Bcensorship%20circumvention%5D%5Bcens%5D__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Prevents%20%5Bdomain%20theft%5D%5Btheft%5D%20(%22seizures%22)__%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Access%20blockchain%20%5Bdomains%20like%20%60.bit%60%2C%20%60.p2p%60%2C%20%60.nxt%60%2C%20%60.eth%60%5D%5Buse%5D__%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20__Certificate%20transparency%20(publicly%20auditable%20log%20of%20certs)__%20%20%20%20%20%20%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%20%3Awhite_check_mark%3A%20(%5Bmaybe%5D%5Bct%5D)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C

**Comment by avnersorek** [comment]
Thanks !
