### ISSUE TITLE
Editor ignores urls that start with double slash

### ISSUE THREAD

**Issue by mazeappleton** [showdownjs/showdown#278]
When you start image urls with double slash, editor ignores those urls and a preview image does not appear.

```md
![img](//placekitten.com/300/200)
```

**Comment by tivie** [comment]
@mazeappleton What do you mean by editor?

I couldn't reproduce your problem [in our editor](http://showdownjs.github.io/demo/#/!%5Bimg%5D(%2F%2Fplacekitten.com%2F300%2F200))

**Comment by mazeappleton** [comment]
I'm using the editor ghost

**Comment by tivie** [comment]
It must be a problem with ghost then. Try to ask in their issue tracker.

**Comment by tivie** [comment]
https://github.com/TryGhost/Ghost/issues/5625
