### ISSUE TITLE
Option to join lines in a paragraph

### ISSUE THREAD

**Issue by nicolaiparlog** [showdownjs/showdown#281]
We are using Showdown to transform Markdown to HTML, which is then used in WordPress. Unfortunately WordPress has the "feature" to automatically insert `<br>` after the end of a line (if another line follows).

This:

    Hi
    there

becomes:

    <p>Hi<br>
    there</p>

A `joinParagraphLines` flag would really help us out. Showdown would first apply its usual transformation and then (if the flag is activated) look for all “hard-wrapped” text paragraphs and put them together.

If this features is approved and I am given some help, I could take a shot at it.

**Comment by tivie** [comment]
So if I understand you correctly, wordpress converts:

```html
<p>hi
there</p>
```

into

```html
<p>hi<br/>
there</p>
```

**Comment by nicolaiparlog** [comment]
Yes, exactly.

My idea was to remove all line breaks that match this criteria:

* not preceded by a tag
* not followed by another line break

I'm currently trying (and failing as it looks like) to find a regex to express those conditions.

**Comment by tivie** [comment]
Well, it's actually easy to fix the issue, without requiring any modification to showdown's source code.

Simply run a beautifier in showdown's output, for instance: https://github.com/beautify-web/js-beautify

Here's a [working fiddle example](https://jsfiddle.net/tivie/0wpqveyj/)

**Comment by nicolaiparlog** [comment]
Thank you very much, that is indeed a good solution. :)
