### ISSUE TITLE
 showdown.subParser['codeSpans'] 's param -> text  is undefined

### ISSUE THREAD

**Issue by jianhaozh** [showdownjs/showdown#287]
In some occasion, maybe my markdown file has some unkown issue, for some reason, not to shown here, the function  showdown.subParser['codeSpans'] 's param -> text may have an undefined value passed into, I am still debugging.......

**Comment by jianhaozh** [comment]
now , i am add the blow codes in the start of this function to avoid this issue happens again, here is the code:
text = text || "";

**Comment by tivie** [comment]
Can you post an example with the issue? So we can verify and test this?

**Comment by tivie** [comment]
Closing as no update in 30 days
