### ISSUE TITLE
Code blocks containing xml comments are not converted correctly when nested in list items

### ISSUE THREAD

**Issue by reversemerman** [showdownjs/showdown#288]
Removing the commented out sections of the XML fixes the issue. These are rendered correctly on GitHub.

**Comment by tivie** [comment]
Can you create a snippet showing the bug?

**Comment by reversemerman** [comment]
OS: Ubuntu 16.04 LTS

`showdown makehtml -i input.txt -o output.txt --tables --ghCodeBlocks`

[input.txt](https://github.com/showdownjs/showdown/files/443654/input.txt)
[output.txt](https://github.com/showdownjs/showdown/files/443655/output.txt)

**Comment by tivie** [comment]
Confirmed in the [online demo](http://showdownjs.github.io/demo/#/*%20list%20item%201%0A%0A%20%20%20%60%60%60%0A%20%20%20%3Cparent%3E%0A%20%20%20%3Cchild%3Echild1%3C%2Fchild%3E%0A%20%20%20%3C!--%20This%20is%20a%20comment%20--%3E%0A%20%20%20%3Cchild%3Echild2%3C%2Fchild%3E%0A%20%20%20%3C%2Fparent%3E%0A%20%20%20%60%60%60%0A%0A*%20list%20item%202).

I will look into this as soon as possible

**Comment by tivie** [comment]
This should be fixed now.

**Comment by siriscac** [comment]
I'm facing this issue again.
Using the npm module. I looked at the code for [799abea](https://github.com/showdownjs/showdown/commit/799abea7674ae5a778f778b5418acc599ee7012e) changes, and it doesn't seem to have them.

**Comment by tivie** [comment]
@siriscac, this update was not released into stable yet.

The next showdown update should include it

**Comment by tivie** [comment]
Released v 1.4.4 that includes this fix

https://github.com/showdownjs/showdown/releases/tag/1.4.4

**Comment by siriscac** [comment]
Can confirm that it works, thanks.
