### ISSUE TITLE
The converter object is not passed into extensions

### ISSUE THREAD

**Issue by DumboJetEngine** [showdownjs/showdown#289]
I have created a plug-in and, based on some samples I saw on-line, I assumed that the converter object should be passed into the extension.
But this is not the case in the 1.4.3 release. Instead, the window object is passed inside, which makes no sense to me:

![image](https://cloud.githubusercontent.com/assets/8676903/18442241/b378b4b4-7918-11e6-923c-fde3ccc2e72c.png)

Isn't this a bug?

**Comment by tivie** [comment]
I'm not quite sure what you mean but the converter is getting passed correctly to extensions.

[The documentation][1] clearly states that the "converter" object is passed as the second argument to "filter" type extensions.

You can see that behavior in [this fiddle][2]

```js
showdown.extension('test', function () {
  return {
    type: 'lang',
    filter: function(text, converter, options) {
      console.log('text', text);
      console.log('converter', converter);
      console.log('options', options);
      return text;
    }
  };
});

new showdown.Converter({extensions: ['test']}).makeHtml('some text');
```

[1]: https://github.com/showdownjs/showdown/wiki/extensions#filter-property
[2]: https://jsfiddle.net/tivie/tznuzdmt/

**Comment by DumboJetEngine** [comment]
Hm... That seems like a different method of registering extensions than the one I use (and is better too).
Here is what I use (`table` is my extension):

```
   // Define the `table` extension.
  ........................

  // Client-side export
  if (typeof window !== 'undefined' && window.Showdown && window.Showdown.extensions) { window.Showdown.extensions.table = table; }
  // Server-side export
  if (typeof module !== 'undefined') {
    module.exports = table;
  }
```

I have checked the arguments list and there is only one (the window).
Maybe the extension registration method I use is obsolete?
I found it inside the source code of your repository and I assumed it was OK to use. :(

**Comment by DumboJetEngine** [comment]
Oh...
Seems like I was using an old version. :(
I had downloaded the latest and though I was using it, but turns out I wasn't.
I was still referencing the older version.

So many changes in only a few months!?!? :o 
Even the case in the `showdown` global variable has changed! ;O

**Comment by DumboJetEngine** [comment]
OK.
I think I have figured things out now...
Sorry for the bugging.
