### ISSUE TITLE
Listener Extensions Bug

### ISSUE THREAD

**Issue by msfragala** [showdownjs/showdown#290]
I'm not sure on the status of listener extensions since the [Wiki](https://github.com/showdownjs/showdown/wiki/extensions#creating-showdown-extensions) indicates that they aren't an official feature yet. However, I noticed a probable bug in the [Converter source code](https://github.com/showdownjs/showdown/blob/master/src/converter.js#L129) where it registers listeners from extensions. It looks like just some missing quotations, so I'm happy to submit a PR!

**Comment by tivie** [comment]
You are correct, listeners are still very experimental, they don't even have proper testcases

**Comment by tivie** [comment]
@msfragala The bug you referred was fixed. However, if you're interested in helping developing listeners, that would be great
