### ISSUE TITLE
List of Resources

### ISSUE THREAD

**Issue by obedm503** [showdownjs/showdown#296]
Is there a list of showdown resources (extensions, examples, etc) where I can add my extension? 

I recently wrote a plugin for showdown which takes asciimath or latex and converts it to pretty html thru katex. It's basically a wrapper for katex. I also wrote some examples for it.

Is there a place anywhere that I can let people who might be interested know this functionality exists? a list of showdown supported/approved resources?

The extension in question is katex-latex - https://obedm503.github.io/katex-latex/

**Comment by tivie** [comment]
In the wiki. https://github.com/showdownjs/showdown/wiki

I've added your extension

**Comment by obedm503** [comment]
great. thanks
