### ISSUE TITLE
[Request] Server-side module for python or php

### ISSUE THREAD

**Issue by TheNofx68** [showdownjs/showdown#297]
Hey there !
I've been using this library for some time, but as I don't work (and don't want to) using nodejs, but I prefer to use php7 or python3/flask instead, I'd like to know if it'd possible to make a version for one of these two solutions ?
Thanks in advance !

**Comment by tivie** [comment]
Hi @TheNofx68! It's not in our plans to port the library into another programming language as it would be very time consuming and meant we need to keep parallel development of the two libraries while maintaining the output identical.


If you don't mind using nodejs in conjunction with PHP or Python, you can call showdown's CLI from your application and read the output. It's pretty straightforward and should be fast.

However, if you REALLY wanna get rid of installing nodejs altogether you might try:
 - [Convert JS to Python](https://github.com/timothycrosley/jiphy)
 - [Compile showdown's library](https://github.com/jaredallard/nexe) - Doesn't get rid of nodejs per se, but comes bundled with the app iteself in a single binary, so you don't really need to install or configure it.

As a last resort, you might wanna try https://github.com/michelf/php-markdown. The output should be very similar, although tehre are some features in showdown not supported in php-markdown and vice versa.

**Comment by TheNofx68** [comment]
Thanks for these infos, but I really don't want to have to work with nodejs, so it's a total no for me.
I can obviously understand the extra work part, and I'll take a look at the php-markdown you gave.
If none suits my needs, I think I'll work on porting your library into php.
Anyways, thanks !
