### ISSUE TITLE
How to remove language-xxx when converting markdown to html

### ISSUE THREAD

**Issue by jeud** [showdownjs/showdown#298]
Dear everyone

I intend to use the converted HTML with [highlight.js](https://highlightjs.org/) for syntax highlighting feature

My code example on markdown file

    ```bash
    # whatever here
    ```

The result after conversion from markdown file to HTML

    <pre>
        <code class="bash language-bash">
            # whatever here
        </code>
    </pre>

**Questions**

 How to remove `prefix-bash` from the `class` attribute because `highlight.js` only needs `class='bash'` for correcting syntax highlighting (I've tried with `showdown.getOptions()` I have seen no related options to setup)

Thanks everyone

**Comment by obedm503** [comment]
have you tried the official highlight extension? it uses google code pretty instead of highlight js

https://github.com/showdownjs/prettify-extension

**Comment by tivie** [comment]
> How to remove prefix-bash from the class  (I've tried with showdown.getOptions() I have seen no related options to setup)

Through showdown options you can't remove the class `language-bash`. The only only is with a output extension.

But what is the problem of having an extra class there?

**Comment by jeud** [comment]
@tivie no problems actually, I used to use *marked.js* and *remarkable.js* both are able configure the class prefix, so I'm just looking for equivalent from *showdown.js*

Also I had little understanding using *highlight.js* at the first place, after trying to learn more, I've found that it works both `class="bash lang-bash language-bash"` So I think I'm fine now :)

Thanks everyone @obedm503, @tivie
