### ISSUE TITLE
Hooking into converter.makeHtml() to customize HTML output

### ISSUE THREAD

**Issue by jeud** [showdownjs/showdown#300]
Dear everyone

I would like to add some extra attributes or some value into HTML output

Example Markdown
```markdown
![](img01.png)
```

Expected HTML Output
```html
<img src="/path/to/images/img01.png>
```

Where/how can I hook into the conversion process from markdown to HTML?, or must I do this after the HTML output?

Thanks everyone

**Comment by obedm503** [comment]
what kind of attributes do want to add? some classes?

you could make an extension

```js
showdown.extension('myext', function () {
  return [{
    type: "output",
    filter: function (html, converter, options) {
      //parse the html string
      var liveHtml = document.createElement('div');
      liveHtml.innerHTML = html;
      var images = liveHtml.getElementsByTagName('img');
      var image;
      for(var i = 0; i < images.length; i++) {
      	image = images[i];
        image.classList.add('some-css-class');
        // or even prepend the src
        //image.src = 'https://obedm503.github.io/bootmark/' + el.src;
      }
      return liveHtml.innerHTML;
    }
  }];
});
```

live fiddle: https://jsfiddle.net/n122569s/

**Comment by tivie** [comment]
ALso check the documentation regarding extensions https://github.com/showdownjs/showdown/wiki/Extensions

**Comment by jeud** [comment]
Thanks @obedm503 , @tivie, I've got some ideas what to do next :)
