### ISSUE TITLE
rendering fenced code block in list mess up

### ISSUE THREAD

**Issue by icymind** [showdownjs/showdown#301]
## env
showdown version: 1.4.4

There is a bug in rendering fenced code block nested in list by `showdown makehtml -i demo.md -o demo.html`. But the Live Editor works well: [Showdown Live Editor](http://showdownjs.github.io/demo/#/1.%20First%20step%0A%0A%20%20%20%20Demo%20of%20first%20step.%0A%0A%20%20%20%20Sub%20list%20of%20first%20step%3A%0A%0A%20%20%20%20-%20list%201.0%0A%0A%20%20%20%20%20%20%20%20%60%60%60bash%0A%20%20%20%20%20%20%20%20%23!%2Fbin%2Fbash%0A%0A%20%20%20%20%20%20%20%20echo%20%22demo%22%0A%20%20%20%20%20%20%20%20echo%20%22code%20block%20of%20sublist%22%0A%0A%20%20%20%20%20%20%20%20exit%200%0A%20%20%20%20%20%20%20%20%60%60%60%0A%0A%20%20%20%20-%20list%201.1%0A%0A%20%20%20%20Continue%20first%20step.%0A%0A2.%20Second%20step%0A%0A%20%20%20%20%60%60%60bash%0A%20%20%20%20%23!%2Fbin%2Fbash%0A%0A%20%20%20%20echo%20%22demo%22%0A%20%20%20%20echo%20%22code%20block%20of%20Second%20step%22%0A%0A%20%20%20%20exit%200%0A%20%20%20%20%60%60%60%0A%0A3.%20Last%20step)
## detail
Raw markdown:
![raw](https://cloud.githubusercontent.com/assets/1908329/20166200/2e94f8fc-a74e-11e6-9b1a-9a218de0f6e4.png)

github and [live editor](http://showdownjs.github.io/demo/#/1.%20First%20step%0A%0A%20%20%20%20Demo%20of%20first%20step.%0A%0A%20%20%20%20Sub%20list%20of%20first%20step%3A%0A%0A%20%20%20%20-%20list%201.0%0A%0A%20%20%20%20%20%20%20%20%60%60%60bash%0A%20%20%20%20%20%20%20%20%23!%2Fbin%2Fbash%0A%0A%20%20%20%20%20%20%20%20echo%20%22demo%22%0A%20%20%20%20%20%20%20%20echo%20%22code%20block%20of%20sublist%22%0A%0A%20%20%20%20%20%20%20%20exit%200%0A%20%20%20%20%20%20%20%20%60%60%60%0A%0A%20%20%20%20-%20list%201.1%0A%0A%20%20%20%20Continue%20first%20step.%0A%0A2.%20Second%20step%0A%0A%20%20%20%20%60%60%60bash%0A%20%20%20%20%23!%2Fbin%2Fbash%0A%0A%20%20%20%20echo%20%22demo%22%0A%20%20%20%20echo%20%22code%20block%20of%20Second%20step%22%0A%0A%20%20%20%20exit%200%0A%20%20%20%20%60%60%60%0A%0A3.%20Last%20step) rendered an expected html:
<img width="952" alt="github" src="https://cloud.githubusercontent.com/assets/1908329/20166229/54384a14-a74e-11e6-81de-7a86efa4fae0.png">

showdown's result by `showdown makehtml -i demo.md -o demo.html`
![ghost](https://cloud.githubusercontent.com/assets/1908329/20166242/62551082-a74e-11e6-97e0-95ad694b517d.png)

**Comment by tivie** [comment]
@icymind Are you using the latest showdown version?

**Comment by icymind** [comment]
Yes, I do use the latest version. The command `showdown -v` prints `1.4.4`

**Comment by tivie** [comment]
By default, the CLI tool has all options turned off. This means github's fenced codeblocks (a non standard markdown feature) is turned off.

So, the appropriate command should be:

```bash
showdown makehtml -i demo.md -o demo.html --ghCodeBlocks=true
```
