### ISSUE TITLE
Strikethrough enabled results in word annotation

### ISSUE THREAD

**Issue by ibenschop** [showdownjs/showdown#306]
When enabling strikethrough. Word interprets it as a annotation change.

**Comment by tivie** [comment]
@ibenschop Need more context. Please provide an example with input, expected result and actual result.

**Comment by ibenschop** [comment]
@tivie We are using showdown server side. 

this is our example text:

```
##I'm FreeForm Text That's made bigger
#Smaller 
###Bigger 
####Biggest 
*I have italics* 
**I am bold** 
~~I'm a strikethrough~~ 

- Unordered 1
- Unordered 2
- Unordered 3

1. Ordered 1
2. Ordered 2
3. Ordered 3 


[Link to Google](https://google.ca)

```

This is the implementation of shodown

```
const showdown = require('showdown');
const converter = new showdown.Converter();
converter.setOption('strikethrough', true);
.........
//ensure we swapp out \n newline correctly
htmlBody += converter.makeHtml(component.content.replace(/^( *(\d+\.  {1,4}|[\w\<\'\">\-*+])[^\n]*)\n{1}(?!\n| *\d+\. {1,4}| *[-*+] +|#|$)/gm, function(e) {
                return e.trim() + "  \n";
            }));

```

The result renders all the formatting correctly except the strikethrough. It results in a word 'change annotation' with the text that is suppose to be strikenthrough. We are using Word for Mac 2016.

Hope the above info helps.

Best,

Ian

**Comment by tivie** [comment]
So the problem is that MS Word is interpreting strikethrough as something else?

**Comment by ibenschop** [comment]
Hi Tobias,

My apologies. I think I have been posting the issue to the wrong thread. It seems html-to-docx is failing to translate <del>some text</del> correctly.

Thanks for you swift response

PS i can validate that it works perfect in showdown!
