### ISSUE TITLE
simplifiedAutoLink should exclude trailing punctuation

### ISSUE THREAD

**Issue by smblott-github** [showdownjs/showdown#308]
If the input is:

    Check out this cool site: https://github.com/showdownjs/showdown.

... then the trailing full stop should be excluded from the link.  (This is how GMail, etc, works.)

Would it be safe to skip all trailing punctuation marks?

**Comment by tivie** [comment]
That is a tricky one.
Fully qualified domains must end with a dot. So its not safe to skip trailing punctiation.

However, you rarely need to use fully qualified domains. Only in very specific situations where a URL might be ambiguous.

**Comment by tivie** [comment]
So I really don't know if we should go for practicality or correctness. 

The practicality argument is that you rarely need periods at the end of the url and in most cases the period marks the end of the sentence.

The correctness argument is that you can't safely assume the period isn't needed at the end of the URL.

A similar situation is discussed in issue #266 albeit regarding parenthesis.

Also, there's an interesting discussion at http://ux.stackexchange.com/questions/15226/should-a-sentence-ending-with-a-url-terminate-with-a-period

**Comment by tivie** [comment]
This was added as a new option called `excludeTrailingPunctuationFromURLs`. Enabling this will remove trailing punctuation and parenthesis from URL parsing in auto linking.
