### ISSUE TITLE
converter.makeHtml is slow for multiple dashes terminated with extra characters

### ISSUE THREAD

**Issue by rolandliwag** [showdownjs/showdown#315]
```
const converter = new require('showdown').Converter();
return converter.makeHtml('- - - - - - - - - - - - - - - - - - - - - - - - - - - - A');
```

The extra characters in this case are an nbsp (char code 160) and the uppercase A. Adding more dashes to the left makes it take more and more time. 

#312 partially fixed this since the output is now correct but it is still slow.

**Comment by tivie** [comment]
I've narrowed the problem (and found the culprit) but I'm really not sure how to fix it. In fact, I don't even know why it is so slow.

(I've opened a question in codereview)[http://codereview.stackexchange.com/questions/150277/why-is-this-regex-so-painfully-slow-in-certain-conditions], asking for help. Maybe they can find an answer.

**Comment by tivie** [comment]
Should be fixed now.

**Comment by rolandliwag** [comment]
Thanks again.
