### ISSUE TITLE
With new `simpleLineBreaks` or `'github'` flavor, lists receive `<br />`'s

### ISSUE THREAD

**Issue by nemoDreamer** [showdownjs/showdown#316]
Hey there, love the addition of simple GFM-style line-breaks, but they seem to be creating undesirable side-effects in lists:

```markdown
1. One
2. Two
  - A
  - B
3. Three
```

Becomes:

```html
<ol>
<li>One</li>
<li>Two<br />
<br />
<ul><br />
<li>A</li><br />
<li>B</li></ul></li>
<li>Three</li>
</ol>
```

Notice the `<br />`s after `<ul>` and `</li>`.
These also are present once you create a list of block elements.

**Comment by tivie** [comment]
Bug verified.

**Comment by tivie** [comment]
Do you notice this behavior with other elements aside from spans and blocks in list?

**Comment by tivie** [comment]
@nemoDreamer This should be fixed now. Do you mind testing it?
