### ISSUE TITLE
New horizontal rule regex breaks backwards compatibility (and GFM compliance)

### ISSUE THREAD

**Issue by tivie** [showdownjs/showdown#317]
The new regex breaks backwards compatibility in the following cases:

 - `   ---`: not parsed as horizontal rule
 - `   - - -`: not parsed as horizontal rule

**Comment by schoettler** [comment]
Still not parsed as horizontal rule (?)

**Comment by schoettler** [comment]
Whoops, needs a line break, my apologies
```
--- *works

text --- *does not work
```
As per Markdown spec

**Comment by tivie** [comment]
no prob
