### ISSUE TITLE
'simpleLineBreaks' doesn't work when a line ends with a Chinese character

### ISSUE THREAD

**Issue by chaoshxxu** [showdownjs/showdown#318]
```
foo烫
bar

foo
bar
```
Despite setting 'simpleLineBreaks' to true, the fragment above is rendered to:

```
<p>foo烫
bar</p>
<p>foo<br>
bar</p>
```

This issue can be reproduced in v1.5.4, while OK in v1.5.1

**Comment by tivie** [comment]
version 1.5.1 had a bug with simpleLineBreaks in lists (see #316 )
The regex was changed to only add line breaks in word boundaries.

It seems javascript does not recognise chinese characters as "words".

**Comment by tivie** [comment]
This should be fixed in latest develop
