### ISSUE TITLE
How to enable table frames and background color alternation each row? 

### ISSUE THREAD

**Issue by ItsmeJulian** [showdownjs/showdown#319]
The demo shows me these beautiful tables:
![image](https://cloud.githubusercontent.com/assets/16867291/21557995/ede0c770-ce33-11e6-8ad1-a16a6e155e83.png)
I try to do the same, no chance so far:
[http://jsfiddle.net/FfT6s/599/](http://jsfiddle.net/FfT6s/599/)
I do have showdown in use on [http://test.wedecide.at/#/setupPugh](http://test.wedecide.at/#/setupPugh) in the last tab _Save_ under button preview

**Comment by tivie** [comment]
Showdown's demo page uses foundation css with a few tweeks here and there. (http://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.min.css)

Check the updated fiddle
http://jsfiddle.net/tivie/oLofqLzf/3/
