### ISSUE TITLE
header ID generated are not compatible with ID generated on Github

### ISSUE THREAD

**Issue by veggiemonk** [showdownjs/showdown#320]
Hi, 

This is a great project!

For instance, on a README.md hosted on Github:
`# Title Example` --> `<h1 id="title-example">Title Example</h1>`

Same file but converted with Showdown:
`# Title Example` --> `<h1 id="titleexample">Title Example</h1>`

A dash `-` replace the space on github but showdow just erase it.
Is there an option for that? 
Otherwise we cannot be consistent with url when referring to a header.

Thanks a lot

**Comment by tivie** [comment]
@veggiemonk thanks! I will be adding an option for this soon.

**Comment by veggiemonk** [comment]
@tivie check #321 :D

**Comment by tivie** [comment]
I did

**Comment by tivie** [comment]
latest version should address this and more.

We're replacing spaces with dashes and removing the following characters: `][&~$!@#*()=:/,;?+'.%\`

Can you check if these characters are enough or if there are more that github replaces?

**Comment by tivie** [comment]
I've grabbed the replaced chars from github's redcarpet. https://github.com/vmg/redcarpet/blob/v3.4.0/ext/redcarpet/html.c#L276

Added `<` and `>` so this should cover every character github removes from header ids.

**Comment by veggiemonk** [comment]
@tivie great job, thanks a lot!
