### ISSUE TITLE
Changing image sizes

### ISSUE THREAD

**Issue by wolfgang1983** [showdownjs/showdown#326]
When I use reference links for images like

```
![enter image description here][1]
   [1]: https://www.example.com/image.jpg
```

```
var text = document.getElementById('message').value,
      target = document.getElementById('showdown'),
      converter = new showdown.Converter(),
      html = converter.makeHtml(text);

    target.innerHTML = html;
});

```
How to change the size of the image I tried like http://stackoverflow.com/questions/37938888/showdown-markdown-editor-how-to-resize-images-to-fit-in-with-the-content

**Comment by tivie** [comment]
as per [documentation](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#image-dimensions):

> When option parseImgDimensionis activated
>
>```md
>![Alt text][id]
>[id]: url/to/image =250x250
>```

**Comment by wolfgang1983** [comment]
How to add parseImgDimension my script?

**Comment by tivie** [comment]
As per [documentation](https://github.com/showdownjs/showdown#options)

```js
converter = new showdown.Converter({parseImgDimension: true});
```

or

```js
converter.setOption('parseImgDimension', true);
```
