### ISSUE TITLE
This actually doesn't work?? 

### ISSUE THREAD

**Issue by SeunMatt** [showdownjs/showdown#327]
I try using it in browser via the cdn and then do

~~~javascript
 var converter = new showdown.Converter();
  converter.setFlavor('github');
 console.log(converter.makeHtml("#Hello markdown"));
~~~

It only outputs #Hello markdown

**Comment by tivie** [comment]
As per [Github documentation](https://guides.github.com/features/mastering-markdown/), github markdown flavor requires a space between `#` and title text.

Showdown mimics this through the option **`requireSpaceBeforeHeadingText`** which gets enabled when you activate github flavor.

Either disable this option, disable github flavor or add a space between `#` and title text.
