### ISSUE TITLE
Hashtag without following space shouldn't be interpreted as header. 

### ISSUE THREAD

**Issue by mawek** [showdownjs/showdown#328]
It is common to have twitter like tags in text and they shouldn't be interpreted as headers as mentioned [here](https://talk.commonmark.org/t/heading-not-working/819/4)

**Comment by tivie** [comment]
1. Showdown follows the [original markdown spec](https://daringfireball.net/projects/markdown/) and not commonmark (which is a spinoff or flavor).

2. `#` followed by text is only interpreted as an header if `#` starts a newline, not in the middle of the text

3. A space between `#` and the text can become mandatory for headers if you enable the option **`requireSpaceBeforeHeadingText`**, as stated [in showdown's documentation](https://github.com/showdownjs/showdown#valid-options):

    > requireSpaceBeforeHeadingText: (boolean) [default false] Makes adding a space between # and the header text mandatory (since v1.5.3)

**Comment by tivie** [comment]
Duplicate #277

**Comment by mawek** [comment]
Thanks for quick response. I missed the ```requireSpaceBeforeHeadingText``` option.
