### ISSUE TITLE
[Question] Discrepancy in link rendering in showdownjs and the Markdown Spec

### ISSUE THREAD

**Issue by alfhenrik** [showdownjs/showdown#329]
We use `showdownjs` and a .NET Markdown to HTML converter in our app to render certain parts of our web UI and we have found that `showdownjs` (incorrectly?) renders link destinations that contain spaces, while the .NET library does not. We went a had a look at the [Markdown Spec](http://spec.commonmark.org/) to see what the correct behavior should be and it [looks like](http://spec.commonmark.org/0.26/#links) it should **not** render it as a link

> A link destination consists of either
>
> a sequence of zero or more characters between an opening < and a closing > that contains no spaces, line breaks, or unescaped < or > characters

The issue can be replicated in the [showdownjs JSFiddle](http://jsfiddle.net/tivie/6bnpptkb/) by adding `[commonmark.js](https://github.com/jgm/common mark.js)` to the document and clicking `Convert`, while doing the same in the [commonmark dingus](http://spec.commonmark.org/dingus/) does not render it as link but just as text.

Our question is, should `showdownjs` adhere to the Markdown Spec and would you accept a PR for bringing it in line?

**Comment by tivie** [comment]
Hey @alfhenrik It makes me sad no one reads [the awesome documentation we wrote](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax). :P

Commonmark is not ***the markdown spec***, but rather a markdown *flavor*. Showdown does not follow commonmark spec, it follows the original spec, as stated in our documentation.

> Although Showdown has evolved since its inception, in "vanilla mode", it tries to follow the [original markdown spec][md-spec] (henceforth refereed as vanilla) as much as possible.

------

Regardless, that is indeed a bug. If an URL containing spaces is found between `<` and `>` it should be left alone. I will look into it as soon as possible



    

[md-spec]: http://daringfireball.net/projects/markdown/

**Comment by alfhenrik** [comment]
Hey @tivie,

Thanks for the reply, I did read the awesome documentation you wrote, but I worded my question a bit to broad, I meant to ask if it should adhere to the spec regarding spaces in URLs.

My apologies, and thank you for your hard work on `showdownjs`!

**Comment by tivie** [comment]
@alfhenrik I had a look and it turns out the problem only arrises if you turn the option **simplifiedAutoLinks** on. (I was hasty claiming this was a bug =P)

This happens because the parser will look for links enclosed in `<>` first.
Then, since it does not find anything, since **simplifiedAutoLinks** is on, it will look for un enclosed links.
It finds a match and parses that match.


This means showdown's behavior is correct. In fact it matches Github's behavior.

```md
<http://www.google.com foo>
```

<http://www.google.com foo>

**Comment by obedm503** [comment]
this is interesting. What about links that actually have spaces in them? Generally links to documents, presentations, pdfs have spaces in the name. Should people write the parsed link between the `<>` directly?

so, this
```markdown
<https://link.com/file%20name>
```
instead of this?
```markdown
<https://link.com/file name>
```

**Comment by tivie** [comment]
@obedm503 yes. Space is not a valid character in a URI.
