### ISSUE TITLE
treat embedded HTML as inert text

### ISSUE THREAD

**Issue by Pomax** [showdownjs/showdown#341]
showdown seems to try to "understand" HTML code inside of a markdown file, and it would be incredibly valuable to be able to tell it *not* to do that, so that this:

```
# Preface

In order to draw things in 2D, we usually rely on lines, which typically get classified into two categories: straight lines, and curves. The first of these are as easy to draw as they are easy to make a computer draw. Give a computer the first and last point in the line, and BAM! straight line. No questions asked.

<div className="note">

## This book is open source.

This book is an *open source* software project

</div>
```
becomes this
```
<h1>Preface</h1>
<p>In order to draw things in 2D, we usually rely on lines, which typically get classified into two categories: straight lines, and curves. The first of these are as easy to draw as they are easy to make a computer draw. Give a computer the first and last point in the line, and BAM! straight line. No questions asked.</p>
<div className="note">
<h2>This book is open source.</h2>
<p>This book is an <em>pen source</em> software project</p>
</div>
```
rather than this

```
<h1>Preface</h1>
<p>In order to draw things in 2D, we usually rely on lines, which typically get classified into two categories: straight lines, and curves. The first of these are as easy to draw as they are easy to make a computer draw. Give a computer the first and last point in the line, and BAM! straight line. No questions asked.</p>
<div className="note">

## This book is open source.

This book is an *open source* software project

</div>
```

**Comment by Pomax** [comment]
As a specific use case, I need markdown with embedded HTML markup converted, not as "final content" step, but for further processing in a site bundle chain. The markdown needs to get wrapped by a JSX header and footer and is then passed into a webpack task that further deals with the content presented (including things that markdown has *zero* understanding of, like LaTeX conversion and replacing specific JSX tags with fully interactive canvas elements backed by a graphics library)

**Comment by tivie** [comment]
So, to make it clear, you want to parse markdown inside HTML tags?

Like this:

```
<div>
# header
</div>
```
becomes:

```html
<div>
<h1>header</h1>
</div>
```

**Comment by Pomax** [comment]
pretty much. I want to be able to say "treat `<` like a letter."

**Comment by tivie** [comment]
As explained in the [documentation][], to enable markdown parsing inside an HTML block, use the attribute `markdown` or  `markdown="1"`  or `data-markdown="1"`



[documentation]: https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#handling-html-in-markdown-documents

**Comment by tivie** [comment]
> pretty much. I want to be able to say "treat < like a letter". (Which is subtly different from "parsing inside HTML tags", although not on an implementation level - I don't even want it to think it's looking at HTML tags at it, it's just more "not markdown" =)

What?

**Comment by Pomax** [comment]
Language thing (I have a formal education in AI, which includes linguistics). From an implementation perspective, the code doesn't care whether humans call it "parsing the content of an HTML element" or whether there is no such thing as an HTML element.

As for that documentation: I am using showdown in Node scripts, not in the browser, and I don't see any mention on how to trigger that. I might be missing the obvious though, where would I find that option?

**Comment by tivie** [comment]
It's the same for node or browser.

```md
<div markdown="1">
this becomes **strong**
</div>

<div>
this does **not**
</div>
```

Here's working in the [demo][]

[demo]: http://showdownjs.github.io/demo/#/%23%20Preface%0A%0AIn%20order%20to%20draw%20things%20in%202D%2C%20we%20usually%20rely%20on%20lines%2C%20which%20typically%20get%20classified%20into%20two%20categories%3A%20straight%20lines%2C%20and%20curves.%20The%20first%20of%20these%20are%20as%20easy%20to%20draw%20as%20they%20are%20easy%20to%20make%20a%20computer%20draw.%20Give%20a%20computer%20the%20first%20and%20last%20point%20in%20the%20line%2C%20and%20BAM!%20straight%20line.%20No%20questions%20asked.%0A%0A%3Cdiv%20data-markdown-foobar%3D%221%22%20className%3D%22note%22%3E%0A%0A%23%23%20This%20book%20is%20open%20source.%0A%0AThis%20book%20is%20an%20*open%20source*%20software%20project%0A%0A%3C%2Fdiv%3E%0A%0A%23%20no%20parsing%0A%0A%3Cdiv%3E%0A%0A%23%23%20This%20book%20is%20open%20source.%0A%0AThis%20book%20is%20an%20*open%20source*%20software%20project%0A%0A%3C%2Fdiv%3E

**Comment by Pomax** [comment]
Right, I can't do that: I need it to be clean HTML, agnostic about which technology reads it. So is there a way to tell the library itself, through an option or conf or something, that it should treat it as inert text instead?

**Comment by tivie** [comment]
well, directly no, but if you want showdown to "ignore" embeded HTML  you can achieve that using an extension or using some preparsing.

# Preparsing

The preparsing option is a lot simpler, albeit a bit hackish. You can just replace `<` and `>` with some other character, before running the text throgh showdown, and then replace back that character.

see [fiidle here](https://jsfiddle.net/tivie/5pzsgjv5/)

This will treat `<` and `>` as 'a letter', like you asked. Please note that no`<` character will be escaped, which can have some side effects.

You can twink with the replacing rules, so it will only match certain conditions.


# extension

WIth an extension you can control how HashHTMLCode subparser behaves, telling it to treat every HTML  tag has having the attribute `markdown`. If you feel the preparsing solution is not enough, I can post a basic extension too

**Comment by Pomax** [comment]
Ah, I see. In that case I'll probably roll a small preprocessor for chunking up the input as stretches of Markdown and HTML tags, so showdown can be applied selectively to the markdown-only parts.

Thanks for the help!
