### ISSUE TITLE
Allow setting the classname of the wrapping div

### ISSUE THREAD

**Issue by jdalegonzalez** [showdownjs/showdown#342]
The generated html is wrapped in a parent div but the div has no classname or other attributes making it hard to style/reference.  It would be nice to be able to do something like... <Markdown className="flarm" ... and have "flarm" appear as the classname of the toplevel div.

**Comment by tivie** [comment]
Showdown does not wrap the output in any div. However, you can do it yourself 2 ways:

## in the input

```md
<div class="some-class" markdown="1">
some *markdown*
</div>
```

don't forget to add markdown="1" attribute or markdown won't be parsed inside the div


## wrapping the output in a div

```js
var otp = converter.makeHtml(input);
var div = document.createElement("div");
div.innerHTML = otp;
```

**Comment by tivie** [comment]
No answer in 7 days. Closing

**Comment by discordianfish** [comment]
@tivie This doesn't work with if you have block elements in the markdown: https://daringfireball.net/projects/markdown/syntax#html

"Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block."

**Comment by tivie** [comment]
@discordianfish You need to add `markdown="1"` to each block element you wish to be parsed as markdown.

```md
<div markdown="1">
  <div markdown="1">
    <div markdown="1">
      <div markdown="1">**foo**</div>
    </div>
  </div>
</div>
```

Keep in mind, however, that the parser will exponentially slow down for each level

**Comment by discordianfish** [comment]
Oh thanks, missed that!
