### ISSUE TITLE
Adding css link like the demo

### ISSUE THREAD

**Issue by goldenram** [showdownjs/showdown#343]
I have looked all over but cannot see how to add a stylesheet link like you have for the demo linking into the foundation stylesheet.  I thought it might be an extension setting, but I just don't see one.  Can you document how to add stylesheet during the conversion process?

**Comment by tivie** [comment]
The stylesheet is not added to the document but rather to the editor itself.
You can inspect http://showdownjs.github.io/demo/ (by pressing F12 in your browser) to see how the demo was done.
