### ISSUE TITLE
There is no escape for the pipe character

### ISSUE THREAD

**Issue by CaseyB** [showdownjs/showdown#345]
When I create a table I can't put the pipe character in the table. It renders correctly here on Github, but not in Showdown.

### Boolean Operators

| Operator | Description |
|----------|-------------|
| & | Logical AND |
| && | Shortcut AND |
| \| | Logical OR |
| \|\| | Shortcut OR |
| ^ | Logical XOR |

**Comment by tivie** [comment]
Bug verified

**Comment by tivie** [comment]
Should be fixed now. 

NOTE: Leave the issue open. It will be closed automatically when develop is merged into master
