### ISSUE TITLE
Converting file

### ISSUE THREAD

**Issue by kenanchristian** [showdownjs/showdown#346]
Can this be used for converting a `.md` file to a valid `.html` file?
I only saw this converting a `md` strings

**Comment by tivie** [comment]
Well, yes. You can use the cli tool for that.

In this example showdown is installed globally but you can achieve the same thing with a local installation.

##Windows

```cmd
echo ^<html^>^<head^>^</head^>^<body^> > otp.html
showdown makehtml -i "path/to/source/file.dm" >> otp.html
echo ^</body^>^</html^> >> otp.html
```

## unix

```cmd
echo "<html><head></head><body>" > otp.html
showdown makehtml -i "path/to/source/file.dm" >> otp.html
echo "</body></html>" >> otp.html
```

**Comment by kenanchristian** [comment]
@tivie I'm using nodejs, so maybe this is not the cleanest way to do it but it works! 👍 
thanks 😄 

![image](https://cloud.githubusercontent.com/assets/11202498/23145844/4cd8675c-f804-11e6-8536-fc4e39505742.png)
