### ISSUE TITLE
simplifiedAutoLink URLs with emphasis/strikethrough are not parsed correctly

### ISSUE THREAD

**Issue by jendewalt** [showdownjs/showdown#347]
When a user enters a URL with emphasis or strikethrough, the html output is incorrect. For example, if you enter `~~http://example.com~~` the html output is
```
<p><del><a href="http://example.com</del>"&gt;http://example.com~~</a></p>
```

The expected output is
```
<p><del><a href="http://example.com">http://example.com</a></del></p>
```

Thanks!

**Comment by tivie** [comment]
Verified!

**Comment by tivie** [comment]
Should be fixed now
