### ISSUE TITLE
Separate package for cli

### ISSUE THREAD

**Issue by vuorinem** [showdownjs/showdown#348]
Is it possible to create a separate package for the cli, so that the showdown parser could be used without all the dependencies from yargs?

**Comment by tivie** [comment]
If you don't mind me asking, what's the problem with showdown dependeing on yargs for the cli?

**Comment by tivie** [comment]
No answer for 24 days, closing

**Comment by vuorinem** [comment]
Sorry for not responding, I really don't like how GitHub handles notifications...

No specific reason for avoiding those dependencies, just a lot of packages (~800k and an annoying fork of isarray) for a feature that's not used when running on a web site. I'm using JSPM (for now). Although I realized that the dependencies can be avoided by installing through github-registry (instead of npm), which makes JSPM ignore dependencies without a registry.
