### ISSUE TITLE
cli: stdin won t work for me 

### ISSUE THREAD

**Issue by mh-cbon** [showdownjs/showdown#353]
Hi,

When i run this command, the output is empty,

```sh
cat README.md | showdown makehtml
Enabling option ghCodeBlocks
Enabling option encodeEmails
...
Reading data from stdin...
Parsing markdown...
Writing data to stdout...


DONE!
```

Where the README has content, see https://github.com/mh-cbon/emd/blob/master/README.md

Node -v 7.7.1 (also tested another older 7.x, broken too), i had to fallback to another tool, mdown

**Comment by tivie** [comment]
that is strange... what version of showdown are you using?

I've tested this on windows and it's working fine:

<img width="456" alt="2017-03-06" src="https://cloud.githubusercontent.com/assets/1608730/23616171/be93b456-0280-11e7-9256-14f80979d43d.png">

**Comment by tivie** [comment]
Tested on:
 - Windows 10
 - node 7.7.1
 - showdown 1.6.4

And it's still working fine:

<img width="456" alt="2017-03-06 4" src="https://cloud.githubusercontent.com/assets/1608730/23616469/bcd63fd4-0281-11e7-8419-57a620c90918.png">

**Comment by tivie** [comment]
you can also try running this command instead:

    showdown makehtml -i README.md 

and check if it works

**Comment by mh-cbon** [comment]
indeed : x

```
$ showdown -v
1.6.4
[mh-cbon@pc15-home ~] $ node -v
v7.7.1
```

see 
```
showdown makehtml -i README.md | wc -l
Enabling option ghCodeBlocks
Enabling option encodeEmails
...
Reading data from file...
Parsing markdown...
Writing data to stdout...


DONE!
138
```
and

```
$ cat README.md | showdown makehtml | wc -lEnabling option ghCodeBlocks
Enabling option encodeEmails
...
Reading data from stdin...
Parsing markdown...
Writing data to stdout...


DONE!
0
```

**Comment by tivie** [comment]
it seems showdown is able to find the README.d file but it is unable to read from it.

Can you try doing this:

    echo "# foobar" | showdown makehtml

**Comment by mh-cbon** [comment]
```
echo "# foobar" | showdown makehtml
Enabling option ghCodeBlocks
Enabling option encodeEmails
...
Reading data from stdin...
Parsing markdown...
Writing data to stdout...


DONE!
```

Digging the source, looks likes the problem is here, size is 0.

```
  function readFromStdIn () {
    try {
      var size = fs.fstatSync(process.stdin.fd).size;
console.log(size);
      return size > 0 ? fs.readSync(process.stdin.fd, size)[0] : '';
    } catch (e) {
      var err = new Error('Could not read from stdin, reason: ' + e.message);
      messenger.errorExit(err);
    }
  }
```

IMHO, i d refactor makehtml.run to copy the stdin stream to memory, rather than sync reading the fdesc.
http://stackoverflow.com/a/13411244/4466350

**Comment by tivie** [comment]
I've been testing this and could not reproduce the issue. 
And it's really bothering me!
