### ISSUE TITLE
Markdown intercepts indented HTML blocks

### ISSUE THREAD

**Issue by xduseko** [showdownjs/showdown#357]
Deeply nested HTML tags are not rendered properly, markdown somehow intercepts. 

```html
<div>
  <div>
    <div>
      <div>
        text
      </div>
      <div>
        text
      </div>
    </div>
  </div>
</div>
```

Renders into
```
text
text
</div>
```
See codepen http://codepen.io/anon/pen/wJedgq

**Comment by obedm503** [comment]
remember that indentation affects how the markdown is rendered

http://codepen.io/anon/pen/aJwLBx

**Comment by xduseko** [comment]
It shouldn't be processed at all unless I use markdown attribute.
```html
<div markdown>
  <div>
    <div>
      <div>
        text
      </div>
      <div>
        text
      </div>
    </div>
  </div>
</div>
```

**Comment by tivie** [comment]
This is indeed a bug but a hard one to tackle, due to efficiency constraints. I have a fix, but it slows down the parser considerably.

**Comment by tivie** [comment]
The workaround is not indenting html code.

**Comment by petebacondarwin** [comment]
Why do you have this `^ {0,3}` constraint on the start tags?
https://github.com/showdownjs/showdown/blob/072973ab8b027b86fb54bc6eb59850dc80f42b3a/src/subParsers/hashHTMLBlocks.js#L52

It can't be to avoid capturing indented code blocks as these are hashed away already, no?

**Comment by petebacondarwin** [comment]
Ah I see that indented code blocks are processed later.

**Comment by tivie** [comment]
Yes, they have to be processed AFTER HTML is hashed

**Comment by petebacondarwin** [comment]
@tivie - you talk about performance issues with your possible solution. Can you give me a pointer to how to run the performance tests as I would be interested in offering a PR for this issue but not if my solution also suffers from performance degradation.

**Comment by tivie** [comment]
If you install dev dependencies, you can run the command `grunt performance` and compare the results with previous implementations

**Comment by tivie** [comment]
Although performance degradation, in this case, happens with specific input: documents with a lot of "indented HTML".

**Comment by tivie** [comment]
This should (hopefully) be fixed now, without much performance issues.
