### ISSUE TITLE
Anchors with 

### ISSUE THREAD

**Issue by kirkins** [showdownjs/showdown#359]
I'm finding that all my single word anchors work automatically but not anchors with two or more words.

For example heading 'two words' in markdown displayed on github would create an anchor called '#two-words'. Though if I create a heading called "oneword" in the markdown it will automatically be linked with '#oneword'

**Comment by tivie** [comment]
Please provide an example with:
  - showdown configuration
  - input
 - expected output
 - actual output

**Comment by kirkins** [comment]
I'm using showdown like this:

```
    var rawFile = new XMLHttpRequest();
    rawFile.open("GET", "README.md", false);
    rawFile.onreadystatechange = function () {
      if(rawFile.readyState === 4) {
        if(rawFile.status === 200 || rawFile.status == 0) {
          var converter = new showdown.Converter();
          document.getElementById('body').innerHTML = converter.makeHtml(rawFile.responseText);
        }
      }
    }
    rawFile.send(null);
```

working: https://kirkins.github.io/EuroRomCom/#activities

Not working: https://kirkins.github.io/EuroRomCom/#word-lists

The second link works in the README on github but not on the website version generated by showdown.

**Comment by tivie** [comment]
Showdown, by default, removes spaces in titles to generate the ids. 

```md
# some header
```

```html
<h1 id="someheader">some header</h1>
```
Github has a different behavior. It replaces spaces (and other disallowed id chars) with dashes `-`.

To use the github behavior, use the option **[ghcompatibleheaderid](https://github.com/showdownjs/showdown/wiki/Showdown-options#ghcompatibleheaderid)**

**Comment by kirkins** [comment]
Great thanks!

**Comment by tivie** [comment]
No prob
