### ISSUE TITLE
Minimized version FIREFOX

### ISSUE THREAD

**Issue by lebeda** [showdownjs/showdown#363]
Hello
I have a problem with minification version **dist/showdown.min.js** in firefox.
Console says:
`SyntaxError: nothing to repeat`
Maybe problem is with `for(b=0;b<c.length;++b)/^ {0,3}\|/.test(c[b])&&(c[b]=c[b].replace(/^ {0,3}\|/,"")),/\|[ \t]*$/.test(c[b])&&(c[b]=c[b].replace(/\|[ \t]*$/,""));` When I comment this part of code, everything is fine.
In another browser is works fine

**Comment by tivie** [comment]
what FIrefox version and for what OS?

**Comment by lebeda** [comment]
Browser is `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0` It's Firefox development version. Operation system is Ubuntu 16.04.

**Comment by tivie** [comment]
We really need automated browser testing

**Comment by tivie** [comment]
I've tested and this is a bug of firefox 53. See https://bugzilla.mozilla.org/show_bug.cgi?id=1147371

**Comment by ZLevine** [comment]
FYI there is a similar issue with the minified version in the latest version of Chrome when you set `tables: true`. Using the full version fixes it.
