### ISSUE TITLE
Not correct behavior when switching between flavors

### ISSUE THREAD

**Issue by simov** [showdownjs/showdown#364]
:wave: 

`resetOptions` should be called inside `setFlavor` because these lines: https://github.com/showdownjs/showdown/blob/1.6.4/src/showdown.js#L117-L119 iterate only through what is found in that particular preset, i.e. if you `setFlavor('github')` then `setFlavor('vanilla')` and then `getOptions()` you get a combination between the `github` flavor and what is found in the `vanilla` flavor.

**Comment by tivie** [comment]
@simov thanks.

Do you mind issuing a PR with a testcase for this issue?

**Comment by simov** [comment]
Sure, I'll do that in a bit.
