### ISSUE TITLE
Support for named images

### ISSUE THREAD

**Issue by simov** [showdownjs/showdown#366]
```markdown
![something]

  [something]: http://i.imgur.com/GiLeftR.png
```

Should be rendered as image:

![something]

  [something]: http://i.imgur.com/GiLeftR.png

**Comment by tivie** [comment]
Should be implemented

**Comment by simov** [comment]
Thanks it covers all of my image test cases [here](https://github.com/simov/markdown-viewer/blob/master/syntax.md).

I'm using my Markdown Chrome Extension to quickly check markdown documents whenever I stumble upon something interesting. Currently only two compilers are officially bundled with the extension but Showdown as well as 6 others are supported, you can check it out [here](https://github.com/simov/markdown-viewer#more-compilers) if you are interested.

:+1:
