### ISSUE TITLE
Creates HTML object instead of string

### ISSUE THREAD

**Issue by maciejkiernarzycki** [showdownjs/showdown#368]
MD file 
"\\<foo\\>"
produces HTMLObject
\<foo\>\</foo\>

**Comment by tivie** [comment]
can you please provide more information?

**Comment by maciejkiernarzycki** [comment]
var converter = new showdown.Converter();
var html = converter.makeHtml('\<foo\>');

Then changing content of div with var html and it contains:
<foo></foo> instead of text

**Comment by maciejkiernarzycki** [comment]
Whole problem are just '\<' and' \>' signs

**Comment by maciejkiernarzycki** [comment]
Added to lines to makeHtml()

    text = text.replace('\\<','&lt;');
    text = text.replace('\\>','&gt;');

With this u can code '\<' '\>' in md file as  '\\<' \'\>'

**Comment by maciejkiernarzycki** [comment]
These do lines did all work in createHTML
    text = text.replace(/\\</g,'&lt;');
    text = text.replace(/\\>/g,'&gt;');

**Comment by tivie** [comment]
related to #374

**Comment by tivie** [comment]
Closing in favor o #374
