### ISSUE TITLE
Feature Request: Default Classes for each HTML element type

### ISSUE THREAD

**Issue by zusamann** [showdownjs/showdown#376]
I have read the documentation and gone through some of the issues, it seems like with some effort it might be possible to make an extension that does the required job. But I feel it really makes sense to have this functionality within the core library.

A lot of people use css ui kits like bootstrap, semantic-ui, etc. And if we could pass a bindings map object like so:
```js
const classBindings = {
  h1: '.ui.large.header',
  h2: '.ui.medium.header',
  ul: '.ui.list'
  li: '.ui.item'
}

const converter = new showdown.Converter({ classBindings });

const text = `
# 1st Heading
## 2nd Heading

- first item
- second item
`
return  converter.makeHtml(text);
```
```html
<h1 class="ui large header">1st Heading</h1>
<h2 class="ui medium header">2nd Heading</h2>
<ul class="ui list">
  <li class="ui item">first item</li>
  <li class="ui item">second item</li>
</ul>
```

Though if you think writing an extension for consuming this mappings object will be a very easy task, then could you please guide me on the same?

If possible I'd like to have the example added to the docs as well, like a recipe of sorts, so that other people can use it for bindings with any css ui kit of their choice.

And thanks so much for this wonderful library! 😁

**Comment by zusamann** [comment]
Actually it is very trivial to write such an extension. I can confirm that the one below does works as intended.

```js
const showdown = require('showdown');

const bindings = {
  h1: 'ui large header',
  h2: 'ui medium header',
  ul: 'ui list',
  li: 'ui item'
}

const extensions = Object.keys(bindings)
  .map(key => ({
    type: 'output',
    regex: new RegExp(`<${key}>`, 'g'),
    replace: `<${key} class="${bindings[key]}">`
  }));

const conv = new showdown.Converter({
  extensions,
  noHeaderId: true
});

const text = `
# 1st Heading
## 2nd Heading

- first item
- second item
`;

console.log(conv.makeHtml(text));
/**
​​​​​<h1 class="ui large header">1st Heading</h1>​​​​​
​​​​​<h2 class="ui medium header">2nd Heading</h2>​​​​​
​​​​​<ul class="ui list">​​​​​
​​​​​<li class="ui item">first item</li>​​​​​
​​​​​<li class="ui item">second item</li>​​​​​
​​​​​</ul>​​​​​
*/
```
You can close the issue, but as requested earlier, it would be useful for other people if this could be added to the documentation as a specific recipe.

**Comment by tivie** [comment]
Thank you @zusamann 

It is indeed a great idea to add this to the cookbook, which I will do as soon as possible.

**Comment by tivie** [comment]
Added this to the wiki. https://github.com/showdownjs/showdown/wiki/Add-default-classes-for-each-HTML-element

Thank you very much for your contribution!!

**Comment by fabiospampinato** [comment]
> Actually it is very trivial to write such an extension.

Is it though? I suppose the proposed solution doesn't take into account the content inside code blocks,  which shouldn't be modified at all.

**Comment by subodhpareek18** [comment]
You are right it might not be trivial. It was, but only for my use case which didn't have any code blocks. 

Though in case of code blocks as well, my guess is the parsed result would be something like a `<pre>` element, and the above solution will just add a css class to it and not modify any of the internal content.
```js
const classMap = {
  h1: 'ui large header',
  h2: 'ui medium header',
  ul: 'ui list',
  li: 'ui item',
  pre: 'some third party css class here'
}
```

So infact it should work fine as long as the parsed output is correctly encapsulated into valid html elements.
