### ISSUE TITLE
Use Numbered lists that start from a specific number

### ISSUE THREAD

**Issue by noam-honig** [showdownjs/showdown#377]
When I use numbered list, it always starts from 1. I want it to be able to start from 5 or any number I choose.

I get that behavior using MarkDig in C# and would love to have it here as well.

To my understanding also http://commonmark.org/ defines this.

How can I make this work using showdown?

1. noam
1. yael
```
Some code
```
3. red
4. blue

**Comment by tivie** [comment]
humm... you can only do that by hijacking the list parser through an extension... but the list parser is very complex, so it's no easy task

**Comment by tivie** [comment]
Github supports this feature (and it's even mentioned in the original spec) so it will be implemented in the next minor release.

**Comment by tivie** [comment]
Implemented on 9cdc35e and should be available next release @ v1.8.0.

---

>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money. Currently, we're looking to improve showdown with automated tests in all browsers and a proper domain and webpage. 500$ should be enough to to keep showdown testing framework running for a year or two.

**If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/34908) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated.**
