### ISSUE TITLE
openLinksInNewWindow breaks _em_ markup  

### ISSUE THREAD

**Issue by andistuder** [showdownjs/showdown#379]
When running the converter with `openLinksInNewWindow` set to `true`, it seems to break the conversion of the `_underscore_` => `<em>underscore</em>` markup. 

example string: 
`My [link](http://example.com) is _important_`

when I convert it with `openLinksInNewWindow` set `false`, I receive (as expected): 
`<p>My <a href="http://example.com">link</a> is <em>important</em></p>`

when I convert it with `openLinksInNewWindow` set `true`, I receive: 
`<p>My <a href="http://example.com">link</a> is _important_</p>`
the word important no longer wrapped with the `em` tag. 

Conversion of `*star*` => `<em>star</em>` works fine.

**Comment by tivie** [comment]
Verified

**Comment by tivie** [comment]
should be fixed now

**Comment by andistuder** [comment]
Much appreciated @tivie! When are you planning to merge this to `master`?

**Comment by tivie** [comment]
Soon. I'm planning the next release but wanted to merge https://github.com/showdownjs/showdown/pull/358 this PR that is dependent on creating a couple of tests. As soon as #358 is merged, a new showdown release will be published.

**Comment by andistuder** [comment]
Thanks for the quick fix @tivie  - I can confirm that works for me!
