### ISSUE TITLE
Architecture & Process Changes

### ISSUE THREAD

**Issue by coreyti** [showdownjs/showdown#38]
`Showdown` is evolving.  I'm interested in exploring options for making larger code architecture and project process changes here.

I'd love to hear from @pdeschen, @tstone and the `Showdown` community at large regarding the following ideas and any others.

Regarding project management, I'm wondering whether it's time to move things to a `Showdown` github "organization".  I feel a number of the recent contributors ought to be given commit rights and the newly added extension mechanism opens the door for `Showdown`, um..., extensions and my sense is that it would likely be good for those to be managed individually.

Regarding recording/maintaining the historical record, I feel it's important to be sure we continue to recognize `Showdown`'s roots and John Fraser as the original author.  On the other hand, it feels like much of the original examples, the Perl code, etc. could be moved "out of the way".  My suggestion here is to create a "legacy" branch (and tag?) which would make it easy to find that stuff, but just as easy to leave it behind and move forward unencumbered.

Thoughts?

**Comment by tivie** [comment]
https://github.com/showdownjs/showdown/commit/eae5f0e01fd086cfee87de5a547fcd057f59a460
