### ISSUE TITLE
Table of Contents rendering incorrectly

### ISSUE THREAD

**Issue by mahirk** [showdownjs/showdown#380]

**Comment by tivie** [comment]
?

**Comment by mahirk** [comment]
@tivie just as I posted it, I added the option to the config and that fixed it, while closing the issue I deleted the content in the request by mistake, here is the problem:

**PROBLEM**:
Incorrect rendering of the Table of Contents link v/s the id tag on the headings:

![issues_showdoiwn](https://cloud.githubusercontent.com/assets/5751414/25447625/c412a5f6-2a6a-11e7-9b45-645df530b4e5.png)

**SOLUTION**:
```
new showdown.Converter({ghCompatibleHeaderId: true});
```

**Comment by tivie** [comment]
glad you figure it out
