### ISSUE TITLE
Add options to enable/disable all subParsers

### ISSUE THREAD

**Issue by keligijus** [showdownjs/showdown#382]
Hi, I've got a use case where I need to selectively enable/disable subParsers. For example, I need to only allow **bold** and *italic* in certain use cases.

Would you be interested in a PR that adds options to enable/disable any subParser?

**Comment by tivie** [comment]
While it's possible to enable/disable subparsers, Showdown parser, as a whole, relies on sequential parsing (as it simplifies regex rules and improves speed a lot)

This means in some cases, disabling a determined subparser produces errors in another subparser.
For instance, disabling the "anchors parser" produces parsing errors in "Emphasis and strong parser".

So, unless showdown is completely rewrote, such a feature os not possible, as it would make showdown very unreliable.

**Comment by keligijus** [comment]
@tivie thanks for clarification. This seems too much trouble.. I guess I will have to make my own parser to do bold and italic only :)

**Comment by tivie** [comment]
Instead of making a parser from scratch, you can try to use showdown's subparsers and create a new logic around them. For instance ([see working fiddle](https://jsfiddle.net/tivie/n2zq8h91/)):

```js
function myConverter (text) {
		var options = {};
    var globals = {
    	converter: {
      	_dispatch: function (a, text) {
        	return text;
        } 
      }
    }
    // Standardize line endings
    text = text.replace(/\r\n/g, '\n'); // DOS to Unix
    text = text.replace(/\r/g, '\n'); // Mac to Unix
    // transform bold and italics
    text = showdown.subParser('italicsAndBold')(text, options, globals);

		return text;
}
```

**Comment by keligijus** [comment]
I was thinking about this too. Thanks so much for the awesome working fiddle 👍  It's going to be a great place to start
