### ISSUE TITLE
openLinksInNewWindow option not working

### ISSUE THREAD

**Issue by gazpachu** [showdownjs/showdown#386]
Hi, I've tried with `'true'` and `true` but it doesn't work. The `target` property is not being added. What am I doing wrong? I'm using the latest version ("showdown": "^1.6.4").

```
this.converter = new showdown.Converter({ openLinksInNewWindow: true });
console.log(this.converter.getOption('openLinksInNewWindow'));
```

The console log returns `true`, which means it's correctly set.

**Comment by tivie** [comment]
This feature is currently only available in develop branch.

**Comment by aaronincincy** [comment]
Is there any ETA for this feature being released?  I have a need for it for a project and want to be able to give an estimate to my PM when the inevitable bug comes up.

**Comment by tivie** [comment]
There are a couple of small fixes we want to push before the next release.
It should be up by the end of the week

**Comment by tivie** [comment]
New release published that includes this feature. https://github.com/showdownjs/showdown/releases/tag/1.7.0
