### ISSUE TITLE
Parsing escaped html entities

### ISSUE THREAD

**Issue by ghost** [showdownjs/showdown#39]
Showdown has been awesome so far, I just have a small issue with escaped html. For example I encode all html entities before running showdown on the user input. Therefore text like  
    &lt;http://google.com&gt;  //  Looks like github is parsing the link with html entities  
 no longer works because the regexs are not checking for escaped entities.
I have tweaked the regex to look like this:  
  
    // autolinking  
    text = text.replace(/(?:<|&lt;)((https?|ftp|dict):[^'">\s]+)(?:>|&gt;)/gi,"<a href=\"$1\">$1</a>");  
    [ignore]  
  
Im sure this may affect other parts of the code but this is the only piece that I have changed so far.

**Comment by pdeschen** [comment]
I don't think this is a bug. Markdown syntax do not support html entities. Otherwise we would end up with so many corner cases. Unless I'm missing something...
