### ISSUE TITLE
Unordered lists messed up

### ISSUE THREAD

**Issue by djjd47130** [showdownjs/showdown#397]
I have markdown formatted like so:

```
- **Customer** – Opens the Customer List. Refer to the document “Customer Management”.
    - Customer List
    - New Customer
    - Customer Prices
    - Appointments

- **Designer** – Opens the Designer List. Refer to the document “Designer Commissions”.
    - Designer List
    - New Designer
    - Designer Payment List
    - New Designer Payment
```

Produces:

![mdissue](https://user-images.githubusercontent.com/8213266/26839200-50c595e8-4ab0-11e7-90d2-149c98eea89d.png)

As far as I know, this is correctly formatted. It works in other places just fine. However, here in particular, using `Showdown`, I have the following issues:

1. Note there's no line break between first and second line - HTML output puts a break between.
2. Note there *is* a line break between the first and second group - HTML output does *not* put a break between.
3. The second main line labeled "Designer" does *not* get formatted as bold - it keeps those characters in the output.

Just as a test, I'm also going to paste the *exact same* markdown here below, and see how GitHub formats it...

- **Customer** – Opens the Customer List. Refer to the document “Customer Management”.
    - Customer List
    - New Customer
    - Customer Prices
    - Appointments

- **Designer** – Opens the Designer List. Refer to the document “Designer Commissions”.
    - Designer List
    - New Designer
    - Designer Payment List
    - New Designer Payment

**Comment by tivie** [comment]
verified. Introduced on v 1.6.0

**Comment by tivie** [comment]
Should be fixed now.


----
We're currently looking to improve showdown with automated tests in all browsers and a proper domain and webpage. If you like our work, please donate!! Your contribution will be greatly appreciated.

https://www.paypal.me/tiviesantos
