### ISSUE TITLE
Regression with literalMidWordAsterisks

### ISSUE THREAD

**Issue by zakness** [showdownjs/showdown#398]
It seems `literalMidWordAsterisks` is treating some non-word characters (such as `,`) as word characters and not converting to HTML properly. This was working correctly in `1.3.0` but not in `1.7.1` (these are the only versions I’ve tested).

Correct behavior in `1.3.0`:

```es6
const md = new showdown.Converter({ literalMidWordAsterisks: true })
md.makeHtml('strippers, **hitler**, and stalin')
// → <p>strippers, <strong>hitler</strong>, and stalin</p>
```

Incorrect in `1.7.1`:

```es6
const md = new showdown.Converter({ literalMidWordAsterisks: true })
md.makeHtml('strippers, **hitler**, and stalin')
// → <p>strippers, **hitler**, and stalin</p>
```

If you remove the `literalMidWordAsterisks` option in `1.7.1` it works again:

```es6
const md = new showdown.Converter()
md.makeHtml('strippers, **hitler**, and stalin')
// → <p>strippers, <strong>hitler</strong>, and stalin</p>
```

**Comment by tivie** [comment]
confirmed

**Comment by tivie** [comment]
`literalMidWordsAsterisk` option was only introduced in version 1.7.0, so in version 1.3.0 it does nothing.

**Comment by tivie** [comment]
Should be fixed now
