### ISSUE TITLE
Escaping characters (angle brackets, etc.) in code blocks/snippets

### ISSUE THREAD

**Issue by devEngine** [showdownjs/showdown#400]
I'm certain this has been asked elsewhere and/or described in some bit of documentation but I'm missing the solution and can't find it (I plead forgiveness in advance).

I've got template content which I load into a div as follows for which I use showdownjs to convert to html as follows:

```
<script>        
    (function (){
        var conv = new showdown.Converter();
        var txt = document.getElementById('article').innerHTML;              
        document.getElementById('article').innerHTML = conv.makeHtml(txt);
    })();
</script> 
```

This works pretty well except that any/all code snippets containing angle brackets for greater-than or less-than signs get HTML-escaped, thus:

< becomes \&lt;
\> becomes \&gt;

and so on. Just for the record, such sections appear in markdown-compliant code outtakes (between the '```' markers) but these get escaped anyway.  Would some kind soul please point me in the right direction as to how to workaround this?

Apologies as I don't want to create an issue where it's not warranted, but I can't seem to find the answer anywhere (don't think it's related to the HTML tag escaping issue: https://github.com/showdownjs/showdown/issues/374) but not sure.

Thanks in advance for any help.

**Comment by tivie** [comment]
Hi @devEngine 

It's like this by design and required by markdown spec, or else code snippets could end up messing the generated html. 

All markdown implementations do this (check [babelmark2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0A%3Chtml%3E%3C%2Fhtml%3E%0A%60%60%60)

For instance:

    ```
    </code></pre>
    ```

This would generate:

```
<pre><code>
</code></pre>
</code></pre>
```


In fact, it is required by HTML spec that, at least, < symbols should be escaped, even inside code blocks.

**Comment by devEngine** [comment]
Thanks very much for your response - and I'm sure it's **me** missing something so apologies once again.

I have this in my original markdown content (between the 3 backticks):

```
{
     accountNum          =>    "$ENV/{HOME}/acct"
   , configFile               =>    "$ENV{HOME}/config"    
},

```

and no matter how I escape the brackets, I always end up getting from the converter:

```
{
     accountNum          =&gt;    "$ENV/{HOME}/acct"
   , configFile               =&gt;    "$ENV{HOME}/config"    
},

```

Any ideas how I should escape these to display the actual brackets?

**Comment by devEngine** [comment]
Sorry, got it with reference to your helpful link.  Thanks for your assistance!
