### ISSUE TITLE
Showdown 1.7.1 not converting tables in live edit 

### ISSUE THREAD

**Issue by sevaho** [showdownjs/showdown#401]
```html
<textarea id="editor" name="text"></textarea>
<div id="html"></div>
```

```js
function convertToHTML () {

  let c = new showdown.Converter();
  $("#html").html(c.makeHtml($("#editor").val()));

}
```

This does not parse tables right, fe: when inserting:
```
| h1    |    h2   |      h3 |
|:------|:-------:|--------:|
| 100   | [a][1]  | ![b][2] |
| *foo* | **bar** | ~~baz~~ |
```

I get this in the #html field:

```
| h1 | h2 | h3 | |:------|:-------:|--------:| | 100 | [a][1] | ![b][2] | | foo | bar | ~~baz~~ |
```

It get parsed as a "\<p\>" string, what am I doing wrong?

**Comment by tivie** [comment]
you need to activate the table parser through options

See the [README](https://github.com/showdownjs/showdown#valid-options) or the [wiki](https://github.com/showdownjs/showdown/wiki/Showdown-options#tables)

**Comment by sevaho** [comment]
Makes sense, thank you very much for your help, it works now :)
