### ISSUE TITLE
a list is displayed despite missing the required line break

### ISSUE THREAD

**Issue by PhilipNunn** [showdownjs/showdown#404]
When providing markdown like:
```
    foo
    - list text here
```
the resulting HTML shows:
foo 
 - list text here

(looks like GitHub has the same issue)  However, since there is no line break after foo, the next line should not be rendered as a list. Although this looks right to the user client-side, the correct but unexpected result with no bullet list is obtained server-side using MarkdownSharp.

**Comment by tivie** [comment]
Seems implementations do not agree between them (and this rule is not specified in the original spec).

https://johnmacfarlane.net/babelmark2/?normalize=1&text=foo%0A-+list+text+here

**Comment by PhilipNunn** [comment]
I see, thanks
