### ISSUE TITLE
Doesn't render one-column tables

### ISSUE THREAD

**Issue by faloi** [showdownjs/showdown#406]
I tried both in my app and the live editor and doesn't work, although `tables` option is enabled.

_Sample markdown:_
```
|some header |
|------------|
|some content|
```

_Expected result:_

|some header |
|------------|
|some content|

**Comment by faloi** [comment]
@rodri042 this is why tables aren't working properly, please subscribe to this issue.

**Comment by tivie** [comment]
Should be fixed now
