### ISSUE TITLE
PrefixHeaderId does not accept forward slashes

### ISSUE THREAD

**Issue by baileyherbert** [showdownjs/showdown#409]
An [`id` attribute](http://www.w3.org/TR/html5/dom.html#the-id-attribute) value may, according to HTML5 and in browser practice, contain any characters except space characters.

In showdown, passing a forward slash in as an ID prefix, like this:

```js
{
  prefixHeaderId: "/layout/"
}
```

Yields a very unexpected result. Instead of generated IDs looking like `id="/layout/simplified-header-text"` it looks instead like `id="layoutsimplified-header-text"`.

Is there an easy workaround to this?

**Comment by tivie** [comment]
According to the HTML [spec](https://www.w3.org/TR/html4/types.html#type-id):

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

**Comment by baileyherbert** [comment]
Is showdown still living in HTML4, then? That link is HTML4.

Here's the direct quote from [W3 HTML5 specification](https://www.w3.org/TR/html5/dom.html#the-id-attribute):

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
> The value must not contain any space characters.

**Comment by tivie** [comment]
Showdown supports HTML4 and HTML5 spec (with some restrictions).

**Comment by tivie** [comment]
I don't know how we could make showdown compliant with HTML4 and HTML5, honestly

**Comment by tivie** [comment]
@baileyherbert You now have 2 options to fix this:

 * use option `rawHeaderId` which removes only spaces, ' and " from titles.
 * use option `rawPrefixHeaderId` which leaves the prefix alone (doesn't change any character from the prefix)

Keep in mind that both options might result in malformed IDs. For instance, when you use `rawPrefixHeaderId` and use a prefix with `"` or ` `

**Comment by baileyherbert** [comment]
Yup, working perfect now. Thanks!
