### ISSUE TITLE
a parse bug

### ISSUE THREAD

**Issue by snowair** [showdownjs/showdown#41]
## markdown text:
```
* list

		+ item

             - subitem

               The HTML has a superfluous newline before this
               paragraph.

             - subitem

               The HTML here is unchanged.

             - subitem

               The HTML is missing a newline after this
               list subitem.
```
## correct  markdown parse :
* list

		+ item

             - subitem

               The HTML has a superfluous newline before this
               paragraph.

             - subitem

               The HTML here is unchanged.

             - subitem

               The HTML is missing a newline after this
               list subitem.

## the showdown parse :
<p>list</p>
<pre><code>+ item

<pre><code> - subitem

   The HTML has a superfluous newline before this
   paragraph.

 - subitem

   The HTML here is unchanged.

 - subitem

   The HTML is missing a newline after this
   list subitem.
</code></pre>

</code></pre>

**Comment by pdeschen** [comment]
Am I correct in saying that this would produce the equivalent html output? This is already documented in [divergences](https://github.com/showdownjs/showdown/wiki/divergences)

**Comment by tivie** [comment]
@pdeschen Yes, it is documented

**Comment by pdeschen** [comment]
Ok invalid for now then.
