### ISSUE TITLE
Feature Request: Add support for link targets

### ISSUE THREAD

**Issue by rhulet34** [showdownjs/showdown#410]
When creating a link in the markdown editor, the user should be able to specify a target (`New Tab` or `Same Tab`) for the link. The `New Tab` option should be selected by default. 

As a developer I would like an option that sets or takes in a value for this

**Comment by tivie** [comment]
There's already an option for opening in a new window

**Comment by rhulet34** [comment]
Yes but does the new window open in a new tab or an actual new window, and is it able to be set in the markdown?

**Comment by rhulet34** [comment]
Alright I tested it, opens in new tab....just got a little confused by the wording. Thanks.
