### ISSUE TITLE
<tag> in table is not parsed as Github does

### ISSUE THREAD

**Issue by naivefun** [showdownjs/showdown#415]
In github this can be parsed:
```markdown
|    名称    |   编码   |    数据类型    | 描述 |
| ---------- | -------- | -------------- | ---- |
| 消息元数据 | meta     | Metadata       |      |
| 消息数据体 | payloads | List\<Payload> |      |
```
<img width="423" alt="screen shot 2017-08-04 at 12 23 14 pm" src="https://user-images.githubusercontent.com/10683378/28954161-b888c500-790f-11e7-8ff8-e30ea2b8c4d9.png">

But this cannot work in showdown with github flavor, the `List\<Payload>` is parsed to `<td>List\</td>`

**Comment by tivie** [comment]
Try with version 1.7.2 and with option `backslashEscapesHTMLTags` enabled
