### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by TC827** [showdownjs/showdown#418]
I'm using your library in SAP. I do not know exactly what environment is behind.
There should be some compatibility issue, I get the error:
`CL_JAVA_SCRIPT, Rcode: (   201 ), Error at line 1453 : unterminated character class [   `
I download your actual dist and the line should be the following:
```javascript
simpleMailRegex = /(^|\s)(?:mailto:)?([A-Za-z0-9!#$%&'*+-/=?^_`{|}~.]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)(?=$|\s)/gmi,
```
Is there a workaround?

**Comment by tivie** [comment]
That's strange because the regex is correct. What version of showdown are you using?

**Comment by TC827** [comment]
I'm using showdown 05-08-2017, but I think that the js engine of SAP (in ABAP environment) is old and I do not know where to get which version SAP is using. Thank you.
