### ISSUE TITLE
bug - Automatic Extension Loading (node only) 

### ISSUE THREAD

**Issue by js-seth-h** [showdownjs/showdown#42]
I found misspelling.
please fix 'undefind' to 'undefined'.

showdown.js , line 120

//
// Automatic Extension Loading (node only):
//
if (typeof module !== 'undefind' && typeof exports !== 'undefined' && typeof require !== 'undefind') {
if (typeof module !== 'undefined' && typeof exports !== 'undefined' && typeof require !== 'undefined') {

**Comment by tivie** [comment]
Fixed in 24716d3520089ce88127ace39d55d8b217a89512
