### ISSUE TITLE
it can't support unicode word

### ISSUE THREAD

**Issue by shangxinbo** [showdownjs/showdown#423]
I use showdown.Convert, and converter.makehtml . can it set utf-8 or parse options? because I use the unicode word like '中国' but it can't be supported
```
let converter = new showdown.Converter()
let html = converter.makeHtml(data.data)
console.log(html)
```

**Comment by shangxinbo** [comment]
s

**Comment by shangxinbo** [comment]
sorry it's my fault

**Comment by tivie** [comment]
no problem

**Comment by daiyi** [comment]
(For future reference, this can be fixed by setting the encoding to UTF-8 by including `<meta charset="utf-8"> ` in the `<head>` tag of your page. [ref](https://www.w3schools.com/charsets/ref_html_utf8.asp))
