### ISSUE TITLE
Some table not render

### ISSUE THREAD

**Issue by webbery** [showdownjs/showdown#424]
Following markdowns can not convert to table:
~~~
|`----D----e--e--e-----p----------- L----ea-------r---------ni-----ng-----` |
|:--------------|
|![Deep Learning](https://github.com/zackchase/mxnet-the-straight-dope/raw/ee284e1fd773bc25f7b70605e92d5fad0972fe6b/img/speech.jpg)|
~~~
And
~~~
|`Tom wants to have dinner in Washington with Sally.`|
|:--|
|`E   -     -  -    -      -  E          -    E`|
~~~
And
~~~
|![](https://github.com/zackchase/mxnet-the-straight-dope/raw/ee284e1fd773bc25f7b70605e92d5fad0972fe6b/img/death_cap.jpg)|
|:-------:|
|Death cap - do not eat!|
~~~
It looks like a bug.

**Comment by tivie** [comment]
One column tables are supported in latest develop, commit fef110c .

Check the [demo](http://showdownjs.github.io/demo/#/%7C%60----D----e--e--e-----p-----------%20L----ea-------r---------ni-----ng-----%60%20%7C%0A%7C%3A--------------%7C%0A%7C!%5BDeep%20Learning%5D(https%3A%2F%2Fgithub.com%2Fzackchase%2Fmxnet-the-straight-dope%2Fraw%2Fee284e1fd773bc25f7b70605e92d5fad0972fe6b%2Fimg%2Fspeech.jpg)%7C)

Related to #406

**Comment by webbery** [comment]
@tivie I can't see demo for my country‘s firewall.  I captured the image of  codes in jsfiddle:
![default](https://user-images.githubusercontent.com/5257853/29518666-e676be40-86ac-11e7-9468-bfd8a24fe549.png)
I used version 1.7.2.

**Comment by tivie** [comment]
@webbery Use [version 1.7.3](https://github.com/showdownjs/showdown/releases/tag/1.7.3) It fixes this bug.

Just a question, where are you from? China? Why is your country blocking showdown's demo page?!?!

**Comment by tivie** [comment]
That's really strange. Showdown demo does not have any kid of propaganda...
