### ISSUE TITLE
Does not support code highlighting

### ISSUE THREAD

**Issue by gene-l-thomas** [showdownjs/showdown#427]
Showdown does not support code highlighting, or I am doing something wrong:

`sudo npm install showdown -g`<br>
`showdown makehtml -i c#-for-scripting.md -o c#-for-scripting.html`

the code in the .html file is not highlighted :o(. .md and .html files attached.
I am running Ubuntu 16.04.3 LTS

[showdown markdown and resulting html .zip](https://github.com/showdownjs/showdown/files/1254214/showdown.markdown.and.resulting.html.zip)

**Comment by tivie** [comment]
Code highlight is provided through an extension. 

https://github.com/showdownjs/prettify-extension

**Comment by tivie** [comment]
@gene-l-thomas did you check those extensions?

Closing as no response for 12 days
