### ISSUE TITLE
Feature request: makePlainText method to strip markdown

### ISSUE THREAD

**Issue by projectitis** [showdownjs/showdown#433]
Feature request: makePlainText method to strip markdown completely.

Use case: My client app has some fields that allow formatting via markdown (e.g. the *description* field) and others that should not (e.g. the *first name* and *last name* fields).  I'd like to be able to strip any markdown from the content before displaying it in these fields, just in case the user has entered any.

I realise there are other javascript projects around that do this, but it would be great for showdown to support it directly.

**Comment by tivie** [comment]
If all content is parsed through Showdown (as it seems the case), you can escape the "*magic*" markdown characters to prevent anything to be parsed as markdown.

This is best accomplished by a pre parser or an extension, dependeing on use case. [(See fiddle)][1]

```js
showdown.extension('escapemd', function() {
  return [{
    type: 'lang',
    regex: /[\][=~`#|()*_-]/g,
    replace: "\\$&"
  }];
});
```

----
We're currently looking to improve showdown with automated tests in all browsers and a proper domain and webpage. If you like our work, please donate!! Your contribution will be greatly appreciated.

https://www.paypal.me/tiviesantos


[1]: https://jsfiddle.net/tivie/pydka770/

**Comment by tivie** [comment]
@projectitis This this help you?

**Comment by projectitis** [comment]
Sorry, I haven't had a chance to implement it yet, but it looks like the perfect solution. Thanks!
