### ISSUE TITLE
Table Markdown not Rendering

### ISSUE THREAD

**Issue by geudrik** [showdownjs/showdown#434]
Using the example in the wiki docs, and the JSFiddle link as a demo, the example Table code does not render at all.

[Table Markdown](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#tables)

**Comment by tivie** [comment]
As it stated in the documentation:

> Tables aren't part of the core Markdown spec, but they are part of GFM and Showdown supports them by turning on the option `tables`.

So you need to turn on the option `tables`;

```js
var converter = new showdown.Converter({tables: true});
```

**Comment by tivie** [comment]
----
We're currently looking to improve showdown with automated tests in all browsers and a proper domain and webpage. If you like our work, please donate!! Your contribution will be greatly appreciated.

https://www.paypal.me/tiviesantos

**Comment by t1m0t** [comment]
Would be great to add proper indication in the wiki for example as to enable options in Showdown as I didn't find any of this except here :/

**Comment by tivie** [comment]
It's both in the [wiki](https://github.com/showdownjs/showdown/wiki/Showdown-options) and in the [README.md](https://github.com/showdownjs/showdown#options)

**Comment by geudrik** [comment]
@tivie 👍 I can't read. Thanks

**Comment by dessalines** [comment]
This isn't working when going from html to markdown, even with the table option enabled.

**Comment by neooblaster** [comment]
For CLI : `showdown makehtml -i file.md -o file.html --tables`

**Comment by ndu2** [comment]
> For CLI : `showdown makehtml -i file.md -o file.html --tables`

thanks - and for CLI Version v2.1.0 use `showdown makehtml -i file.md -o file.html -c tables`
