### ISSUE TITLE
This is broke

### ISSUE THREAD

**Issue by mjbrancato** [showdownjs/showdown#436]
Using the Browser code with the CDN JS, nothing displays on the page.

**Comment by tivie** [comment]
What is the error you're getting?

**Comment by tivie** [comment]
Closing as no update in 6 days

**Comment by mjbrancato** [comment]
Input: Copy and paste the code example from the markdown file.

Expected Output: The markdown text to be converted to the markdown preview

Actual Output: Markdown just shows all text and there is no preview.

Sorry, I was busy and didn't have time to fill in all this information. I decided to go with a PHP plugin since none of the JavaScript plugins seem to work with MarkDown.

**Comment by tivie** [comment]
Did you initialize showdown?

```
var conv = new showdown.Converter();
var html = conv.makeHtml('**some** *text*');
alert(html);
```

**Comment by codermjb** [comment]
>var conv = new showdown.Converter();
>var html = conv.makeHtml('**some** *text*');
>alert(html);

This worked!

I think I got confused by the markdown example and how the var was a one line var rather than seperate like your example, which I don't usually do that. Then I think I was using text instead of html.

Sorry about that!

**Comment by tivie** [comment]
If you want to convert files, there's a CLI imbued in showdown. You need to install nodejs though

**Comment by codermjb** [comment]
@tivie thank you, but I would prefer not to.

I have a PHP plugin that already takes markdown and converts it to HTML.

Showdown does it too, but I just need to figure out how to put multiple lines of markdown text in it.

**Comment by tivie** [comment]
Multiple lines? Of course you can...

see [the demo page](http://showdownjs.github.io/demo/)

see [a fiddle doing exactly that](https://jsfiddle.net/tivie/qqksnqws/)

**Comment by codermjb** [comment]
Oh ok, so it's working in a text area, but it doesn't work here: var html = conv.makeHtml('<?php echo $markdown; ?>');

And there is no CSS formatting at all.

**Comment by tivie** [comment]
?!? You're trying to render a PHP variable into a Javascript variable?!?  
Obviously that will not work... a newline character will "break" the string literal. Multiline strings are not supported in javascript.

But that is outside the scope of showdown.

**Comment by codermjb** [comment]
Yes I understand that the multilines, I thought there was a solution. Either way, I am trying to fetch a md file and parse it into showdown, I know there is a way and I will figure it out and provide the answer, especially now that you showed me how to get it working.

My issue is there is no CSS that gets parsed. It does not show the example like in the project of showdown or the really nicely formatted html in the link you sent.

What include do we need for the CSS? It's not in the readme.

**Comment by tivie** [comment]
The demo uses foundation (//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.min.css)

**Comment by codermjb** [comment]
Thank you. Using both of those looks slightly better than a previous CSS styling that I found for the PHP plugin so I will use your plugin with the Cebe/PHP plugin I currently have.

I will however, work on a way so you can fetch a markdown file and use showdown to convert it so that way I am contributing something back. Would that be something you would be interested in so you can add a comment? I am going to use a basic AJAX get request to load it in there.

**Comment by tivie** [comment]
Showdown works both client (browser) and server (nodejs) side so it won't make much sense to add that feature.

Feel free, however, to design an "editor", based on showdown, that supports file import and export. You can grab the demo as a basic template https://github.com/showdownjs/demo

**Comment by codermjb** [comment]
Sorry, I didn't mean that, I mean like an example like this. Then you can fetch actual files on the server.

And might be nice to add to your readme.md for a method to fetch files and convert them via showdown.

Include jQuery CDN file `<script
  src="//code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>`

```
<script>
    $(function(){
        $.get("coding.md", function(data, status){
            var markdownText = data;

            var converter = new showdown.Converter({
              'strikethrough': true
            });
          
            // converts the markdown text into html
            var html = converter.makeHtml(markdownText);

            // paste the HTML inside the appropriate div
            document.getElementById('trg').innerHTML = html;
        });
    });
</script>
```

**Comment by obedm503** [comment]
As for the fetching, converting and styling Markdown files automatically, [bootmark](https://obedm503.github.io/bootmark) already does that

**Comment by codermjb** [comment]
@obedm503 showdown does that too. I just provided a working example for you guys.

I am trying to help you out on improving the readme file since it is lacking. Issues with example, no file support, and no CSS. No need to modify your code, just need to enhance readme file.

**Comment by EvilJordan** [comment]
For anyone else that stumbled upon this and doesn't need some elaborate solution, the culprit is the encoded newline characters, which you can easily replace with escaped versions:

`converter.makeHtml('<?php echo str_replace("\n",'\\n',addslashes(file_get_contents("/path/to/your.md"))); ?>')`
