### ISSUE TITLE
GFM mode - only two new lines must produce a <br>

### ISSUE THREAD

**Issue by pleerock** [showdownjs/showdown#438]
```md
hellow world
how are you
```

Must be intepreted as:

```html
hellow world how are you
```

not

```html
hellow world<br/>
how are you
```

like right now

**Comment by pleerock** [comment]
Only

```md
hellow world

how are you
```

must produce:

```html
hellow world<br/>
how are you
```

**Comment by pleerock** [comment]
Its reproducable only when:

```js
converter.setFlavor('github');
```

is used.

**Comment by pleerock** [comment]
Solution is to do:

```js
converter.setFlavor('github');
converter.setOption('simpleLineBreaks', false);
```

**Comment by tivie** [comment]
try this here in the issue comment box:

```
github default behavior 
is to treat
each linebreak
as a `<br>`
tag, at least
in comments.
:)
```

github default behavior 
is to treat
each linebreak
as a `<br>`
tag, at least
in comments.
:)

**Comment by pleerock** [comment]
Yes you are right, it does it this way in comment editor. However when it parses `.md` files (like README.md) it does it different.

**Comment by tivie** [comment]
> Yes you are right, it does it this way in comment editor. However when it parses .md files (like README.md) it does it different.

Yeah, it's inconsistent in how it parses markdown, so we aren't really sure which behavior to implement. 
I think, maybe, we should point this out in the wiki so users won't be surprised by this behavior.

**Comment by sulthan-ahmed** [comment]
I ran into a [similar problem](https://github.com/UKHomeOffice/right-to-rent-check/pull/127) but thankfully this explanation cleared everything up.  Adding it to the README would be helpful
