### ISSUE TITLE
Safe output

### ISSUE THREAD

**Issue by Alir3z4** [showdownjs/showdown#45]
Hi
I've noticed that **Showdown** doesn't escape the _HTML_ tags.
With **Python** port of _markdown_ it's possible to have _safe_ output  by passing the **safe** arg to markdown converter, and all the html tags will be removed or replaced by a word.

I guess it's better to just strip _HTML_ tags and remove them completely.

**Comment by Download** [comment]
Markdown (and thus also Showdown) are inherently unsafe where it comes to HTML. There are a bunch of other issues here debating it but basically read this if you want to know more:
https://michelf.ca/blog/2010/markdown-and-xss/

The solution is to sanitize the HTML *after* Showdown has generated it. I suggest using [sanitize-html](https://www.npmjs.com/package/sanitize-html), which is used by many and well maintained. It is as easy as:

```js
var sanitizeHtml = require('sanitize-html');
var dirty = 'some really tacky HTML';
var clean = sanitizeHtml(dirty);
```

**Comment by tivie** [comment]
Also check the wiki article about this issue
