### ISSUE TITLE
Cloudflare CDN seems to have wrong version stored for 1.8.0

### ISSUE THREAD

**Issue by udondan** [showdownjs/showdown#452]
When requesting https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.0/showdown.min.js the first line of the file tells it actually is version v 1.7.6:

```
/*! showdown v 1.7.6 - 24-10-2017 */
```

**Comment by tivie** [comment]
that's strange.

**Comment by tivie** [comment]
Published version 1.8.1 which should be available shortly in CDNjs. Please use this version (1.8.1) instead.

**Comment by udondan** [comment]
Thanks, it's available now. I'm using the github cdn, just opened the issue since I noticed.

**Comment by tivie** [comment]
I will leave the issue open in case someone else stumbles upon this
