### ISSUE TITLE
Add support for <ins>

### ISSUE THREAD

**Issue by ckoppelman** [showdownjs/showdown#455]
In some flavors of markdown, just like `~~` means `<del>`, `++` means `<ins>`

I'd like an option parallel with `strikethrough` that allows me to convert the following:

```markdown
My name is ~~Mike~~ ++John++.
```

into:

```html
<p>My name is <del>Mike</del> <ins>John</ins>.</p>
```

I believe it's fairly simple.  My lang converter to approximate this is below, but probably cloning the strikethrough parser is more robust:

```js
showdown.extension('pp-insert', function() {
  return {
    type: 'lang',
    regex: /(?<!\\)[+]{2}((?=\S).*?\S)[+]{2}/gi,
    replace: '<ins>$1</ins>'
  };
});
```

**Comment by tivie** [comment]
That is non-standard syntax, not supported in any flavor showdown supports (see [babelmark2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=My+name+is+~~Mike~~+%2B%2BJohn%2B%2B)).

As such, is better suited for an extension, namely a listener extension (you can check a working example in this [fiddle](https://jsfiddle.net/tivie/vdkegtjs/))

```js
// Extension of type listener
showdown.extension('ins', function() {
  return [{
    type: 'listener',
    listeners: {
      // the extension is called right AFTER the parser parses italicsAndBold
      // and only during span gamut
      'italicsAndBold.after': function (event, text, options, globals) {
        return text.replace(/(?:\+){2}([\s\S]+?)(?:\+){2}/g, function (wm, txt) {
          if (options.simplifiedAutoLink) {
            txt = showdown.subParser('simplifiedAutoLinks')(txt, options, globals);
          }
          return '<ins>' + txt + '</ins>'
        });
      }
    }
  }];
});
```

**Comment by ckoppelman** [comment]
I tried it out.  Works perfectly.  I understand why you'd want to limit the scope of the project.

For those who follo me, this regex works a bit better by including the last `+`'s and ensuring there's a non-whitespace character after the first `++` and before the last:

```js
/(?!\\)(?:\+){2}(?=\S)([\s\S]*?\S)(?:\+){2}(?!\+)/g
```
