### ISSUE TITLE
openLinksInNewWindow should not apply to internal anchor links (e.g. TOC links)

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#457]
Right now if you use openLinksInNewWindow, _all_ links get updated to open in a new window, including internal anchor links. This is not desirable. Please consider changing the default behavior such that internal anchor links are ignored/skipped by the openLinksInNewWindow setting. Thanks!

**Comment by tivie** [comment]
Although there isn't a perfect solution for this issue (since that would require showdown to be aware of URL context), showdown can disable target="__blank" for relative urls that start with a #.

**Comment by KirkMunro** [comment]
That's what I was looking for. I think that would be a nice improvement for openLinksInNewWindow.

**Comment by tivie** [comment]
Should be fixed now

---

>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money. Currently, we're looking to improve showdown with automated tests in all browsers and a proper domain and webpage. 500$ should be enough to to keep showdown testing framework running for a year or two.

**If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/34908) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated.**

**Comment by FreeTrade** [comment]
@tivie 

>showdown can disable target="__blank" for relative urls that start with a #.

This does not seem to apply to ghMentionsLink as at version 1.9.1
