### ISSUE TITLE
Disable block quotes

### ISSUE THREAD

**Issue by 110Percent** [showdownjs/showdown#460]
Is there a way to edit the configuration for a converter to disable the automatic generation of block quotes from `>` symbols?

**Comment by obedm503** [comment]
you can always escape the `>` with `\` http://demo.showdownjs.com/#/%3Eblock%20quote%0A%0A%5C%3Enot%20block%20quote

**Comment by tivie** [comment]
Since it's a block parser, you can always override the blockquote parser, like this (see [working fiddle](https://jsfiddle.net/tivie/kk6vLf2n/)):

```js
showdown.subParser('blockQuotes', function (text, options, globals) {
  text = globals.converter._dispatch('blockQuotes.before', text, options, globals);
  text = globals.converter._dispatch('blockQuotes.after', text, options, globals);
  return text;
});
//... more code
// initialize showdown as usual
var conv = new showdown.Converter();
```

**Comment by tivie** [comment]
---

>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money. Currently, we're looking to improve showdown with automated tests in all browsers and a proper domain and webpage. 500$ should be enough to to keep showdown testing framework running for a year or two.

**If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/34908) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated.**

**Comment by tivie** [comment]
@110Percent did this work for you?
