### ISSUE TITLE
Bold Breaking

### ISSUE THREAD

**Issue by James-Burnham** [showdownjs/showdown#461]
When using the "literalMidWordAsterisks" option, there are a few circumstances which you would want bold to maintain, but it is instead keeping the literal asterisk.

`**Bold:** vs **Bold**:`
Will appear as **Bold:** vs `**Bold**:` while a , or . after the ** will properly display as un-bolded when the word is bold. Is there a way to make non-alphanumeric characters eligible to not break bolding?

Additionally, this option breaks bolding when creating a sub-list.

```
- **Bold**
    - Tier 2
```

Will display with the asteriks unless you add a space after it, which it will then display as formatted text.
All of the above previewed on v1.8.2 [Showdown Editor](http://demo.showdownjs.com/#/**Bold%3A**%0A%0A**Bold**%3A%0A%0A**Bold**%2C%0A%0A%0A-%20**Bold**%0A%20%20%20%20-%20Tier%202)

**Comment by tivie** [comment]
Should be fixed now.

---

>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money. Currently, we're looking to improve showdown with automated tests in all browsers and a proper domain and webpage. 500$ should be enough to to keep showdown testing framework running for a year or two.

**If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/34908) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated.**

**Comment by James-Burnham** [comment]
Thanks for the quick fix! Confirmed it is working now.
