### ISSUE TITLE
Alternate numbering methods when using nested ordered lists

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#462]
Imagine you start with markdown defining two lists: one ordered, and another not.

```markdown
1. Hello.
1. World.
    1. This is nested.
        1. And this.
        1. And another.
    1. And this one.

- Hello.
- World.
    - This is nested.
        - And this.
        - And another.
    - And this one.
```

When this markdown is rendered into HTML using showdownjs, the unordered list alternates the type of bullets used in the HTML, but the ordered list always uses the same numbering method in the nested ordered lists that it used in the base ordered list.

I would like you to consider adding an option that would change this behaviour such that the first level of rendered numbering is numeric (1., 2., etc.), the second is alphabetic (e.g. a), b), etc.), and the third is roman (i., ii., iii., etc.), then cycling back to numeric again, and so on. Without this option, nested ordered lists don't render as nicely as they could/should.

**Comment by tivie** [comment]
You can easily style lists with css. [see this example fiddle](https://jsfiddle.net/tivie/m62j639s/)

```css
ol>li>ol {list-style-type: upper-roman;}
ol>li>ol>li>ol {list-style-type: lower-alpha;}
```

**Comment by KirkMunro** [comment]
Thanks @tivie, that's helpful.

**Comment by Dan-Wood** [comment]
I had this issue too, moving to Micromark fixed it unfortunately. I really liked Showdown...
