### ISSUE TITLE
Help Wanted: Integrating with Angular 5

### ISSUE THREAD

**Issue by eavestn** [showdownjs/showdown#463]
Everything is working, perfectly; however, when the DOM is rendered, the styles I would expect to be applied are not applied. Everything is styled with the default browser styles. Does your library include stylings or is just an HTML converter? 

If it _does_ include stylings, are there any known issues around Angular's treatment of DOM additions and security that would prevent your styles from being applied?

```
	private convertMarkdownIntoHtml(rawMarkdown) {
		const converter = new showdown.Converter({ tables: true });
		return converter.makeHtml(rawMarkdown);
	}

	private turnMardownIntoTemplate(mdFileLocation: string) {
		this.httpClient.get(mdFileLocation, {responseType : 'text' })
			.subscribe(function(data) {
				const html = this.convertMarkdownIntoHtml(data);
				this.markdownAsHtmlContainer.nativeElement.innerHTML = html;
			}.bind(this)
		);
	}
```

As you can see, I am not doing anything particularly spectacular.

**Comment by obedm503** [comment]
showdown does not include any styles. what are these styles you "would expect to be applied"

**Comment by tivie** [comment]
> Does your library include stylings or is just an HTML converter?

Showdown is just an html converter, no style is applied.

I really dont' know why the content is not styled. Can you reproduce the issue in a fiddle?

**Comment by eavestn** [comment]
@obedm503 none if no styles are applied. It looked from the tutorial page that markdown stylings would be applied

**Comment by eavestn** [comment]
@tivie the default browser styles are applied, of course.

**Comment by tivie** [comment]
@eavestn You mean the demo page? https://demo.showdownjs.com

**Comment by eavestn** [comment]
@tivie yeah.

**Comment by tivie** [comment]
The demo page uses foundation
