### ISSUE TITLE
italicsAndBold.after listener extension shouldn't execute inside code spans

### ISSUE THREAD

**Issue by ctsears** [showdownjs/showdown#464]
For some reason, italicsAndBold.after listener extensions are working inside code spans. The correctly do not run inside code blocks. Since italicsAndBold doesn't impact code spans, I'm not sure what's going wrong. Fiddle is here:  https://jsfiddle.net/s83o24et/11/

**Comment by tivie** [comment]
Found the issue. Code spans are not being hashed after parsing. Instead, we're only escaping "magic" markdown chars inside. Since the character + is not magic in markdown, it's not being escaped

**Comment by tivie** [comment]
@ctsears This should be fixed now. Please give it a try and tell me if it works.

**Comment by ctsears** [comment]
Working now! Thanks!
