### ISSUE TITLE
Is there a way to get auto-generated ids also on <h2>, <h3> etc?

### ISSUE THREAD

**Issue by LeaVerou** [showdownjs/showdown#467]
I looked through the options but didn't find anything.

**Comment by tivie** [comment]
What do you mean? By default, ids are added to all headings. Check [the fiddle](https://jsfiddle.net/tivie/n4vj42mq/)

**Comment by LeaVerou** [comment]
Sorry, I guess I filed this too hastily. Looks like it's something else in my codebase stripping them.
