### ISSUE TITLE
Please add this to Wiki...

### ISSUE THREAD

**Issue by ivanhjc** [showdownjs/showdown#468]
As I spent quite some time on finding how to enable tables and strikethrough options, the only places where I could find mentioning this problem is [here](https://github.com/showdownjs/showdown/wiki/Showdown-Options "Showdown Options") and [here](https://github.com/showdownjs/showdown/wiki/CLI-tool#extra-options "CLI-tool"), and after reading these I still had to meddle a bit to figure it out. So maybe this will save a little bit of someone else's time :smile: 

To enable multiple options: 
`var converter = new showdown.Converter({tables: true, strikethrough: true});`

**Comment by tivie** [comment]
It's also in the README.md (https://github.com/showdownjs/showdown#options)

**Comment by ivanhjc** [comment]
Oh don't know why I missed that. I saw this so I just googled `Showdown's API documentation` and couldn't find it anywhere :rofl: 
![default](https://user-images.githubusercontent.com/9710620/33353433-c46534b4-d4e8-11e7-9a05-f7e7502d3ed0.PNG)

**Comment by tivie** [comment]
Added this to the wiki pages: https://github.com/showdownjs/showdown/wiki/Showdown-Options

**Comment by tivie** [comment]
> ## Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at pledgie.com](https://pledgie.com/campaigns/35166.png?skin_name=chrome)](https://pledgie.com/campaigns/35166)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/35166) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by ivanhjc** [comment]
Just donated. Thanks for the good work 👍
