### ISSUE TITLE
Options for enabling spaces in link destinations?

### ISSUE THREAD

**Issue by ivanhjc** [showdownjs/showdown#469]
It seems Showdown has evolved to comply with the [CommonMark spec](http://spec.commonmark.org/0.25/#link-destination) so that spaces are not supported in link addresses anymore. As I used [1.4.2](https://github.com/showdownjs/showdown/releases/tag/1.4.2) before and it supports both spaces and `20%` in link addresses well so I sometimes just conveniently write a link like this to refer to project files: `* [A Map For Learning](A Map For Learning.html)`. I think it's better as per the prime goal of Markdown for easy reading.

**Comment by tivie** [comment]
Hello @ivanhjc 

Showdown does not follow the CommonMark spec (although if, in some instances, it does, it's just a coincidence).

The issue with URLs is that the URI spec does not allow URLs to have spaces. https://tools.ietf.org/html/rfc3986
