### ISSUE TITLE
extension is able to replace text inside code blocks

### ISSUE THREAD

**Issue by santhosh-tekuri** [showdownjs/showdown#470]
I am using https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.3/showdown.min.js

I created simple extension based on the example in wiki and registered it:

```
showdown.extension("myext", function () {
  return[{
    type: 'lang',
    regex: /markdown/g,
    replace: 'showdown'
  }];
});
```

when i convert following markdown to html:

    this is markdown paragraph
    ```
    this is markdown code block
    ```

it produces following html:
```
<p>this is showdown paragraph</p>
<pre><code>this is showdown code block
</code></pre>
```

Notice that the word "markdown" inside code block is also getting replaced with "showdown"

this is unexpected behaviour.

**Comment by santhosh-tekuri** [comment]
the same happens with inline code also:

```
`markdown`
```
converted to:
```
<code>showdown</code>
```

**Comment by tivie** [comment]
A lang extensions knows nothing about context (unless you provide it). It's run before any of the subparsers and so takes precedence over them. It's supposed to work like that or you wouldn't have a way to change code blocks, for instance.

So, for your use case, since context matter, you should use an event extension and listen to a "span" event, for instance, the `italicsAndBold.after` event. 

See an example [in this fiddle](https://jsfiddle.net/tivie/s83o24et/)



> ## Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at pledgie.com](https://pledgie.com/campaigns/35166.png?skin_name=chrome)](https://pledgie.com/campaigns/35166)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/35166) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by santhosh-tekuri** [comment]
Thanks. after changing to listener to wiki, it works as expected

Actually i followed the documentation in [wiki](https://github.com/showdownjs/showdown/wiki/Extensions). it talks about only extensions of type lang and output.

updating the wiki, will help new users

**Comment by tivie** [comment]
See #459
