### ISSUE TITLE
Have the extension for Mathjax? thanks

### ISSUE THREAD

**Issue by garyyan** [showdownjs/showdown#474]
@coreyti 
Have the extension for Mathjax? thanks

**Comment by tivie** [comment]
?

**Comment by obedm503** [comment]
well, I guess you want to be able to write math and print it nicely. then there'shttps://github.com/obedm503/showdown-katex it can print math in tex and asciimath

**Comment by garyyan** [comment]
@obedm503 
well,it is what I want,I will do a test at first,thank you very much

**Comment by garyyan** [comment]
@obedm503
After  the test,the  https://github.com/obedm503/showdown-katex  work well to me
And I find it use the `~`for katex  inline, but not the `$`,right?
thank you again

**Comment by tivie** [comment]
Closing issue
