### ISSUE TITLE
Option to recognize adjacent but separate block quotes as distinct, separate block quotes

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#477]
There are many cases where I use two distinct block quotes next to one another in markdown, with a space or blank line between them, and in these cases I always want the block quotes to be rendered as two separate block quotes. In Visual Studio Code I get this behaviour by default. In GitHub I get this behaviour by default as well. With showdownjs, however, I don't get that behaviour. Instead, the adjacent block quotes are rendered as a single block quote. I recognize that this is the default markdown behaviour; however, it would be very useful to have an option in showdownjs that makes it render block quotes separated by blank lines as separate block quotes.

e.g. I would like this:

```markdown
> # Block quote  1
>
> This is my first block quote.

> # Block quote 2
>
> This is my second block quote.
```

To render like this:

> # Block quote  1
>
> This is my first block quote.

> # Block quote 2
>
> This is my second block quote.

Instead of like this:

> # Block quote  1
>
> This is my first block quote.
>
> # Block quote 2
>
> This is my second block quote.

Thank you @tivie for everything you do with showdownjs and for considering this request. Happy Holidays!

**Comment by tivie** [comment]
Should be available in version 1.8.6

> ## Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at pledgie.com](https://pledgie.com/campaigns/35166.png?skin_name=chrome)](https://pledgie.com/campaigns/35166)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/35166) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.
