### ISSUE TITLE
Possibly Ignoring Options

### ISSUE THREAD

**Issue by ComputerCarl** [showdownjs/showdown#484]
I am using Showdown with React. When there is a domain in the text, it both displays as a link and opens in the current window.

`<div dangerouslySetInnerHTML={markdownToHtml(description)}></div>`

````js
var converter = new showdown.Converter({
  headerLevelStart: 3,
  openLinksInNewWindow: true,
  simplifiedAutoLink: false,
  emoji: true
});
export var  markdownToHtml = (markdown) => {
  console.log(converter.getOptions());
  return {__html: converter.makeHtml(markdown)}
};
````

**Comment by ComputerCarl** [comment]
I've got something else going on apparently; it didn't happen in the following code;

````js
import React, { Component } from 'react';
// import CardReveal from './CardReveal';
import MarkdownConverter from './MarkdownConverter';

class App extends Component {
  render() {
    return (
      <div className="App">
        <p>The src folder should be chock-full o gists</p>
        <div>
          <MarkdownConverter />
        </div>
      </div>
    );
  }
}

export default App;
````

**Comment by ComputerCarl** [comment]
I've got something else going on.. it didn't happen in the following component;
````js
import React from 'react';
import showdown from 'showdown';

export default () => {
    var converter = new showdown.Converter({
    headerLevelStart: 3,
    openLinksInNewWindow: true,
    simplifiedAutoLink: false,
    emoji: true
    });

    var  markdownToHtml = (markdown) => {
    console.log(converter.getOptions());
    return {__html: converter.makeHtml(markdown)}
    };
    var description = "I like the site anywhere.com. It makes me happy.";
    return (
        <div dangerouslySetInnerHTML={markdownToHtml(description)} />
    )
}
````

**Comment by ComputerCarl** [comment]
Links were cause by Disqus plugin affiliate links and VgLnk.

**Comment by tivie** [comment]
Sorry, I got lost. So, no problem with showdown?

**Comment by ComputerCarl** [comment]
No problemo.. Showdown behaving as expected!

However, i don't know if it already performs the function of markdown to plain text or I can put a feature request?

I was a little surprised there was a `makeHtml` no nothing like `makeText` so had to install `markless` package also.

**Comment by tivie** [comment]
plain text?

**Comment by ComputerCarl** [comment]
Yes.. when the markdown text is to be displayed in a snippet, or for some other such purpose, the text must be displayed without formatting.
