### ISSUE TITLE
How to custom CSS ?

### ISSUE THREAD

**Issue by iShawnWang** [showdownjs/showdown#485]
Since showdown just generate plain html, and what's the best practice to custom the appearence of generated html, such as add class and CSS.

# :D

**Comment by obedm503** [comment]
something like [picnic](https://picnicss.com/) might be useful since it doesn't require much dom manipulation adding classes like boostrap

**Comment by tivie** [comment]
You can create a custom extension that adds classes to elements, for instance.

https://github.com/showdownjs/showdown/issues/300

https://github.com/showdownjs/showdown/issues/376

https://github.com/showdownjs/showdown/wiki/Add-default-classes-for-each-HTML-element

https://github.com/showdownjs/showdown/issues/310

**Comment by iShawnWang** [comment]
Awesome, really useful ~
Thanks @tivie
