### ISSUE TITLE
need to render html without paragraph tags

### ISSUE THREAD

**Issue by savsharma2** [showdownjs/showdown#493]
need to render html without paragraph tags.

**Comment by tivie** [comment]
Showdown does not allow for selective parsing. You can, however, create an extension that replaces `<p>` tags with something else (or remove them entirely).

**Comment by cori** [comment]
I was working on solving a different problem and stumbled across a possible solution for this one:

```
var noMorePsExt = {
  type: 'output',
  filter: function(text, converter) {
    var re = /<\/?p[^>]*>/ig;
    text = text.replace(re, '');
    return text;
  }
};

const converter = new showdown.Converter({extensions: [noMorePsExt]});
```
then the rest of your code.
