### ISSUE TITLE
Can you please fix demo.showdownjs.com so that the rendered view doesn't bleed outside of the browser?

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#500]
In demo.showdownjs.com, the rendered view runs off of the right side of the browser. This makes it difficult to test/troubleshoot with because you can't see all the rendering without manually breaking up paragraphs.

@tivie, can you please fix demo.showdownjs.com so that the rendered view on the right fits in the browser window?

**Comment by tivie** [comment]
Please open this issue in the showdownjs demo repository

**Comment by tivie** [comment]
Oh @KirkMunro and to "fix" that issue, just click in the 3 bars 2 times.
