### ISSUE TITLE
TypeError: text.replace is not a function

### ISSUE THREAD

**Issue by DearVikki** [showdownjs/showdown#501]
When I use showdown under node environment, an error is emitted as _'TypeError: text.replace is not a function at showdown.Converter.makeHtml '_. 

However, showdown works totally fine under web environment with the same raw content. 

Does anyone has any clue that why this happens?  

---------------
O I see, since showdown used 'document.createElement()' and there's no 'document' exists under node...so is it mean that there's no way to use showdown in my situation? ◔‸◔

**Comment by tivie** [comment]
what version are you using?

**Comment by DearVikki** [comment]
1.8.6...Oh, I should be better to update it to the latest version and try again!

**Comment by tivie** [comment]
1.8.6 is the latest version and works fine under node.

**Comment by DearVikki** [comment]
Yes it works totally fine!!..Sorry its all my fault.. I accidentally passed in an object rather than a string.. : (

**Comment by stephanbogner** [comment]
**If somebody stumbles upon this:**
I accidentally loaded an md-file using `fs.readFileSync( filePath )`, which makes it return a buffer and not a string.
Adding the encoding makes it work: `fs.readFileSync( filePath , 'utf-8')`
