### ISSUE TITLE
Update donation link

### ISSUE THREAD

**Issue by raisen** [showdownjs/showdown#507]
[Pledgie](http://pledgie.com/) states they ceased operations. The donation link on the [README](https://github.com/showdownjs/showdown/blob/master/README.md) points to a Pledgie campaign.

**Comment by tivie** [comment]
thanks. We're currently looking into alternatives for donations.

**Comment by tivie** [comment]
In the meanwhile, donations can be done directly through paypal https://www.paypal.me/tiviesantos

**Comment by tivie** [comment]
I've just created a patreon page at https://www.patreon.com/showdownjs
