### ISSUE TITLE
the "[^1]:a"  been coverted to nothing

### ISSUE THREAD

**Issue by garyyan** [showdownjs/showdown#510]
showdown version:showdown v 1.8.6 - 22-12-2017 
and code as below
```
var converter =  new showdown.Converter();
var text      = '[^1]:a';
var html      = converter.makeHtml(text);
```
but find the output `html=""`
and I update to `var text      = '[^1]a';`,
and find the output is `"<p>[^1]a</p>"`,which is correct

**Comment by tivie** [comment]
verified

**Comment by tivie** [comment]
This is weird. Every parser in babelmark produces empty string https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%5E1%5D%3Aa

**Comment by tivie** [comment]
After talking with some markdown experts, that is the intended behavior. The commonmark spec is explicit in this regard: https://spec.commonmark.org/0.28/#link-reference-definitions

So it's not a bug, but actually the intended behavior. If you wish to write that specific sequence of characters, you need to escape the opening square brackets: `\[^1]:a`
