### ISSUE TITLE
Dates formatted 2018_04_09 converted to 2018<em>04</em>09

### ISSUE THREAD

**Issue by abuyoyo** [showdownjs/showdown#514]
Description:
I'm not sure this is expected behaviour.

Input:
`2018_04_09`

Expected output:
`2018_04_09`

Actual output:
`2018<em>04</em>09`

**Comment by obedm503** [comment]
you need to set `literalMidWordUnderscores` option when creating the converter
```js
var converter = new showdown.Converter({ literalMidWordUnderscores: true });
```

**Comment by abuyoyo** [comment]
:)
Thanks!
I shoulda figured this was a common issue..

**Comment by obedm503** [comment]
great!
@abuyoyo can you close the issue since this was resolved? thanks
