### ISSUE TITLE
how to set hyperlink have Underline?

### ISSUE THREAD

**Issue by VinceXie** [showdownjs/showdown#515]
markdown text : 
```
[https://github.com/mekentosj/oauth2-example](https://github.com/mekentosj/oauth2-example)
```

i want to look like this：
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fq7pcoloimj30ki02k0sw.jpg)

**Comment by tivie** [comment]
You need to use css to style it

**Comment by obedm503** [comment]
maybe wrap it in `<u></u>` tags, but this is a bad practice. even mdn says

>[This element used to be called the "Underline" element in older versions of HTML, and is still sometimes misused in this way. To underline text, you should instead apply a style that includes the CSS text-decoration property set to "underline".](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u)
