### ISSUE TITLE
How to convert html content into markdown content?

### ISSUE THREAD

**Issue by Savan-Karathiya** [showdownjs/showdown#516]
I am using makeHTML() for convert markdown content into HTML.
But also I want to convert HTML into markdown.
Is there any function available for it?

**Comment by Slapbox** [comment]
I don't think it's built into this package (could be totally mistaken.)

For this I'm using https://github.com/domchristie/turndown

**Comment by Savan-Karathiya** [comment]
@Slapbox Thanks for the help.

**Comment by tivie** [comment]
A reverse conversion tool will be available in version 2.0.0-alpha
