### ISSUE TITLE
Please support latex and graphviz

### ISSUE THREAD

**Issue by parthi2929** [showdownjs/showdown#517]
Hi 

This is a great tool. Thank you very much firstly. 

Can you also please support latex and graphviz? 

Latex is awesome to write formula and graphviz to draw diagrams both programmatically. The rendered would be image. There are CDN's available. You could just use those js to render. Please please implement them. 

latex: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML
graphviz: https://cdnjs.cloudflare.com/ajax/libs/viz.js/1.3.0/viz.js

**Comment by obedm503** [comment]
you could use [showdown-katex](https://github.com/obedm503/showdown-katex) to display both asciimath and latex. and i'm sure an extension for graphviz wouldn't be too difficult for you to write

**Comment by tivie** [comment]
You can use extensions to accomplish that.

**Comment by tbhaxor** [comment]
The extension is not much flexible
