### ISSUE TITLE
Missing letter

### ISSUE THREAD

**Issue by su8** [showdownjs/showdown#527]
Hello there is a missing letter **r** in the following sentence here - 
https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)

>situation you application may face

**Comment by ozzywalsh** [comment]
I have fixed the typo. Could the maintainers merge my changes in. I couldn't make a pull request against the wiki, nor fork it. So I cloned it and pushed to my own remote.

[https://github.com/ozzywalsh/showdown-wiki/](https://github.com/ozzywalsh/showdown-wiki/)

**Comment by tivie** [comment]
fixed. Thank you very much @ozzywalsh
