### ISSUE TITLE
Add CLI example to Extensions.md

### ISSUE THREAD

**Issue by leon-vv** [showdownjs/showdown#533]
Hello, thanks for sharing this project!

I would like to propose an addition to the Extensions.md file of the wiki. It would be helpful to show that you can load extensions while using the CLI tool. So beneath the `Client-side Extension Usage` and `Server-side Extension Usage` there could be a section:
```markdown
# CLI Extension Usage

Extensions can be loaded while using the CLI tool using the `-e` flag.
` ``
showdown -e twitter -i foo.md -o bar.html
` ``
```
I did not find a way to edit the wiki myself (if this is not possible, why is it called a wiki? :thinking:)

Cheers!

**Comment by tivie** [comment]
> I did not find a way to edit the wiki myself (if this is not possible, why is it called a wiki? 🤔)

You can, of course, edit the wiki. You just have to clone `https://github.com/showdownjs/showdown.wiki.git` and make a pull request.


That is already documented in: https://github.com/showdownjs/showdown/wiki/CLI-tool#option--e--extensions

However, I added what you proposed to the documentation. :)
