### ISSUE TITLE
Multiple parentheses () in url link is not parsed correctly

### ISSUE THREAD

**Issue by fbucek** [showdownjs/showdown#534]
**Description:** 

Url link with multiple () in url path does not work correctly. Single parentheses () in url is parsed correctly. 

**Input**

```
[Jira issue filter](https://bugreports.qt.io/browse/QTBUG-68277?jql=project%20in%20(QTBUG%2C%20QBS)%20AND%20issuetype%20in%20(Bug%2C%20Epic)%20AND%20status%20%3D%20Open)
```

**Expected output** 

Basically what Github does, Github parse this link correctly: [Jira issue filter](https://bugreports.qt.io/browse/QTBUG-68277?jql=project%20in%20(QTBUG%2C%20QBS)%20AND%20issuetype%20in%20(Bug%2C%20Epic)%20AND%20status%20%3D%20Open)

**Actual output**:  

```
Jira issue filter%20AND%20status%20%3D%20Open)
```

Results form [Showdown demo](http://demo.showdownjs.com/)

**Comment by tivie** [comment]
Confirmed. Related to other link parsed bugs.

**Comment by tivie** [comment]
#355

**Comment by tivie** [comment]
Should be fixed now.

---

> ### Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at paypal.com](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/tiviesantos)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate ~~[through Pledgie](https://pledgie.com/campaigns/35166) or~~ directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by RushikeshPatange** [comment]
@fbucek It appears that the issue you're experiencing is still unresolved. I'm facing a similar problem in my case #986 . During my exploration, I discovered that using a backslash `\` before the closing parenthesis (the inner ones) provides the correct expected result. 

So, for instance, your input could be modified as follows:
> Please take a note on `\` before closing parenthesis (the inner ones) 👀
## Input
```
[Jira issue filter](https://bugreports.qt.io/browse/QTBUG-68277?jql=project%20in%20(QTBUG%2C%20QBS\)%20AND%20issuetype%20in%20(Bug%2C%20Epic)%20AND%20status%20%3D%20Open)
```
----
```
[Jira issue filter](https://bugreports.qt.io/browse/QTBUG-68277?jql=project%20in%20(QTBUG%2C%20QBS)%20AND%20issuetype%20in%20(Bug%2C%20Epic\)%20AND%20status%20%3D%20Open)
```
## Result
[Jira issue filter](https://bugreports.qt.io/browse/QTBUG-68277?jql=project%20in%20(QTBUG%2C%20QBS)%20AND%20issuetype%20in%20(Bug%2C%20Epic)%20AND%20status%20%3D%20Open)

I have tried it with **[Live Demo](http://demo.showdownjs.com/#!/%5BJira%20issue%20filter%20case%201%5D(https%3A%2F%2Fbugreports.qt.io%2Fbrowse%2FQTBUG-68277%3Fjql%3Dproject%2520in%2520(QTBUG%252C%2520QBS%5C)%2520AND%2520issuetype%2520in%2520(Bug%252C%2520Epic)%2520AND%2520status%2520%253D%2520Open)%0A%0A---%0A%0A%5BJira%20issue%20filter%20case%202%5D(https%3A%2F%2Fbugreports.qt.io%2Fbrowse%2FQTBUG-68277%3Fjql%3Dproject%2520in%2520(QTBUG%252C%2520QBS)%2520AND%2520issuetype%2520in%2520(Bug%252C%2520Epic%5C)%2520AND%2520status%2520%253D%2520Open))**, PTAL @fbucek and @tivie.Thanks !
