### ISSUE TITLE
question: how to enable code blocks

### ISSUE THREAD

**Issue by al-k21** [showdownjs/showdown#538]
I am unable to see code blocks:
![image](https://user-images.githubusercontent.com/29542357/40428814-0bdf09c0-5e99-11e8-8329-e5409e879f05.png)

Compared to the demo (http://demo.showdownjs.com/):
![image](https://user-images.githubusercontent.com/29542357/40428963-5fe53eae-5e99-11e8-8799-4bb469995cab.png)

## How to reproduce:
1. `npm i showdown`
2. Run `node convert.js`, where `convert.js` is:
```
let fs        = require('fs'),
    showdown  = require('showdown'),
    converter = new showdown.Converter(),
    text      = fs.readFileSync('README.md', 'utf8'),
    html      = converter.makeHtml(text);
fs.writeFileSync('README.html', html);
```
This will convert the `README.md` to `README.html`
3. Open the `README.html`

Am I missing anything obvious?

**Comment by al-k21** [comment]
HTML file has code tags around the code (e.g):
```
<h2 id="bower">Bower</h2>
<pre><code>bower install showdown
</code></pre>
```
Could someone help resolve this?

**Comment by obedm503** [comment]
Make sure to enable ghCodeBlocks. You can read the rest of the docs in the wiki https://github.com/showdownjs/showdown/wiki/Showdown-options

**Comment by al-k21** [comment]
> **NOTE: ghCodeBlocks are enabled by default since version 0.3.1**

According to [Showdown-options#ghcodeblocks](https://github.com/showdownjs/showdown/wiki/Showdown-options#ghcodeblocks, I am on `"^1.8.6"`.

Even after I set the option through the constructor `let converter = new showdown.Converter({'ghCodeBlocks': true})` I am still not see code blocks.

By printing the options I get:
```js
{ omitExtraWLInCodeBlocks: false,
  noHeaderId: false,
  prefixHeaderId: false,
  rawPrefixHeaderId: false,
  ghCompatibleHeaderId: false,
  rawHeaderId: false,
  headerLevelStart: false,
  parseImgDimensions: false,
  simplifiedAutoLink: false,
  excludeTrailingPunctuationFromURLs: false,
  literalMidWordUnderscores: false,
  literalMidWordAsterisks: false,
  strikethrough: false,
  tables: false,
  tablesHeaderId: false,

  ghCodeBlocks: true,

  tasklists: false,
  smoothLivePreview: false,
  smartIndentationFix: false,
  disableForced4SpacesIndentedSublists: false,
  simpleLineBreaks: false,
  requireSpaceBeforeHeadingText: false,
  ghMentions: false,
  ghMentionsLink: 'https://github.com/{u}',
  encodeEmails: true,
  openLinksInNewWindow: false,
  backslashEscapesHTMLTags: false,
  emoji: false,
  underline: false,
  completeHTMLDocument: false,
  metadata: false,
  splitAdjacentBlockquotes: false }
```

**Comment by tivie** [comment]
Please share the output code.
From the images you posted, it seems showdown is working properly. The only difference is in styling.

**Comment by tivie** [comment]
No styling is provided. You must add it yourself. In the demo we are using foundation

**Comment by NE-SmallTown** [comment]
For me, the easiestway to solve this is to inspect `http://demo.showdownjs.com/` and then search/find and the copy the related code about styling
