### ISSUE TITLE
Add custom class from markdown

### ISSUE THREAD

**Issue by ManzDev** [showdownjs/showdown#542]
Markdown extra support custom classes:
https://michelf.ca/projects/php-markdown/extra/#spe-attr

For example:
```## The Site ##    {.main}```

Showdown can made this?

**Comment by Netsaver** [comment]
I would add also ID & classes for inline elements, with a syntax similar to link's one:
`[text to annotate]{#ref1 .annotated 'mytip'}`
If implemented at least for links I would add empty reference:
`[text to annotate](){#ref1 .annotated 'mytip'}`, but I should capture it via js to convert it to span before rendering... it would be better having it inside extension.

regards,
Netsaver

**Comment by tivie** [comment]
This can be easily accomplished by an extension

**Comment by bw1984** [comment]
any chance of pointing me in the right direction in terms of regex? ive read the documentation for creating an extension and have several working examples but im struggling to fetch the params from within the curly braces and "inject" them backwards into the blockquote tag

**Comment by joewagner** [comment]
Does anyone know of an extension that does this?

**Comment by hieunc229** [comment]
For anyone who is still looking, here is an example that you can use `[.class]` to add a class.

```js
// Declare extension
var customClassExt = {
    type: 'output',
    filter: function (text: string) {
        return text
            // Add class for list (ol, ul)
            .replace(/<p>\[\.([a-z0-9A-Z\s]+)\]<\/p>[\n]?<(.+)>/g, `<$2 class="$1">`)

            // Add class for other blocks
            .replace(/<(.+)>\[\.([a-z0-9A-Z\s]+)\]/g, `<$1 class="$2">`);
    }
};
// Add extension to converter
converter.addExtension(customClassExt);
```

**Note: When adding a class to a list, you need a new line after `[.class]`. There is no new line break needed for other tags**
Here is a markdown example:

```
#[.header] Content title
[.pTag]Content description

[.list]
1. Item 1
2. Item 2
```

Results
```html
<h1 id="headercontenttitle" class="header">Content title</h1>
<p class="pTag">Content description</p>
<ol class="list">
    <li>Item 1</li>
    <li>Item 2</li>
</ol>
```

**Comment by alanfluff** [comment]
[This](https://github.com/showdownjs/showdown/issues/542#issuecomment-660437310) is exactly what I want - thank you.

But I can't get it to work(?); I have this

```
<script src="md.js"></script>
<script src="md_extensions.js"></script>
```

where `md_extensions.js` holds [this exact code](https://github.com/showdownjs/showdown/issues/542#issuecomment-660437310), 
and the console produces this if the `md_extensions.js` line is uncommented:

> Uncaught SyntaxError: missing ) after formal parameters

I cannot see any obvious missing brackets and am a bit stuck. Any clues would be most appreciated : ) Thanks
