### ISSUE TITLE
Support having multiple files put as input to one big file from CLI

### ISSUE THREAD

**Issue by simonv3** [showdownjs/showdown#543]
Hey all, 

I was wondering if it's possible to input multiple files as input to the CLI and have them be spit out as one .html file. 

It looks like this isn't supported at the moment from the CLI code. What would be involved in making that work? 

Thanks for this great tool!

**Comment by tivie** [comment]
Shouldn't be too hard to implement. Although, it's also trivial to actually concatenate the files prior to feeding them to showdown:

**unix**

```batch
cat file1.md file2.md | showdown ...
```

**windows**

```cmd
type file1.md file2.md | showdown ...
```
