### ISSUE TITLE
literalMidWordUnderscores causes full sentences to be bolded

### ISSUE THREAD

**Issue by rachel-church** [showdownjs/showdown#544]
I would expect the behavior of `literalMidWordUnderscores` to only affect underscores attached to non-space characters.

Example:
`some text with__underscores__in middle` where `__` is used without spaces between words.

Actual Behavior:
If `literalMidWordUnderscores` is true then all text between two separate bolded words gets bolded.

`__Once upon a time__, there was a little girl named __Goldilocks__.`
Expected: __Once upon a time__, there was a little girl named __Goldilocks__.

<img width="1621" alt="screen shot 2018-06-01 at 9 28 56 am" src="https://user-images.githubusercontent.com/30054943/40852148-5bd38dde-657e-11e8-8da8-f843b1061153.png">

**Comment by tivie** [comment]
bug introduced in 1.6.4

__Once upon a time__, there was a little girl named __Goldilocks__.
