### ISSUE TITLE
Spaces between curly and square brackets in urls should not be ignored

### ISSUE THREAD

**Issue by throwable-one** [showdownjs/showdown#545]
Following code is incorrect and should not be coverted to url, and it is not converted to url by any implementation except showdown because there is a space between ``]`` and ``(``

[http://ya.ru] (http://ya.ru)

**Comment by tivie** [comment]
https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhttp%3A%2F%2Fya.ru%5D+(http%3A%2F%2Fya.ru)


[Markdown original spec allows spaces or newlines between brackets.](https://daringfireball.net/projects/markdown/syntax#link)
