### ISSUE TITLE
anchors and images of subParser are errors when they are specific strings

### ISSUE THREAD

**Issue by uedy** [showdownjs/showdown#548]
An error occurred
```
[constructor]()
[__proto__]()
```
an error is emitted as  `Uncaught TypeError: url.replace is not a function`

Cause: 
```     
showdown/src/subParsers/makehtml/anchors.js: L.25~30 
if (!showdown.helper.isUndefined(globals.gUrls[linkId])) {
  url = globals.gUrls[linkId];
  if (!showdown.helper.isUndefined(globals.gTitles[linkId])) {
    title = globals.gTitles[linkId];
  }
}
```
When `globals.gUrls` is Object, `globals.gUrls.constructor` return  functions. for that reason `showdown.helper.isUndefined` returns false.
At that time url becomes functions.
The result is this.

**Comment by tivie** [comment]
Well caught. We will need to revamp the internals a bit. I believe this happens with other javascript "magic" words.

**Comment by level420** [comment]
@tivie any news on when this will be solved?

**Comment by Strohgelaender** [comment]
@SyntaxRules You wrote in 833 that we can mention you on issues you may have missed. I just encountered this issue in a project, could you have a look at this?

**Comment by SyntaxRules** [comment]
Recreated on 2.0.0-alpha. Error is the same as above. Failing test:
`#548.error-when-using-javascript-names.md`
```
[constructor]()
[__proto__]()
```

`#548.error-when-using-javascript-names.html`
```
<p><a href="">constructor</a></p>
<p><a href="">__proto__</a></p>
```

**Comment by SyntaxRules** [comment]
There is a released issue where empty links are not kept as links: https://github.com/showdownjs/showdown/issues/820

**Comment by SyntaxRules** [comment]
This is fixed in the master branch. It unfortunately, required a big re-write. so you will have to wait for 3.0.0 for it to be resolved.
