### ISSUE TITLE
Does showdown has Sanitizer like Pagedown has?

### ISSUE THREAD

**Issue by rebootcode** [showdownjs/showdown#555]
Pagedown fork of showdown has sanitizer to sanitize xss or malicious tags - https://github.com/StackExchange/pagedown/blob/master/Markdown.Sanitizer.js

Does showdown has any? 

It is crucial for user generated markdown content.

**Comment by tivie** [comment]
> Showdown tries to convert the input text as closely as possible, without any concerns for XSS attacks or malicious intent. So, the basic rules are:
> - removing HTML entities from markdown does not prevent XSS. Markdown syntax can generate XSS attacks.
> - XSS filtering should be done AFTER Showdown has processed any input, not before or during. If you filter before, it’ll break some of Markdown’s features and will leave security holes.
> - perform the necessary filtering server-side, not client side. XSS filtering libraries are useful but shouldn't be used blindly.



https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)

**Comment by Llorx** [comment]
> > Showdown tries to convert the input text as closely as possible, without any concerns for XSS attacks or malicious intent. So, the basic rules are:
> > 
> > * removing HTML entities from markdown does not prevent XSS. Markdown syntax can generate XSS attacks.
> > * XSS filtering should be done AFTER Showdown has processed any input, not before or during. If you filter before, it’ll break some of Markdown’s features and will leave security holes.
> > * perform the necessary filtering server-side, not client side. XSS filtering libraries are useful but shouldn't be used blindly.
> 
> https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)

But it doesn't say "how to mitigate it". It just tells you what are *some* of the problems. When you finish reading it, you are still with the same problem with no solution but "you have to mitigate it somehow, but not this way, neither this way".
