### ISSUE TITLE
excludeTrailingPunctuationFromURLs should still convert "Wikipedia-style" brackets

### ISSUE THREAD

**Issue by rugk** [showdownjs/showdown#560]
## Expected
(using GitHub as a live examples, where it is done correctly)

* (This link may have something to do with a sentence: http://foo.com/blah_blah_wikipedia)
* This does not, but it's better to not link the `)` anyway: http://foo.com/blah_blah_wikipedia)
* But these are well-known Wikipedia links: http://foo.com/blah_blah_(wikipedia)

In short: It should consider brackets correctly as "Wikipedia-style" if they previously appeared in the link itself.

## What happens

When `excludeTrailingPunctuationFromURLs` is enabled, it actually _never_ considers a trailing `)` (or similar) a link.  

v1.8.6

**Comment by tivie** [comment]
Yes, it's a known issue. And its a hard problem to tackle.

Related #355

**Comment by tivie** [comment]
Should be fixed now
