### ISSUE TITLE
Clarify that the latest release does not support HTML->MD

### ISSUE THREAD

**Issue by svarlamov** [showdownjs/showdown#563]
The description of this project reads "A bidirectional MD to HTML to MD converter written in Javascript" and that is very misleading at this point given that the HTML to MD feature is not actually shipping (at least yet) in the npm package...

I believe it would be kind to the user to add a prominent note about that in the README...

**Comment by tivie** [comment]
The last NPM package (v1.8.6) does not support MD->HTML conversion. But the readme for that version (that figures in the NPM) does not state that. 

The current master / develop branches (which tag for v2.0.0-alpha1, not released yet) do support MD to HTML conversion.

**Comment by tivie** [comment]
Version 1.9.0 was released today and add an experimental feature that supports Markdown to HTML conversion.

> ## Donate
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Patreon](https://patreon.com/showdownjs) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.
