### ISSUE TITLE
How to escape special HTML-Chars like < and >

### ISSUE THREAD

**Issue by LeJared** [showdownjs/showdown#570]
If I write text like this in markdown:
``It is true that a<b and b>a, so lorem ipsum dolor sit.``

then pass it through showdown.js and render the output as html than the result shown by the browser is:
``It is true that aa, so lorem ipsum dolor sit.``

This is, because the browser handles ``<b and b>`` as an HTML-Tag. I down't want that. I want all the text outputed. So how do I escape ``<`` and ``>`` and ``&`` as ``&gt;`` and so on, so they don't get parsed to html by the browser?

Unfortunately I can not apply escaping on the input because showdown.js than will double encode those entities in all code-blocks.

**Comment by LeJared** [comment]
Well, that's not very convenient since it requires to change all our MD files. The second option even applies visible changes to the content, which is not allowed.

Is there any option planed for future releases to enable escaping of those special chars?

**Comment by tivie** [comment]
@LeJared Closing issue as no update was given. If you feel you still need help, feel free to reopen the issue.
