### ISSUE TITLE
Passing variable into Extension

### ISSUE THREAD

**Issue by toddb** [showdownjs/showdown#58]
I believe I have the need for variables to be passed into extensions. Please correct me if I am not thinking about the solution correctly.

My scenario is tagging a piece of content that will be excluded/included at compile time. I know that I could hide information via classes but I need the content not to be compiled in. This is a well known technique by technical writers for single sourcing documentation (for example in DocBook using attributes, eg revision, condition).

In my overly simple example, I want to only include the content when `condition='a'`. `a` is obviously the value that I want to hand in at compile time to base the exclusion on. So, in the code below, `a` is hardcoded but I would like to pass it in - suggestion below. At this stage, let's not worry about it being in html.

*Extension*
````javascript
function(converter) {
        return [
            { type: 'output', filter: function(source){
                var regex = /<\w+\s+(condition)='a'.*?>(.*?)<\/.*?>/gmi;
                return source.replace(regex, "");
            }}
        ];
    };
````

*Markdown*
````md
a<span condition='a'>tagging</span>
````

*Compiled to HTML*
````html
<p>a</p>
````

Would I be thinking about it wrong to want `options` as a second parameter? 

````javascript
var options = { condition: 'a' };
var converter = new Showdown.converter({ extensions: [mine], options });
````
*Extension: mine*
````javascript
function(converter, options) {
        return [
            { type: 'output', filter: function(source){
                console.log(options.condition);
                return source;
            }}
        ];
    };
````

**Comment by pdeschen** [comment]
That would make a nice addition. options could follow some namespace within the options hash such as 
```
{
  extension1: {
    optionA: 'foo',
    optionB: 'bar'
  }
  ...
}
```

**Comment by tivie** [comment]
Feature added in 33f64f60c94c561776c848c375fa49b19d6c3883

The new extension mechanism passes the full options object to extensions. So you can do something like this:
```js
var options = { 
    extensions: [mine],
    condition: 'a'
 },
    converter = new showdown.Converter(options);
```

and retrieve `conditions: a` from within the extension
