### ISSUE TITLE
HTML to Markdown (MD)

### ISSUE THREAD

**Issue by dace** [showdownjs/showdown#582]
Thanks for all the great work. 

The repo describes showdown as "A bidirectional MD to HTML to MD converter written in Javascript ", but I can't find how to convert HTML to MD. Is this supported? I can't seem to find it in the documentation. 

Thank you!

**Comment by tivie** [comment]
HTML to MD converter is a new feature, available only in master branch. The documentation hasn't been written yet.

To use it you can clone the master branch and use `converter.makeMarkdown(htmlText)`

**Comment by maciej-kolodziejczak** [comment]
@tivie After cloning a master brach I get a `Module not found: Error: Can't resolve 'tls' in [...]/node_modules/tunnel-agent` error. Any clues?

**Comment by andosteinmetz** [comment]
@maciej-kolodziejczak `cd` into the `showdown` directory and `npm install`

**Comment by mattkwiecien** [comment]
@tivie solved this in https://github.com/showdownjs/showdown/commit/e4b0e697243f2d8b0a604eb688d08938a0e7acbb (issue closed here https://github.com/showdownjs/showdown/issues/233#event-1958639417)

and this issue can probably also be closed.

**Comment by verheyenkoen** [comment]
Is there a way to use this in Node.js, as this seems to be using the window object?

**Comment by ilyaskarim** [comment]
I am late here but with an answer:

```javascript
const converter = new showdown.Converter();
converter.makeHtml(__YOUR_MARKDOWN)
converter.makeMarkdown(__YOUR_HTML)
```

**Comment by sojs-coder** [comment]
I tried using the `converter.makeMarkdown()` in my code.. but it throws the error `window is not defined`. 
I am in a node enviroment.
Is there some way to do the same but in node?

**Comment by karthik2206** [comment]
I am facing the `window is not defined` error too when I am using converter.makeMarkdown(). Again in a node environment.

**Comment by cchambers** [comment]
What I've discovered is that it does work but only if everything you're trying to convert is at the top level. 

For instance, this will just return the HTML:  
```
<div>
  <h2>some title</h2>
  <p>some text</p>
</div>
```

Whereas the following returns markdown:  
```
<h2>some title</h2>
<p>some text</p>
```

**Comment by prashantbhudwal** [comment]
On the backend, you need to pass the DOM parser. According to the docs of the function.

(method) Showdown.Converter.makeMarkdown(src: string, HTMLParser?: HTMLDocument | undefined): string
Converts an HTML string into a markdown string.

@param src — The input text (HTML)

@param HTMLParser — A WHATWG DOM and HTML parser, such as JSDOM. If none is supplied, window.document will be used.

@returns — The output markdown.


Example. This works on node.
`ts
const convertor = new showdown.Converter();
    const dom = new JSDOM(result.value);
    console.log("Parsing HTML");
    const parsedHTML = dom.window.document;
    const markdown = convertor.makeMarkdown(result.value, parsedHTML);
    console.log("Parsed markdown", markdown);
    
    `

**Comment by meAyushSharma** [comment]
> On the backend, you need to pass the DOM parser. According to the docs of the function.
> 
> (method) Showdown.Converter.makeMarkdown(src: string, HTMLParser?: HTMLDocument | undefined): string Converts an HTML string into a markdown string.
> 
> @param src — The input text (HTML)
> 
> @param HTMLParser — A WHATWG DOM and HTML parser, such as JSDOM. If none is supplied, window.document will be used.
> 
> @returns — The output markdown.
> 
> Example. This works on node.
> 
> ```ts
> const convertor = new showdown.Converter();
>     const dom = new JSDOM(result.value);
>     console.log("Parsing HTML");
>     const parsedHTML = dom.window.document;
>     const markdown = convertor.makeMarkdown(result.value, parsedHTML);
>     console.log("Parsed markdown", markdown);
> ```

Thanks it helped!

**Comment by gerardmarquinarubio** [comment]
> What I've discovered is that it does work (at least on the frontend) but only if everything you're trying to convert is at the top level.
> 
> For instance, this will just return the HTML:
> 
> ```
> <div>
>   <h2>some title</h2>
>   <p>some text</p>
> </div>
> ```
> 
> Whereas the following returns markdown:
> 
> ```
> <h2>some title</h2>
> <p>some text</p>
> ```

Can confirm, even after correctly invoking everything in the nodejs environment the makeMarkdown function is still pretty useless as it won't do much at converting html documents with nested tags...

**Comment by TheDogHusky** [comment]
> Frontend has a window object, back end does not. So, on the backend, you need to pass the DOM parser. This will help in parsing your HTML to markdown.
> 
> According to the docs of the function:
> 
> (method) Showdown.Converter.makeMarkdown(src: string, HTMLParser?: HTMLDocument | undefined): string Converts an HTML string into a markdown string.
> 
> [@param](https://github.com/param) src — The input text (HTML)
> 
> [@param](https://github.com/param) HTMLParser — A WHATWG DOM and HTML parser, such as JSDOM. If none is supplied, window.document will be used.
> 
> [@returns](https://github.com/returns) — The output markdown.
> 
> Example. This works on node.
> 
> const convertor = new showdown.Converter();
>     const dom = new JSDOM(result.value);
>     console.log("Parsing HTML");
>     const parsedHTML = dom.window.document;
>     const markdown = convertor.makeMarkdown(result.value, parsedHTML);
>     console.log("Parsed markdown", markdown);

Hey!

For some reason I run into weird issues with this setup.

Here is a reproductible example on showdown 2.1.0:
```ts
import showdown from "showdown";
import { JSDOM } from "jsdom";

/**
 * The converter used across all the app
 */
export const converter = new showdown.Converter({
    simplifiedAutoLink: true,
    headerLevelStart: 1,
    strikethrough: true,
    tasklists: false,
    tables: false,
    simpleLineBreaks: true,
    ghMentions: false,
    openLinksInNewWindow: true,
    emoji: true
});

const html = `<h1>Hello!</h1>
<p>This is a test <br /> say hello!</p>`;
const dom = new JSDOM(html);
const document = dom.window.document;
const markdown = converter.makeMarkdown(html, document);
console.log(markdown);
```

What is weird is that the output on the console is this:
```
# Hello!

This is a test <br>

 say hello!
```

I have so many questions on why does it does this. It keep <br>?
Add random spaces in new lines? (look at "say hello", there is a space before for some reason)

Can someone help?
