### ISSUE TITLE
getDefaultOpts is not defined

### ISSUE THREAD

**Issue by bkuhl** [showdownjs/showdown#591]
I'm attempting to import this library into a VueJS component and running into an unexpected error.  Perhaps I'm doing this wrong?

My VueJS component contains `import showdown from 'showdown/src/showdown` alongside other imports that are loaded correctly.  When I run my component I get the error:

```
showdown.js?25ac:9 Uncaught ReferenceError: getDefaultOpts is not defined
    at eval (showdown.js?25ac:9)
    at Object../node_modules/showdown/src/showdown.js (app.js?id=3655585264ebf1a5f704:1956)
    at __webpack_require__ (app.js?id=3655585264ebf1a5f704:20)
```

I'm attempting to use `showdown` like:

```
                converter: (function () {
                    return new showdown.Converter({
                        openLinksInNewWindow: true,
                    });
                })()
```

Then to use that dependency... 

```
console.log(this.converter.makeHtml(this.body), this.body); // throws the error
```

I'm no expert in modern JS practices.  What am I doing wrong when using this library to trigger this error?

**Comment by tivie** [comment]
The error is here:

> `at Object../node_modules/showdown/src/showdown.js`

You cannot import directly from the src directory. You need to import from the dist directory, where all library files are concatenated.

**Comment by bkuhl** [comment]
Yep, thanks!
