### ISSUE TITLE
Adjust tasklist HTML

### ISSUE THREAD

**Issue by asbjornu** [showdownjs/showdown#593]
When converting Markdown to HTML, I would like to adjust the resulting HTML so that the `<input type="checkbox">` is not `disabled`. Is it possible to plug into `showdown.subParser('makehtml.lists', ...)` in any way to accomplish this?

**Comment by asbjornu** [comment]
Great! So to create an output extension, I just do something like this?

```javascript
var taskListEnablerExtension = function () {
  return [{
    type: 'output',
    regex: /disabled="disabled"/g,
    replace: ''
  }];
}

var converter = new showdown.Converter({ extensions: ['taskListEnablerExtension'] });
```

**Comment by tivie** [comment]
Yes. I would probably add more context to the regex, just to make sure only tasklists are affected. Something like

    regex: /<input type="checkbox" disabled(?:="disabled")?/,
    replace: '<input type="checkbox"'

**Comment by tivie** [comment]
@asbjornu Did you manage to work this out?

**Comment by asbjornu** [comment]
@tivie, no, I've not gotten this to work yet. I've inspected the resulting HTML and it looks like this:

```html
<li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled="" style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;" checked=""> Checked</li>
```

The following extension does not seem to match anything:

```js
var taskListEnablerExtension = function() {
    return [{
        type: 'output',
        regex: /<input type="checkbox" disabled=""/,
        replace: '<input type="checkbox"'
    }];
};

var converter = new showdown.Converter({
    tasklists: true,
    smoothLivePreview: true,
    extensions: [taskListEnablerExtension]
});
```

It's hard to debug this since the extension is not invoked with any event argument or anything else I can inspect. Ideas?

**Comment by tivie** [comment]
You can check a working fiddle here: https://jsfiddle.net/e5af9kdr/1/

```js
var taskListEnablerExtension = function() {
    return [{
        type: 'output',
        regex: /<input type="checkbox" disabled(="")?/g,
        replace: '<input type="checkbox"'
    }];
};

var converter = new showdown.Converter({
    tasklists: true,
    smoothLivePreview: true,
    extensions: [taskListEnablerExtension]
});
```

**Comment by tivie** [comment]
#
> ## Donate
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate [through Patreon](https://patreon.com/showdownjs) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by asbjornu** [comment]
Yep, that did the trick. Thanks!
