### ISSUE TITLE
Emojis broken on minified build

### ISSUE THREAD

**Issue by oscarmorrison** [showdownjs/showdown#595]
![image](https://user-images.githubusercontent.com/1651212/46570716-2d844080-c9ac-11e8-9d04-fbac96b14c44.png)

Need to pass the `ascii_only=true` to uglify

**Comment by tivie** [comment]
@oscarmorrison can you elaborate a bit? What do you mean by emojis broken in minified build?
I've just tested in a fiddle, with the minified version and emojis seems to be working ok.

https://jsfiddle.net/tivie/w9bd7rot/1/

**Comment by tivie** [comment]
@oscarmorrison Closing as no feedback was produced in 11 days. If you feel this was premature, feel free to reopen the issue.

**Comment by oscarmorrison** [comment]
@tivie sorry for lack of response, happy to keep closed.  Essentially using the minified build, if you concat that with another script, the emoji's got broken. Leaving this here incase anyone else has same problem, this was my solution in the end, to concat, then minify the build myself:

```
// where script.js is your custom script
uglifyjs -c -m -o md-page.js showdown.js script.js -b beautify=false,ascii_only=true
```
