### ISSUE TITLE
Bug in add default classes for each HTML element wiki page

### ISSUE THREAD

**Issue by MikielAgutu** [showdownjs/showdown#597]
https://github.com/showdownjs/showdown/wiki/Add-default-classes-for-each-HTML-element

```
regex: new RegExp(`<${key}(.*)>`, 'g'),
replace: `<${key} class="${classMap[key]}" $2>
```

According to : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#

> The capturing groups are numbered according to the order of left parentheses of capturing groups, starting from 1. 

The regex only has 1 capturing group. Therefore, in `replace`, the `$2` ought to be `$1`.

**Comment by tivie** [comment]
Thank you. Fixed
