### ISSUE TITLE
captureEnd Event is not triggered inside writeAnchorTag function

### ISSUE THREAD

**Issue by GabSocial** [showdownjs/showdown#599]
Hi,

I am trying to write an extension for github mentions. However I figure out captureEnd event is not triggered in writeAnchorTag. FYI

https://github.com/showdownjs/showdown/blob/db69d02974df5df13ab68a655e7fa29178678e26/src/subParsers/makehtml/links.js#L132

**Comment by tivie** [comment]
Those events are not supported yet. I'm in the middle of a complete reqriting of the parser and event systems for version 2.0.

**Comment by GabSocial** [comment]
@tivie I see. I think the design is good. I am sorry I needed to check latest version rather than master.

**Comment by tivie** [comment]
No problem. I pushed those updates because I was having troubles with my local disk and didn't want to lose the code changes.
