### ISSUE TITLE
Ignore syntax inside <pre> totally

### ISSUE THREAD

**Issue by H1D** [showdownjs/showdown#60]
I found that some syntax are not ignored inside &lt;pre> or code block (```). For example image embedding syntax. Also all extensions are not ignored. Is there a tag to ignore all syntax?

**Comment by tivie** [comment]
Can you provide a markdown example where this bug happens?

**Comment by mmavko** [comment]
Similar thing happening in @borismus's "Markdown Preview" Chrome extension (https://chrome.google.com/webstore/detail/markdown-preview/jmchmkecamhbiokiopfpnfgbidieafmd).

Here's the snippet:

```
    ```shell
    $ python ./Texas/manage.py syncdb
    $ python ./Texas/manage.py migrate
    ```
```

Additionally, this gets wrapped in `code` tag, but no `pre` tag. The output:

```
<code>shell
$ python ./Texas/manage.py syncdb
$ python ./Texas/manage.py migrate
</code>
```

**Comment by tivie** [comment]
THis was fixed in https://github.com/showdownjs/showdown/pull/147
