### ISSUE TITLE
cndjs claims to host Showdown 1.8.6 but it returns the wrong version???

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#603]
@tivie I just ran into issue #478 again, which I know you already fixed when my colleague reported it to you, and was trying to figure out why. In my case, I'm in a different web service project, and the version of showdown that I download (Visual Studio downloads it for me automatically, actually) is reported as 1.8.6; however, it does not contain this fix, so it is quite clearly not version 1.8.6.

Here is the file that is automatically downloaded into my web service when it is launched from a new deployment for the first time: https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.6/showdown.js.

If you look in that file, specifically at lines 3785-3793, you will see that they _do not_ contain the fixes you applied in [this commit](https://github.com/showdownjs/showdown/commit/fe70e4530bfd3d299001291bbd0f720bbf120618).

Do you have any idea why this fix might not be showing up in a version that is being reported as 1.8.6 but doesn't actually appear to be 1.8.6?

**Comment by tivie** [comment]
It's correct. The commit fe70e45 is after commit a8bcde1 (v 1.8.6 commit).

Since version 2.0 is taking a lot more time than expected, I will backport some of the fixes from 2.0 and release a version 1.8.7 today if possible.

**Comment by tivie** [comment]
@KirkMunro Btw, do you feel literalMidWordAsterisk is an essential option? Cause for version 2.0 I was really thinking about droping that option since it's causing a lot of trouble in the new parser

**Comment by KirkMunro** [comment]
@tivie I think it's pretty important, yes. I also have something that I've been thinking may help: in our app we added an extension for a different emphasis syntax that we needed, and I'm really proud of how well that works, with mid word emphasis or not. It uses a combination of a greedy and a lazy search to figure out what the user really wanted, and works quite wonderfully, with every test case I've thrown at it. Made me wonder if the same logic would be helpful to showdown when it needs to deal with bold or italic emphasis enclosures.

**Comment by tivie** [comment]
Version 1.8.7 is available now and should include that (and other) bugfixes.

**Comment by tivie** [comment]
> What needs to be done to make 1.8.7 available on cdnjs?

cdnjs should update automatically. This update is taking longer, I don't know why. You can try to post an issue in the [CDNJS repository](https://github.com/cdnjs/cdnjs) so that devs might have a look why the package is not being updated.

You also have <https://unpkg.com/#/> CDN: https://unpkg.com/showdown@1.8.7/dist/showdown.min.js




> Also I just looked at the change log and it doesn't show any changes for 1.8.6 or 1.8.7

What do you mean? https://github.com/showdownjs/showdown/blob/version_1.x/CHANGELOG.md

**Comment by KirkMunro** [comment]
Thanks, I posted an issue in the CDNJS repo asking why it seems to be taking so long.

For the change log, I was referring to this document:
https://github.com/showdownjs/showdown/blob/master/CHANGELOG.md

It shows the last update as 1.8.5. Is that because master is now the 2.x branch?

**Comment by tivie** [comment]
Yes. I will update that

**Comment by KirkMunro** [comment]
Great, thanks for this @tivie! I'll close this issue since I have [this issue](https://github.com/cdnjs/cdnjs/issues/13055) opened in the CDNJS repo.
