### ISSUE TITLE
how i create [toc] menu.  showdown-toc can`t  use

### ISSUE THREAD

**Issue by busyhe** [showdownjs/showdown#605]

**Comment by BusyHe** [comment]
i want to create toc menu. #422 showdown-toc requires jQuery, it cant`t use. what should I do。thank

**Comment by tivie** [comment]
You can make an extension.

Also, if you're willing to wait for version 2.0, creating a TOC will be trivial, sicne showdown will have a proper parser that outputs an abstract node tree that represents the document tree (and you can grab all the headings to create a TOC).

**Comment by ahungrynoob** [comment]
I will create a showdown-toc-meta extension.
