### ISSUE TITLE
Problem with Demo document indentation

### ISSUE THREAD

**Issue by tlhunter** [showdownjs/showdown#613]
The demo document uses 2 space indentation, however Showdown by default only accepts 4 space indentation.

![20181028144849](https://user-images.githubusercontent.com/551402/47622417-04922f80-dac2-11e8-93a3-2bcf31bccfeb.png)

(I wasn't able to find this demo docs in the repo, if someone points me to it I can update in a PR)

**Comment by tivie** [comment]
Nice catch. The document is pulled from the wiki https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax

should be fixed now

**Comment by tivie** [comment]
fixed
