### ISSUE TITLE
Issues on Codes blocks generation

### ISSUE THREAD

**Issue by neooblaster** [showdownjs/showdown#617]
Hi team,

I just install Showdown in version 1.8.7 : 
![image](https://user-images.githubusercontent.com/22078558/48162527-a1807400-e2dd-11e8-8d4a-8b1e534ff0ac.png)

Currently, I'm facing of an old issue which must be fixed (#184)

The following Markdown code produce this result :
```
* **Author** : ``Nicolas DUPRE (NDU9005)``
* **Release** : ``01.10.2018``
* **JIRA request** : ``CEPS01T-83283``
* **Edition Tags** : 
    ````abap
    * BEGIN_ADDITION - NDU90045 - CEPS01T-83283
      <<Code Changes Here>>
    */ END_ADDITION - NDU90045 - CEPS01T-83283
    ````
```
![image](https://user-images.githubusercontent.com/22078558/48162658-f15f3b00-e2dd-11e8-82c3-0436194e56e9.png)

It's very weird, because the underscore in `BEGIN_ADDITION` disapears. I try to break `BEGIN_ADDITION` which can be an instruction in the Showdown engine, but nothing change.

<hr />

The following Markdown code produce the good result :
```
* **Author** : ``Nicolas DUPRE (NDU9005)``
* **Release** : ``01.10.2018``
* **JIRA request** : ``CEPS01T-83283``
* **Edition Tags** : 
````abap
* BEGIN_ADDITION - NDU90045 - CEPS01T-83283
  Code Changes Here
*/ END_ADDITION - NDU90045 - CEPS01T-83283
````
( Dont take care of code highlight)
![image](https://user-images.githubusercontent.com/22078558/48162891-8feb9c00-e2de-11e8-8d3c-0997135e86b3.png)

I expected this result : 
![image](https://user-images.githubusercontent.com/22078558/48162958-b1e51e80-e2de-11e8-8808-f77544de5dac.png)

<hr />

When I add a new line , that works, but I don't want these spaced lines :
```
* **Author** : ``Nicolas DUPRE (NDU90045)``
* **Release** : ``01.10.2018``
* **JIRA request** : ``CEPS01T-83283``
* **Edition Tags** : 

    ````abap
    * BEGIN_ADDITION - NDU90045 - CEPS01T-83283
      Code Changes Here
    */ END_ADDITION - NDU90045 - CEPS01T-83283
    ````
```
![image](https://user-images.githubusercontent.com/22078558/48163497-1a80cb00-e2e0-11e8-8db7-03df0f18fcbd.png)


UPDATE : 
When I use Indented code block, , in this following code block, the result is a Code block into another one :

```
      " Parcourir le niveau 1 de la hiérachie.
      LOOP AT lt_rgsb1.
        CALL FUNCTION 'G_SET_FETCH'
          EXPORTING
            setnr            = lt_rgsb1-setnr
          TABLES
            set_lines_single = lt_rgsb2
          EXCEPTIONS
            no_authority     = 1
            set_is_broken    = 2
            set_not_found    = 3
            OTHERS           = 4.
    
    
        " Parcourir le niveau 2 de la hiérachie.
        LOOP AT lt_rgsb2.
          CALL FUNCTION 'G_SET_FETCH'
            EXPORTING
              setnr            = lt_rgsb2-setnr
            TABLES
              set_lines_single = lt_rgsb3
            EXCEPTIONS
              no_authority     = 1
              set_is_broken    = 2
              set_not_found    = 3
              OTHERS           = 4.
```
Result :
![image](https://user-images.githubusercontent.com/22078558/48185771-5c3c6080-e336-11e8-972f-2cd1176a1049.png)
![image](https://user-images.githubusercontent.com/22078558/48185805-78d89880-e336-11e8-9d72-3f17443786d0.png)


With my development experience, one possible explanation could be, when openning tags for code block did not begin at the first char of one line (so, containing spaces/tab (in my case tab are spaces)), the engine only check the closing tag for code block, without take care of spaces/tab as the openning one. So the first corresponding closing tag (```) is good candidate.

When the root openning tag for code don't begin with tab/space, there is no issue.
END UPDATE.

Do you know why that does not work in my case ?

Thanks a lot for the support.

Best Regards,
Nicolas DUPRE

**Comment by tivie** [comment]
Hi @neooblaster 

The newline between `* **Edition Tags** : ` and the fenced codeblock is required [according to the original spec](https://daringfireball.net/projects/markdown/syntax#list).

Some markdown implementations are more lax and don't require this (namely commonmark)


Note: Showdown version 2.0 which have a fully compliant commonmark "mode".

**Comment by neooblaster** [comment]
Hi @tivie,

Thank you for your reply. I did not know that was the official spec.
I always skip the newline, because my tools which renders my Markdown (PhpStorm, Markdown-PDF) add spaces between my list items.

An idea when Showdown v2.0 will be released ?

**Comment by tivie** [comment]
Hope I can launch an alpha until the end of the year

**Comment by neooblaster** [comment]
Ok top !
I will be present to test it with my "issue" ;)

Thank you for your support.
