### ISSUE TITLE
Support for other markdown specs

### ISSUE THREAD

**Issue by DonaldTsang** [showdownjs/showdown#620]
- [ ] CommonMark https://commonmark.org/
- [ ] Github Flavored https://github.github.com/gfm/
- [ ] Markdown Extra https://michelf.ca/specs/markdown-extra/
- [ ] MultiMarkdown https://fletcherpenney.net/multimarkdown/

**Comment by tivie** [comment]
?

**Comment by DonaldTsang** [comment]
@tivie these are all different standards of the type "markdown", it would be great to see all of these derivatives to be implemented

**Comment by frumbert** [comment]
I for one would love to see the use of Markdown Extra being possible. E.g.

    ![Elva dressed as a fairy](elva-fairy-800w.jpg){srcset="elva-fairy-320w.jpg 320w, elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w" .my-class .img #myId action="make-clickable"}

would become

    <img src="elva-fairy-800w.jpg" alt="Elva dressed as a fairy" srcset="elva-fairy-320w.jpg 320w, elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w" class="my-class img" id="myId" data-action="make-clickable">

MDE is also supported by PanDoc which is my current solution as a server-side renderer (though it also wraps images in a figure element - https://pandoc.org/try/?text=&from=markdown&to=html5)

**Comment by tivie** [comment]
I know these are markdown flavors. 

Regarding CommonMark and GFM, **showdown already supports all the features** (although there are some differences in output in edge cases). 

In fact, some of the features of those specs were **borrowed from showdown**.

As for non standard implementations, that's what extensions are for. With showdown it's trivial to add new syntax.

With version 2.0, the new template system will make it even easier to add new synatx and even completely change the output of existing subparsers.
