### ISSUE TITLE
Emphasis / bold fails

### ISSUE THREAD

**Issue by edgewood1** [showdownjs/showdown#625]
My markdown contains a line with two sets of underscores on either side which typically correctly outputs as bold.  However, showdown is outputting it in \<p\> tags as opposed to \<b\> tags or some equivalent.  
I've tried variations on the underscore and asterisks as well.  Any suggestions on why this is happening?

**Comment by tivie** [comment]
@edgewood1 Can you specify exactly the **input**, **expected output** and **actual output**?

**Comment by edgewood1** [comment]
On closer inspection, it does includes the expected output in the console.

the markdown:`__Method 2: Component Functions w/o Arguments__`
expected/actual output: `<p><strong>Method 2: Component Functions w/o Arguments</strong></p>` 

However, upon rendering in chrome and firefox, this line is not in bold even though a similar line set for italics renders fine.  

Attached is the react code and resulting screen shot.


[showdown.txt](https://github.com/showdownjs/showdown/files/2670345/showdown.txt)
<img width="763" alt="screenshot" src="https://user-images.githubusercontent.com/20213366/49845328-31f61c80-fd94-11e8-964e-a985301f1ef6.png">

**Comment by tivie** [comment]
The file you provided is in RTF format

**Comment by edgewood1** [comment]
[src_components_react_post.txt](https://github.com/showdownjs/showdown/files/2672237/src_components_react_post.txt)

**Comment by tivie** [comment]
Sorry, maybe I wasn't clear. In order for me to help you, I need the markdown input, the output from showdown and the output you expected.

Example:

**input**

```md
*foo* **bar**
```

**expected output**

```html
<p><em>foo</em> <strong>bar</strong></p>
```

**actual output**

```html
<p>foo bar</p>
```

**Comment by edgewood1** [comment]
Yes, I gave that information to you in a previous post.  I'll try to rephrase it: 

On closer inspection, the expected output IS appearing in the console. _However_, this output does not not appear as bold in the chrome or firefox browsers even though my italics markup _does_ render as italics in the browser. 

the markdown(input): __Method 2: Component Functions w/o Arguments__
expected output:  <p><strong>Method 2: Component Functions w/o Arguments</strong></p>
actual output: <p><strong>Method 2: Component Functions w/o Arguments</strong></p>

Thanks.

**Comment by tivie** [comment]
Yes, you're right, i missed it.

What version of showdown are you using? In the latest version 1.9.0 I could not reproduce the issue.
