### ISSUE TITLE
Links break when title contains email address

### ISSUE THREAD

**Issue by mirka** [showdownjs/showdown#632]
The Markdown parsing breaks when a link title contains an email-address-like string surrounded by spaces.

Input:

```
[Inline](http://showdownjs.com/ " a@b.c ")
```

Output:

```
<p><a href="http://showdownjs.com/" title=" <a href=">a@b.c</a> "&gt;Inline</p>
```

Simplified example: http://demo.showdownjs.com/#!/%5BInline%5D(http://showdownjs.com/%20%22%20a@b.c%20%22)%0A%0A%5BReference%5D%5B1%5D%0A%0A%5B1%5D:%20http://showdownjs.com/%20%22%20a@b.c%20%22

So a title like `Email me at hello@me.com to say hi!` would break the output.

**Comment by tivie** [comment]
confirmed

**Comment by SyntaxRules** [comment]
The latest version of showdown translates this:
```
[Inline](http://showdownjs.com/ " a@b.c ")
```
into this:
```
<p><a href="http://showdownjs.com/" title=" a@b.c ">Inline</a></p>
```
I think this is what is expected. Please re-open this issue if I am not correct, or we need to re-address this.
