### ISSUE TITLE
Don't convert ...  (three dots) into … (Unicode Character 'HORIZONTAL ELLIPSIS' (U+2026))

### ISSUE THREAD

**Issue by junyuecao** [showdownjs/showdown#634]
I have a gitlab url in the markdown document like this: 

https://gitlab.com/gitlab-org/gitlab-ce/compare/v11.5.4...v11.5.5  (right)

showdown will convert the ... into the unicode … so that the url is not available.

https://gitlab.com/gitlab-org/gitlab-ce/compare/v11.5.4…v11.5.5  (wrong)

**Comment by judell** [comment]
> I will be removing this feature

Sounds like a good idea. Data point: I had to comment it out because of mis-encoding that I couldn't figure out.

**Comment by Dam-Buty** [comment]
Hi ! 

I second this motion ;) i'm using Showdown as part of a message templating chain that sometimes sends SMS ... Our SMS bill has doubled because this unicode character forces Unicode encoding instead of the standard GSM one :/

**Comment by tivie** [comment]
@Dam-Buty That is a damn good reason!

**Comment by tzachyrm** [comment]
+1
Any updates? My reason is that I use a font that doesn't have a glyph for the Unicode ellipsis, so the output looks bad.
Any workaround to disable this feature until there's a permanent fix?

**Comment by SyntaxRules** [comment]
#731 Was merged into master. It will be part of v2.0.0. This should solve this issue for now. If anyone feels strongly that the ellipsis should be entirely removed, or default to false then please make another issue or PR for that! (Ping: @tivie @junyuecao @judell @Dam-Buty ). Thanks all!
