### ISSUE TITLE
Tasklist does not generate input tag

### ISSUE THREAD

**Issue by richyliu** [showdownjs/showdown#637]
With the `tasklists` option enabled, showdown generates
```html
<ul>
    <li class="task-list-item"> foo</li>
    <li class="task-list-item"> bar</li>
</ul>
```
from the following markdown:
```markdown
- [x] foo
- [ ] bar
```

However, as specified in the [docs](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#tasklists-gfm-style), an `input` element should be generated as well inside each `li`:
```html
<ul>
    <li class="task-list-item"><input type="checkbox" disabled checked> foo</li>
    <li class="task-list-item"><input type="checkbox" disabled> bar</li>
</ul>
```

**Comment by fabiospampinato** [comment]
I don't have this problem, I'm setting `converter.setFlavor ( 'github' );`

**Comment by richyliu** [comment]
It works with `converter.setFlavor('github')`. Thank you
