### ISSUE TITLE
A link with empty content inside a list gets rendered as a checkbox

### ISSUE THREAD

**Issue by fabiospampinato** [showdownjs/showdown#638]
The following thing:

```markdown
- [](www.google.com)
```

Gets rendered like so by GitHub:

- [](www.google.com)

But even with GFM enabled it gets rendered as the following by parsedown:

<img width="189" alt="screen shot 2019-01-17 at 15 16 18" src="https://user-images.githubusercontent.com/1812093/51324366-d8f06700-1a6a-11e9-916d-108d7437f9bc.png">

I think the regex used for matching checkboxes should check that the character after the closing square bracket is not an opened square bracket/parenthesis `(?!\[|\()`.

**Comment by tivie** [comment]
confirmed

**Comment by SyntaxRules** [comment]
The latest version of showdown translates this:
```
- [](www.google.com)
```
to this:
```
<ul>
<li><a href="www.google.com"></a></li>
</ul>
```
I think this is what you expect. Since it has been forever, I don't expect a response. But in the case that I am incorrect, please re-open this issue. Thanks!
