### ISSUE TITLE
Blog post error: new feature Markdown to HTML converter

### ISSUE THREAD

**Issue by mattgaspar** [showdownjs/showdown#642]
Blog post from 2018-11-10 says 

> Version 1.9.0 introduces a new feature, the **Markdown to HTML** converter.

Shouldn't it be the other way around "HTML to Markdown" since markdown to html is not a new feature, as it's the core feature!

**Comment by tivie** [comment]
thank you

**Comment by bandantonio** [comment]
Fixed. @mattgaspar thanks for reporting it.
