### ISSUE TITLE
Showdown refuses to grab metadata.

### ISSUE THREAD

**Issue by jcc10** [showdownjs/showdown#644]
I have been building a website framework and figured I would switch to markdown as opposed to JSON as it would be far simpler to use, however I can't seem to get the metadata parser to function.

```javascript
var converter = new showdown.Converter({metadata:true});
var text      = '«««\
title: document title\
some meta name: some meta content\
»»»\
    \
    # Test';
var html      = converter.makeHtml(text);
var metadata = converter.getMetadata(true); // returns an object with the document metadata',

console.log(html);
console.log(metadata);
```

The metadata is empty and the HTML includes the metadata. I honestly don't know what I'm doing wrong. (I have also tried the `---` version, it didn't work.)

**Comment by tivie** [comment]
Glad your worked it out
