### ISSUE TITLE
Tasklist does not comply GFM

### ISSUE THREAD

**Issue by andreas-vvv** [showdownjs/showdown#655]
Hi,

I recommend to adjust `var rgx` in [makehtml.links](https://github.com/showdownjs/showdown/blob/master/src/subParsers/makehtml/links.js) to 
```js
var rgx = /(\n)?(^ {0,3})([*+-]|\d+[.])[ \t]+((\[(x| )][ \t]+)?[^\r]+?(\n{1,2}))(?=\n*(¨0| {0,3}([*+-]|\d+[.])[ \t]+))/gim
````

since GFM expects a space character after the task list item marker 

> A task list item is a list item where the first block in it is a paragraph which begins with a task list item marker and at least one whitespace character before any other content.
https://github.github.com/gfm/#task-list-items-extension-

**Comment by tivie** [comment]
Thanks,
