### ISSUE TITLE
“One of your alts has already entered the tournament” error when joining tournament

### ISSUE THREAD

**Issue by PatrickL789** [showdownjs/showdown#656]
I am helping a friend set up a server.  When we teat the code on a hosted server, and try to create a tournament, we are encountering a message that says “one of your alts has already entered this tournament” when other people try to join the created tournament even though no participants have entered the tournament yet. As a result, no one can join the tournaments we create.

How can we resolve this issue?

**Comment by tivie** [comment]
I'm sorry what?

**Comment by PatrickL789** [comment]
When we teat the code on a hosted server, and try to create a tournament, we are encountering a message that says “one of your alts has already entered this tournament” when other people try to join the created tournament even though no participants have entered the tournament yet.

**Comment by tivie** [comment]
This library is a markdown to HTML converter

**Comment by PatrickL789** [comment]
Oh. Oops. You’re right. Wrong repo. Sorry.
