### ISSUE TITLE
license of showdown_1.9.0: GPL or BSD?

### ISSUE THREAD

**Issue by luisapace** [showdownjs/showdown#659]
Hi, my team would like to use the package showdown_1.9.0 and to approve that I've to verify all its licenses (included those of all of the modules included), and to do that I've to analyze its source code.

Now I've noted that the Readme declares it under GPL V2, while the license.txt is BSD.

Could you please clarify what is the license of showdown_1.9.0?

Thanks.

**Comment by luisapace** [comment]
Hi, any news on this?

**Comment by tivie** [comment]
Sorry for the delay in answering the question. That is, in fact, a mistake. I've checked the code and previous versions are under BSD. I will fix the readme as soon as possible.

**Comment by luisapace** [comment]
Perfect, thanks!

**Comment by SyntaxRules** [comment]
FYI, showdown 2.0.0 is moving to MIT license
