### ISSUE TITLE
Emojis Broken Image Source

### ISSUE THREAD

**Issue by vmjames** [showdownjs/showdown#662]
I have tried showdown 1.0.9 with and without showdown-emoji 1.0.5 and can not get emojis to work. 

Without showdown-emoji I just get the text:

`<p>emoji :smile:</p>`

And with showdown-emoji the image links appear to be broken: 

<p>emoji <img src="https://github.global.ssl.fastly.net/images/icons/emoji/smile.png?v5" alt=":smile:" title=":smile:" class="emoji-img emoji"></p>

https://github.global.ssl.fastly.net/images/icons/emoji/smile.png?v5 is not found?

Am I missing something? Thanks

**Comment by vmjames** [comment]
I got it working without showdown-emoji but adding emoji: true.

Whoops!

**Comment by tivie** [comment]
Glad you figure it out. :)
