### ISSUE TITLE
Multiple break lines aren't preserved

### ISSUE THREAD

**Issue by rmartins90** [showdownjs/showdown#665]
When converting a markdown with multiple line breaks it does render only one break line.

Implementation: https://jsfiddle.net/rkLuo3n6/1/

**Comment by tivie** [comment]
Where you expecting multiple empty paragraphs? Or the html output to have 2 paragraphs separated by multiple empty lines?

**Comment by tivie** [comment]
closing as no update

**Comment by vince1995** [comment]
But an option to do this would be nice. Could be a `<br>`. 🤷‍♂️

**Comment by tivie** [comment]
@vince1995 Showdown already supports `<br>`. You can either add 2 spaces at the end of the line or use the option `simpleLIneBreaks`.

**Comment by Brentably** [comment]
chatgpt api streams back markdown with multiple \n's...

**Comment by TheDogHusky** [comment]
> [@vince1995](https://github.com/vince1995) Showdown already supports `<br>`. You can either add 2 spaces at the end of the line or use the option `simpleLIneBreaks`.

With this option, it parses simple line breaks like github. Cool.
But still no option to parse multiple line breaks. Could be handy for a lot of people to be able to put multiple line breaks.
