### ISSUE TITLE
Strange limitation: maximum nesting of 10 spans reached!!!

### ISSUE THREAD

**Issue by Guseyn** [showdownjs/showdown#668]
When I am trying to use html tables with number of rows more than 5-6, I get an error `maximum nesting of 10 spans reached!!!`
What is it, and why is this limitation needed ?

**Comment by tivie** [comment]
Can you provide an input example?

https://github.com/showdownjs/showdown/blob/4da93e8e136e5cc1f13ad2b3d5477c14e11aaafd/src/subParsers/makehtml/hashHTMLSpans.js#L41

**Comment by Guseyn** [comment]
I don't have it now, I fixed it enabling tables in MD, didn't see this moment at first, I thought that this lib does not support tables
