### ISSUE TITLE
Release text 1.9.0 might be wrong?

### ISSUE THREAD

**Issue by fabsenet** [showdownjs/showdown#672]
I was reading the [release text of 1.9.0](https://github.com/showdownjs/showdown/releases/tag/1.9.0):

> Version 1.9.0 introduces a new feature, the **Markdown to HTML converter**. This feature is still experimental and is a partial backport of the new Reverse Converter planned for version 2.0.

This looks odd to me. shouldn't it be more like: 

> Version 1.9.0 introduces a new feature, the **HTML to Markdown converter**. 

??

**Comment by tivie** [comment]
Huhh... yes you're right...

**Comment by fabsenet** [comment]
you know you could fix it in a minute in the release here on github and even your website would update? :unicorn:

**Comment by tivie** [comment]
I believe I've already fixed it
