### ISSUE TITLE
I would be happy if you add support for rtl and css (in completeHTMLDocument)

### ISSUE THREAD

**Issue by Men770** [showdownjs/showdown#673]
I would be happy if you add support for rtl and css (in completeHTMLDocument)

**Comment by obedm503** [comment]
How does showdown prevent you from doing rtl or css?

**Comment by Men770** [comment]
in completeHTMLDocument

**Comment by obedm503** [comment]
if you provide a full example I can probably help you out. If you're running in node you could use [jsdom](https://www.npmjs.com/package/jsdom) to get the same api as in the browser

**Comment by tivie** [comment]
closing issue as no update provided in 28 days

**Comment by SomwareHR** [comment]
I don't know about OP, but I understood that they wanted something like adding
   <link rel="stylesheet" href="customstylesheed.css">
when option "completeHTMLDocument" = "true".
That would be nice :)
