### ISSUE TITLE
Detecting link click

### ISSUE THREAD

**Issue by Marclev78** [showdownjs/showdown#675]
Is there any way for me to detect when a link is clicked and execute some custom JavaScript instead of treating it as a simple `href`?

I mean the sort of thing I would do in an onclick handler in pure HTML.

**Comment by obedm503** [comment]
you could attach event listeners to all anchors after they've been rendered
```ts
function handleClick(e) {
  // preventDefault stops the browser from following the link
  e.preventDefault();
  alert('link to ' + e.target.href + ' was clicked');
}

// a[href] finds all anchors with an href attribute
$container.querySelectorAll('a[href]')
  .forEach(function($el) {
    $el.addEventListener('click', handleClick);
  });
```
full example: https://jsbin.com/kahenulimu/1/edit?html,js,console,output
