### ISSUE TITLE
Debug Showndown Not Working

### ISSUE THREAD

**Issue by gdemir** [showdownjs/showdown#683]
Hi,

I want to default showndown.min.js **like option of Github markdown converter**. [Demo](http://demo.showdownjs.com/#!/%23%23%23%23%23%20%60render%60%20(%24view_options%20%3D%20%5B%5D%2C%20%24response_options%20%3D%20NULL)%20veya%20(%24template%20%3D%20%22%22%2C%20%24response_options%20%3D%20NULL)) link correct running but my JS file not working [showdown.min.js](https://barak-framework.github.io/assets/js/showdown.min.js)

i am trying this code but not working : 

    ##### `render` ($view_options = [], $response_options = NULL) veya ($template = "", $response_options = NULL)

**Showndown output :**

[Link Click → DOKÜMANTASYON Click → Guides>Controllers>Methods>Render Method Output Here](https://barak-framework.github.io/ )

    render ($viewoptions = [], $responseoptions = NULL) veya ($template = "", $response_options = NULL)

**GitHub output :**
 
[github-markdown2html](https://github.com/barak-framework/barak-framework.github.io/blob/master/guides/v5.0.0/README.md#render-view_options---response_options--null-veya-template---response_options--null)

    render ($view_options = [], $response_options = NULL) veya ($template = "", $response_options = NULL)

**Comment by tivie** [comment]
I'm sorry, I don't understand. What debug option are you referring to?

**Comment by gdemir** [comment]
@tivie Compare github and your converter outputs.

GitHub output : "$view_options" correct 
but 
Showndown output : "$viewoptions" wrong output

**Comment by gdemir** [comment]
this problem solved with this option :      ` literalMidWordUnderscores: true`
