### ISSUE TITLE
Header level start

### ISSUE THREAD

**Issue by blabno** [showdownjs/showdown#69]
Hi,
I have a following usecase:
```
H1 Package.name
H2 SubPackage.name
(showdown.makeHtml(SubPackage.description))
```
So it would be great if I could call ```showdown.makeHtml(SubPackage.description,3)```
so that in case there is following code in ```SubPackage.description```
```
\#Given
\#When
\#Then
```
I could get output like this:
H1 Package.name
H2 SubPackage.name
H3 Given
H3 When
H3 Then

**Comment by tivie** [comment]
Added this feature in  b84ac67

To set the header level start to 3 (`<h3>`) just pass it as an option. Example:
```js
var conv = new showdown.Converter({headerLevelStart: 3})
```
