### ISSUE TITLE
makeMarkDown does not work node server side

### ISSUE THREAD

**Issue by crissacandler** [showdownjs/showdown#691]
Description (Brief description of the problem)
When I am using server side node and I want to convert Html back into markdown. I get this outcome: 

Code:
```
const showdown = require('showdown')
showdown.setOption('noHeaderId', true)
const converter = new showdown.Converter()
converter.setFlavor('github')

 converter.makeMarkdown('<h1>a heading</h1>')
 console.log('# a heading')

```

Input (input that is causing problems):
The input is basic html

`'<h1>a heading</h1>'`

Expected Output (Output that is expected)

`'# a heading'`

Actual Output (Actual showdown output)

`
ReferenceError: window is not defined
      at showdown.Converter.makeMarkdown.makeMd (node_modules/showdown/dist/showdown.js:2544:7)
      at Object.module.exports.toMarkdown.htmlString [as toMarkdown] 
`

**Comment by SkylarPhx** [comment]
It requires a WHATWG DOM and HTML parser for a second parameter – such as `JSDOM`. If not provided the `window.document` will be used.

**Comment by braian125** [comment]
Could someone help with a more specific answer here, or some documentation for beginners? Thanks

**Comment by nilscox** [comment]
Hi, using `JSDOM`, it could be something like:

```js
const showdown = require('showdown');
const jsdom = require('jsdom');

const dom = new jsdom.JSDOM();
const converter = new showdown.Converter();
const html = '<h1>Hello!</h1>';

const md = converter.makeMarkdown(html, dom.window.document);
```

Hope it helps!

**Comment by tivie** [comment]
As stated by other users, makeMarkdown in node requires a third party DOM parser to work, since "window" is not available in that environment. You can use any third party DOM parser as long as it follows the spec (for instance [JSDOM](https://github.com/jsdom/jsdom))
