### ISSUE TITLE
headerId cause problems

### ISSUE THREAD

**Issue by chendifan** [showdownjs/showdown#692]
Current showdown.js will generate pure digital id for heading dom element, but it will cause error when try to `document.querySelectorAll('#1')`.

The error is something like this:

`Failed to execute ‘querySelectorAll’ on ‘Document’: ‘#1’ is not a valid selector`.

After adding this config, problem solved:
`noHeaderId: true`

But since I cannot predicate the behavior of other third party plugin, could showdown.js generate normal id instead or just not generate id by default, I`m not sure which is the best way, thank you very much.

**Comment by keerthivasan-r** [comment]
Just as a note, HTML 4.01 has greater restrictions on the content of id values (for example; in HTML 4.01, id values cannot start with a number).

# Attribute values


Value | Description
-- | --
id | Specifies a unique id for the element. 

Naming rules
  * Must contain at least one character 
  * Must not contain any space characters
