### ISSUE TITLE
Tasklists not showing correct in html-output

### ISSUE THREAD

**Issue by louagej** [showdownjs/showdown#699]
Hi,
I'm trying to convert tasklists to html with showdown.
in my javascript code, the option is set to true:

```javascript
var converter = new showdown.Converter({
    simplifiedAutoLink: true,
    tasklists: true,
    tables: true,
    strikethrough: true
}),
    text = data,
    html = converter.makeHtml(text);
```

In my markdown, it show up correct like this:
2. Takslist

- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request

But the **html-output** shows like this:
![image](https://user-images.githubusercontent.com/7229592/58094612-65559680-7bd1-11e9-972e-e9889215cef1.png)

**Comment by keerthivasan-r** [comment]
I'm not able to reproduce this error. I get this result. Can you please double check your input?

Input string - Markup
```
`2. Takslist
  *  [x] Finish my changes
  *  [ ] Push my commits to GitHub
  *  [ ] Open a pull request`
```
Output HTML

```
<ol start="2">
<li>Takslist</li>
</ol>
<ul>
<li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;" checked> Finish my changes</li>
<li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> Push my commits to GitHub</li>
<li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> Open a pull request</li>
</ul>
```

**Comment by ijkzen** [comment]
> 
> 
> I'm not able to reproduce this error. I get this result. Can you please double check your input?
> 
> Input string - Markup
> 
> ```
> `2. Takslist
>   *  [x] Finish my changes
>   *  [ ] Push my commits to GitHub
>   *  [ ] Open a pull request`
> ```
> 
> Output HTML
> 
> ```
> <ol start="2">
> <li>Takslist</li>
> </ol>
> <ul>
> <li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;" checked> Finish my changes</li>
> <li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> Push my commits to GitHub</li>
> <li class="task-list-item" style="list-style-type: none;"><input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> Open a pull request</li>
> </ul>
> ```

replacing '-1.6em' with '0.25em' will work.

**Comment by louagej** [comment]
Hi,

The reason was probably that I wasn't working with the latest version of showdown.js.
I downloaded the latest version and the html is generated goed now.

Kind regards,
Job
