### ISSUE TITLE
Where could I find your documentation?

### ISSUE THREAD

**Issue by xealits** [showdownjs/showdown#71]
I would like to find out if the showdown can escape produced html.
Apparently [here](http://softwaremaniacs.org/playground/showdown-highlight/ "the older version") it does not do so.
Don't see the answer in comments of the script (sure, I could just miss it)

**Comment by klmdb** [comment]
+1 for documentation request

**Comment by tivie** [comment]
You're right, the documentation is a bit sparse. We're restructuring the code and some breaking changes will be introduced so the documentation will need to be changed accordingly.

**Comment by pdeschen** [comment]
We're slowly migrating most of documentation bits out of the readme file into the [project wiki](https://github.com/showdownjs/showdown/wiki).

We'll also try to better support code documentation through jsdoc in a near future.

**Comment by tivie** [comment]
@pdeschen Documentation is getting a bit outdated.
