### ISSUE TITLE
makeHtml cann't convert to blockquote

### ISSUE THREAD

**Issue by lienze** [showdownjs/showdown#719]
```javascript
function compile(elem){
    var converter = new showdown.Converter();
    var html = converter.makeHtml(elem.innerHTML);
    elem.innerHTML = html;
}
```
input elem.innerHTML is 
```shell
> Pardon my french
```
output html variable is
```html
<p>&gt;Pardon my french</p>
```

**Comment by obedm503** [comment]
try using `elem.textContent` instead. If you use `innerHTML` the angle bracket is converted to `&gt;`

**Comment by lienze** [comment]
> try using `elem.textContent` instead. If you use `innerHTML` the angle bracket is converted to `&gt;`

I tried this and it works! Thanks a lot.
