### ISSUE TITLE
Can't upload your library to my repo?

### ISSUE THREAD

**Issue by EdmundMai** [showdownjs/showdown#72]
I tried integrating your library to my project, but when I went on my repo to the javascript folder, the "showdown" folder is not clickable. Deploying also doesn't work since it seems to just be a blank unclickable folder. Is there some sort of licensing issue? I eventually got it to work by just copying the parts I needed (showdown/src/). Still curious though

**Comment by tivie** [comment]
I don't really know what you're referring to. There is no licensing restrictions in using Showdown.

To install showdown you can download a release zip (or tarball), clone the repository or use Bower.
