### ISSUE TITLE
Question-source code of @types/showdown:1.4.31 

### ISSUE THREAD

**Issue by iamfariba** [showdownjs/showdown#722]
please let me know where is the link to download source code of @types/showdown version 1.4.31?

https://www.npmjs.com/package/@types/showdown/v/1.4.31  for the repository has this link https://github.com/DefinitelyTyped/DefinitelyTyped  but  this contains only master version,

Please let me know source code address for @types/showdown version 1.4.31.

Best Regards

**Comment by SyntaxRules** [comment]
It looks like the source code for that @type repo is version 1.4.1. Linked here: https://github.com/showdownjs/showdown/releases/tag/1.4.1
