### ISSUE TITLE
Add Option to Show 'Copy' Button by the Code Block

### ISSUE THREAD

**Issue by Chopinsky** [showdownjs/showdown#762]
It will be nice to add a 'Copy' button next to the generated code block, such that clicking the button will let user copy the (raw) code inside the block. 

I'd imaging something as shown below:

![image](https://user-images.githubusercontent.com/5376280/72370220-62ab3280-36c7-11ea-8838-ff7993a20382.png)

**Comment by ShinChven** [comment]
Leave it to [highlightjs-copy](https://github.com/arronhunt/highlightjs-copy)
