### ISSUE TITLE
Latest grunt-mocha module requires grunt update.

### ISSUE THREAD

**Issue by nicovalencia** [showdownjs/showdown#79]
When running `npm install`:

```
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-mocha@0.4.7 wants grunt@~0.4
```

[package.json](https://github.com/coreyti/showdown/blob/master/package.json#L33) specifies: `"grunt-mocha": "*"` which is grabbing v0.4.7. We need to either set an older version of grunt-mocha that's compatible with grunt-0.3.17, or upgrade grunt to 0.4.

**Comment by tivie** [comment]
This should be fixed in the new version 0.3.3
