### ISSUE TITLE
setFlavor does not work at all.

### ISSUE THREAD

**Issue by BreakUps** [showdownjs/showdown#792]

**Comment by obedm503** [comment]
@BreakUps can you at least show some example code of it not working?

**Comment by Slapbox** [comment]
Works fine for me.

**Comment by BreakUps** [comment]
```javascript
import showdown from 'showdown';
showdown.setFlavor('github');
const converter = new showdown.Converter({tables: true});
```
Above is my code. But I didn't get desired github-styled html. For example, blockquote don't have left grey border. So does it bahaves when I set other flavors.

**Comment by obedm503** [comment]
@BreakUps So, this is an issue with styling (css) and not structure? Showdown does not include any styling as part of it's output, just html. Styles, like a left grey border on block quotes, are up to you.

**Comment by BreakUps** [comment]
@obedm503 Ok, I misunderstood the effect of setFlavor.
