### ISSUE TITLE
Adding multiple titles/headers with the same content produces invalid markup.

### ISSUE THREAD

**Issue by nicovalencia** [showdownjs/showdown#82]
Creating a title/header [adds the content of the header](https://github.com/coreyti/showdown/blob/master/src/showdown.js#L778) to the header markup tag's `id` attribute.

For example:

```
# foobar
# foobar
```

produces:

```
<h1 id="foobar">foobar</h1>
<h1 id="foobar">foobar</h1>
```

If setting an `id` attribute is **necessary** for #hash linking, it should keep track of duplicates appending a unique identifier. e.g. `foobar-1`, `foobar-2`, etc or a timestamp `foobar-1389214127156`, `foobar-1389214127157`, etc.

If setting an `id` attribute is **unnecessary**, this functionality should be removed altogether.

**Comment by pdeschen** [comment]
@nicovalencia I think duplicate headers should be allowed and is all fine. What if I have something like

```
# Chapter 1

## Introduction
...

# Chapter 2

## Introduction
...

```

Now you're idea about using a suffix counter is an interesting workaround. As an addition: would it make sense to add the original section title as a class (for invariable styling)?

**Comment by tivie** [comment]
Once we merge the v2 branch, c367a4b will close this. @nicovalencia contribution should be mentioned though, somewhere appropriate.

**Comment by nicovalencia** [comment]
Makes sense to me -- thank you @tivie!

:cake:
