### ISSUE TITLE
Empty URL didn't get encode.

### ISSUE THREAD

**Issue by jcs090218** [showdownjs/showdown#820]
`[here]()` did not get encode to [here]().

Everything work if not empty.

**Comment by SyntaxRules** [comment]
We should support this, it look like it is common among markdown specs.

This is allowed in GFM: https://github.github.com/gfm/#example-495
This is allowed in CommonMark: https://spec.commonmark.org/0.30/#example-484
This is an ambiguous feature in DF: https://daringfireball.net/projects/markdown/syntax#link
