### ISSUE TITLE
text.replace() isn't a function

### ISSUE THREAD

**Issue by Scientific-Guy** [showdownjs/showdown#824]
Idk why this text.replace() error is comming for code blocks from md to html?

**Comment by obedm503** [comment]
Can you give more detail? It's difficult to figure out what you're talking about from:
>Idk why this text.replace() error is comming for code blocks from md to html?

Are you talking about extensions? A random showdown error?
A complete code example demonstrating the issue would be ideal.

**Comment by cursorweb** [comment]
I think what happened was that he provided the argument incorrectly
like if you put in `undefined`, obviously the output would be an error.

**Comment by Scientific-Guy** [comment]
No i didnt eneterd `undefined` or others i just did
```js
const showdown = require('showdown')
const converter = new showdown.converter()

console.log(converter,makeHtml('```js\nconst test = 'test'\n```'))
```

I eneterd this sample code

**Comment by obedm503** [comment]
@Scientific-Guy  `'```js\nconst test = 'test'\n```'` is not a valid string. Also, `test` is undefined.

**Comment by Scientific-Guy** [comment]
Thats just a string not a code so it wont matter its defined or undefined. And it is supposed to make a html

**Comment by obedm503** [comment]
I'm trying to say that the code you posted is invalid. It produces a syntax error.

**Comment by Scientific-Guy** [comment]
Uhmmm np i figured some other way
