### ISSUE TITLE
foundation.min.css  and demo.showdownjs.com/css/style.css are required to tables and snippets?

### ISSUE THREAD

**Issue by jrichardsz** [showdownjs/showdown#831]
Hi.

I love libraries ready to use like yours! Thanks for that.

When I was testing, I see the snippets a little rare and when I put a classic table markdown the suspicion was confirmed.

**Markdown sample:**

I cannot put here because is markdown:

![https://i.ibb.co/9p1KScw/sample.png](https://i.ibb.co/9p1KScw/sample.png)

**Error:**
![https://i.ibb.co/XJrwK9g/error.png](https://i.ibb.co/XJrwK9g/error.png)

---
With some luck, I found two css files in the official demo: http://demo.showdownjs.com/
So my final code was:
```
<script src= "https://cdn.jsdelivr.net/npm/showdown@1.9.1/dist/showdown.min.js" type="text/javascript" ></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.min.css" rel="stylesheet"> 
<link href="http://demo.showdownjs.com/css/style.css" rel="stylesheet"> 
```
And the error disappeared:

![https://i.ibb.co/LgDHJ8n/success.png](https://i.ibb.co/LgDHJ8n/success.png)

**Environment:**

- ubuntu
- firefox, chrome

**So my question are?**

- Are these files required?

Thanks

**Comment by abubakar-shehu** [comment]
I think it's not. However you can used it if you think the display is okay for you. But you can still create your own style sheet to suit your needs.

**Comment by tivie** [comment]
showdown does not include any style. Tables are converted to the appropriate HTML code, but no styling is provided. You can style however you want. Using foundation or your own custom style)
