### ISSUE TITLE
GitHub pages relative path links

### ISSUE THREAD

**Issue by elpiel** [showdownjs/showdown#836]
Is it possible to replace relative paths to github with full github paths?

Example:
`(My link)[./my_fille.md]` and `(My link)[/my_file.md]` to give a link to the actual repository, instead to the github pages url?

This might also be needed for Images, since images should be using the `raw` paths of github

**Comment by SyntaxRules** [comment]
Currently the markdown `[link](/uri)` is changed into `<a href="/uri">link</a>`. Are you asking if we can change this to make `[link](/uri)` point to `<a href="<some_repo>/uri">link</a>`?

**Comment by elpiel** [comment]
Not exactly.

In GitHub when you create a link to e.g. `./File.md` it will make a link that points to the file in the repository in the root of the repo.

I.e.:
`./My_Mardown.md` => `github.com/org/repo/tree/master/My_Mardown.md`

This should only be performed on relative or markdown files in the found links.

**Comment by SyntaxRules** [comment]
I don't think this is feasible to do in showdown. The library itself has no knowledge of the page it is being rendered on. In other words, the library does not know the webpage it is being rendered on so it cannot modify the links to point to a website specific location.

The best solution I can think of is to edit the "base url" outside of showdown. Alternatively we could create some kind of parameter to modify links to point to a given repo- but I'm not sure how feasible that is.

For now I'm going to close this, as my opinion is that showdown should not be modifying the links in this manner. However, we can review this again if there is significant interest.
