### ISSUE TITLE
Tag script is bug?

### ISSUE THREAD

**Issue by xiaofei9070** [showdownjs/showdown#841]
Tag script is bug?

**Comment by obedm503** [comment]
wat.jpg

spam?

**Comment by xiaofei9070** [comment]
script tag is not in pre code，this ‘<script></script> ’ can run

**Comment by obedm503** [comment]
Can you show what input you're giving the parser, what output it gave you, and what output were you expecting?

**Comment by xiaofei9070** [comment]
```javascript 
var converter = new showdown.Converter({tables: true});
	console.log(converter.makeHtml('~~test~~'))
````
Result is `<p>~~test~~</p>`
This result should `<del>test</del>`

**Comment by obedm503** [comment]
Ensure that `strikethrough: true` is set. http://demo.showdownjs.com/#!/~~test~~ seems to be working fine

**Comment by xiaofei9070** [comment]
Thank you, This link can't open

**Comment by obedm503** [comment]
@xiaofei9070 is this still an problem? If not, can you close the issue?
