### ISSUE TITLE
Can I set Showdown to recognize internal anchors links?

### ISSUE THREAD

**Issue by PawcioCNCProfi** [showdownjs/showdown#845]
Hi,
My markdown has some local links, but showdown shows them as plain text like: 
`[Declare options](#Declare current operation options) `
I can't find a mention about this in the documentation, only basic links are discussed :|

**Comment by nuts-n-bits** [comment]
### Immediately resolute

**Comment by SyntaxRules** [comment]
Fragments should be permissible:

CommonMark allows them: https://spec.commonmark.org/0.30/#example-500
Github Markdown allows them: https://github.github.com/gfm/#example-509
DF is ambiguous: https://daringfireball.net/projects/markdown/syntax#link

**Comment by SyntaxRules** [comment]
However, a space in the fragment name is not permissible. To get your example above to work the markdown needs to change from this:
```
[Declare options](#Declare current operation options)
```
to this:
```
[Declare options](#Declare%20current%20operation%20options)
# or
[Declare options](<#Declare current operation options>)
```
