### ISSUE TITLE
Confusion regarding the licensing of component

### ISSUE THREAD

**Issue by stefan-hdt** [showdownjs/showdown#849]
Hello,

I was looking at the licensing of this component. It was a little confusing because the link to https://github.com/showdownjs/showdown/blob/1.9.1/license.txt states a BSD-3-Clause for Version 1.9.1, the README file (https://github.com/showdownjs/showdown/blob/1.9.1/README.md), though, states the GPL-2.0 as license for the same version.

The README file for the current master branch (https://github.com/showdownjs/showdown/blob/master/README.md), the following is stated:

> ShowdownJS v 2.0 is release under the MIT version. Previous versions are release under BSD.

Can you please clarify which license is applicable, especially for version 1.9.1.

Thanks a lot!

Stefan

**Comment by Andrew-Chen-Wang** [comment]
probably a bit late, but rest assured BSD 3 Clause applies to version 1.9.1 according to the tag and package.json: https://github.com/showdownjs/showdown/blob/483e51f7a624c94c95787a14cbf577c053f8076f/package.json#L33

**Comment by SyntaxRules** [comment]
It looks like versions 1.9.1 and below are BSD-3-Clause, but the latest code on the master branch (and eventual 2.0.0) will be MIT licensed. I fixed the package.json file on master to represent this. Does that answer your question @stefan-hdt ?
