### ISSUE TITLE
Code highlight missing(?)

### ISSUE THREAD

**Issue by jiwidi** [showdownjs/showdown#850]
Hi!

First thank you for the library, I've been using it for some time and is very intuitive yet powerful to use.

Now I have come across a use case where highlightning code blocks is a must and I don't know how to do it with showdown, I have look around the documentation and couldn't find anything. Is there any way to do so? I'm looking for the same type of highlight that occurs in github when you write 

```
```python
import pandas

df = pd.DataFrame()
``` #End of code block
```

That resolves into:

```python
import pandas

df = pd.DataFrame()
```

When I run showdown with a MD file containing that the HTML generated has so highlight at all.

Thanks

**Comment by sojs-coder** [comment]
I have had some success with using another library like hilight.js on the client side to highlight the code blocks. It wont work with JS disabled though.

**Comment by SyntaxRules** [comment]
See the showdown [prettify extension](https://github.com/showdownjs/prettify-extension)
