### ISSUE TITLE
Code block invalid output with custom language input

### ISSUE THREAD

**Issue by erictuvesson** [showdownjs/showdown#856]
### Markdown Input:

![image](https://user-images.githubusercontent.com/1263211/117879002-b2434380-b2a6-11eb-9bae-0e290e70fa71.png)

### Expected Output:
```html
<pre><code class="json language-json">{
    "custom": true
}
</code></pre>
<pre><code class="json language-json">{
    "custom": false
}
</code></pre>
```

### Actual Output:
```html
<p>```json custom data
{
    "custom": true
}</p>
<pre><code>
</code></pre>
<p>json
{
    "custom": false
}
```</p>
```

## Extra
Removing ` custom data` from the markdown will solve the issue, but it doesn't allow for code block extensions.

**Comment by SyntaxRules** [comment]
Good catch, this kind of metadata is allowable, at least in GFM: https://github.github.com/gfm/#example-113

**Comment by tivie** [comment]
yeah, showdown doesn't allow spaces after the code block delimiter.

**Comment by tivie** [comment]
Should be fixed in commit 6711425

**Comment by Philmod** [comment]
Hi! Was this change released?

I have the issue when there is a space after the language: "```python ". I'm using the 2.1.0 version of showdown.

Thanks!

**Comment by Philmod** [comment]
@tivie Any help on ^ ?
