### ISSUE TITLE
Code span started with newline parsed incorrectly

### ISSUE THREAD

**Issue by kospl** [showdownjs/showdown#857]
Having this issue with large code block, I got tracked it down to minimal reproducable example: 

> \`
> <div\><\/div>
> \`

that won't be parsed with v 1.9.1 as expected (`<div></div>`)

Live demo: http://demo.showdownjs.com/#!/%60%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%60

Screenshot: 
![image](https://user-images.githubusercontent.com/26386660/121723936-d1c0cc80-caef-11eb-805e-8d5aa3606a3c.png)

Let me know if this can be fixed, thanks!

**Comment by aote777** [comment]
![图片](https://user-images.githubusercontent.com/53163966/142878516-814e1f2b-b169-4106-acdc-10a23fa72f28.png)
Me too

**Comment by SyntaxRules** [comment]
So this isn't a "Fenced code block" becuase "A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~)" [Source Link](https://github.github.com/gfm/#fenced-code-blocks)

This is a "code span". Here is the closes example I can find: https://github.github.com/gfm/#example-346

**Comment by aote777** [comment]
`https://github.com/aote777/anki-md-template`

上边那个显示错误我知道怎么回事了, 你必须保证传入showdown解析的时候是没有被转换为字符实体的. 不然你就会得到字符实体原样输出. 可以参考一下我写的anki转换模板.

**Comment by kospl** [comment]
@SyntaxRules thanks, changed title to be more appropriate.

Do you think this can be fixed soon? Not sure if this repo is still alive though, latest release was on 2019 (2 years ago).

**Comment by kospl** [comment]
Seems I got it, according to spec https://github.github.com/gfm/#container-blocks-and-leaf-blocks 
blocks are parsed first, so order has to be next:

1. second line (with div tags) is parsed first because it's HTML considered to be a block structure (leaf block), and left as is.
2. backticks parsed after that are considered inline (code span), so looking for closing backtick on same line, but found nothing, and left as is.

**Comment by SyntaxRules** [comment]
Thanks @kospl for looking deeper into this. I'm glad showdown is following the spec here. As for releases, hopefully we will have 2.0.0 version soon. There are a lot of backlog issues to go through before we can make that release.
