### ISSUE TITLE
extensions expect Showdown to be in the window object if on client side

### ISSUE THREAD

**Issue by boneskull** [showdownjs/showdown#86]
However, Showdown never puts itself into the window object--what it does instead is assume it's executed in the global context, which is not necessarily true.

Probably the right thing to do is look for `window` and stuff `Showdown` in it.

**Comment by pdeschen** [comment]
Indeed. That would be cleaner. But not a big deal as it simply covers both browser and node this way.

**Comment by tivie** [comment]
This should be fixed in v 1.0.* since now showdown explicitly registers itself into `window`on browser context.

See https://github.com/showdownjs/showdown/blob/1.0.0/dist/showdown.js#L1685
