### ISSUE TITLE
How to use gatsby image?

### ISSUE THREAD

**Issue by agtz92** [showdownjs/showdown#863]
Hi,
I'm using Gatsby + Netlify CMS in my project. 
I am converting markdown variables to HTML to have "multiple bodies" in my document. I'm doing it as follows

` <div className="div-text-post" dangerouslySetInnerHTML={{ __html: converter.makeHtml(post.frontmatter.mk1) }} />
          <div className="div-text-post" dangerouslySetInnerHTML={{ __html: converter.makeHtml(post.frontmatter.mk2) }} />
          <div className="div-text-post" dangerouslySetInnerHTML={{ __html: converter.makeHtml(post.frontmatter.mk3) }} />
          <div className="div-text-post" dangerouslySetInnerHTML={{ __html: converter.makeHtml(post.frontmatter.mk4) }} />
          <div className="div-text-post" dangerouslySetInnerHTML={{ __html: converter.makeHtml(post.frontmatter.mk5) }} />`
The output looks like this:
`mk1: >+
  ### 1.

  #### ¿Ketchup?

  ![w](/assets/w.jpg "w")

  El fan más importante de la Ketchup <br/>
  Patrick es un gran fanático del ketchup, incluso es la imagen de la marca Hunt’s.

  ### 2.

  #### Y por eso la precisión

  ![0](/assets/0.jpg "0")

  Le sirvió <br/>
  El jugador líder de Kansas le debe su talento a su padre Pat Mahomes, que fue pitcher profesional de las Grandes Ligas de béisbol. Pat fue el que lo entrenó a Patrick durante su juventud.`
I used to do one body converting it to HTML natively with Gatsby and I opted for this plugin since Gatsby is not capable of creating multiple markdown/rich text fields. 

 However, after using this, gatsby image is no longer optimizing the images not resizing them as before. How can I recover this functionality?

**Comment by SyntaxRules** [comment]
I'm unsure how gatsby optimizes it images. Do you think this is a issue with what ShowdownJS is doing? Or is the issue that the two libraries are not working together well?
