### ISSUE TITLE
No formatting for words surrounded by spaces

### ISSUE THREAD

**Issue by henry-pc** [showdownjs/showdown#865]
Hello! I'm wondering if there is a reason that asterisks are interpreted literally and not as added emphasis when there is a space before the word (see screenshot below for example). Is there no concept of spaces being formattable? In this instance, I would like the word text to be italicized. Would I have to just remove the space before the word "test?"

<img width="1355" alt="Screen Shot 2021-09-28 at 2 11 28 PM" src="https://user-images.githubusercontent.com/68820342/135151184-d28857d0-8734-4e79-b1c2-637e50dca150.png">

**Comment by SyntaxRules** [comment]
In the github flavored markdown (GFM), a `*` followed by a space is not a valid way to begin emphasis. According to GFM:

> A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace ...

Source: https://github.github.com/gfm/#emphasis-and-strong-emphasis

I'm going to close this as a non-issue, but feel free to ping me with follow up questions.
