### ISSUE TITLE
Security issue in ansi-regex dependency (via yargs)

### ISSUE THREAD

**Issue by jlaine** [showdownjs/showdown#866]
Currently it is impossible to install showdown without pulling in a security vulnerability, because showdown has a tightly versioned dependency on `yargs` which pulls in a vulnerable `ansi-regex`.

The security advisory is:

https://github.com/advisories/GHSA-93q8-gq69-wqmw

**Comment by SyntaxRules** [comment]
@jlaine I updated yargs on the master branch. Eventually there will be a 2.0.0 release with this fix.

**Comment by code-by-gijs** [comment]
@SyntaxRules Can this be updated to a new version of the showdown package as well?

**Comment by SyntaxRules** [comment]
@code-by-gijs For sure, I'm trying to work through as much of the backlog I can before releasing- as you can tell there are quite a few issues. It may take a bit before I can get the release out.

**Comment by code-by-gijs** [comment]
@SyntaxRules awesome, thanks!

**Comment by wbt** [comment]
[With some ambitious plans, it looks like the 2.0.0 release could be quite a ways away.](https://github.com/showdownjs/showdown/issues/881)  Might we be able to just apply the above commits on the last release tag and publish a patch update that handles the vulnerabilities / audit failures before then?

**Comment by wbt** [comment]
I should also mention that's something I'm willing to do if you want to have me on with the right permissions. I'm also a maintainer on the much more widely used Winston logger for similar reasons.

**Comment by wbt** [comment]
Even without permissions, I can offer this quickest path route:
[This](https://github.com/showdownjs/showdown/commit/9c043d8848536a961d5697951b36440d37eeb9dc) is the commit which fixes the issue, but it's [quite a ways ahead](https://github.com/showdownjs/showdown/compare/1.9.1...9c043d8848536a961d5697951b36440d37eeb9dc) of the last release, so I can understand reluctance to do a release from that.
However, the version_1.x branch is [only one tiny commit ahead](https://github.com/showdownjs/showdown/compare/1.9.1...version_1.x) of the release, and a brief inspection demonstrates that's not going to break anything important. 
The simplest PR would be to add the caret on the yargs line on the version_1.x branch and do a patch-level release from that.

**Comment by wbt** [comment]
I've added a PR which should fix this.  It drops support for node v6 and v8, so technically it should probably go out as 2.0.0, with the next big breaking release now being planned going out in _n_ months as 3.0.0.
This commit bumps the version number and adds changelog notes you can copy (the source of) that and paste it right into the release notes.  

Merge, release on Github, publish to npm, and this issue is solved.  Thanks for your work!
