### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by zidingz** [showdownjs/showdown#869]
Hey there!

I belong to an open source security research community, and a member (@yetingli) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by SyntaxRules** [comment]
For now, security issues can be added to as an issue on this repo. I've added a `SECURITY.md` file stating the same.

**Comment by JamieSlome** [comment]
@SyntaxRules - thanks for your response! 👍 

You can find the reports here:

https://huntr.dev/bounties/25869988-0cd6-4637-a25c-a7f76ebe4988/
https://huntr.dev/bounties/1dca6154-2d97-4761-a0b8-ae1794e83d61/

They are both private and only accessible to maintainers with repository write permissions!
