### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by SyntaxRules** [showdownjs/showdown#881]
The time has come for a 2.0.0 release. This release comes with breaking changes in the form of new features and by virtue of us updating the dependencies as well. While the objective of this release is mostly a maintenance release, I anticipate some new features will make its way into the release as well.

**Maintenance objectives:**
- [x] Update node versions, npm dependencies and CI runners
- [x] Resolve PRs, either merged or addressed
- [ ] Resolve issues, either merged, addressed, or determined a later feature.

**Enhancements:**
- [ ] Update plugin architecture (more on this later)
- [ ] Make it work with ES6
- [ ] ... more to follow...

**Bugs/TODO:**
- [ ] `...` in links are being converted to the unicode ellipsis chartacter. This can be avoided by turning ellipsis off.
- [ ] Integrate https://github.com/showdownjs/showdown/commit/5544e4d995e181712221278c658f6cedf98f5338 and https://github.com/showdownjs/showdown/commit/8e2b339fe2ee4521d6f99c272464fd2c15364ab3 Update and test emoji's
- [ ] Integrate https://github.com/showdownjs/showdown/commit/775f2abe978372dd2a8c55122c7c7f2f924e8db2 Add the details tag to known HTML tags

I don't have a solid release time frame yet. Due a large number of issues, I don't anticipate that this will be quick. If you care to help triage of issues and/or pull requests are happily accepted. Thanks to @tivie for the work on this library over the years. He has been busy fighting COVID pandemic and it ahs become clear that Showdown has relied on him for many years to stay active.

Notes:
-  Version 2.0.0+ of Showdown will be MIT Licensed. Previous versions of showdown were BSD-3-Clause

**Comment by SyntaxRules** [comment]
[2.0.0-alpha has been released](https://github.com/showdownjs/showdown/releases/tag/2.0.0-alpha)

**Comment by wbt** [comment]
Note that there has been no npm publish, perhaps awaiting some process that turns -alpha into 2.0.0 without qualifier, so the npm audit vulnerabilities cannot yet be resolved.

**Comment by SyntaxRules** [comment]
@wbt published now. I had to contact old contributors to get access 😄
