### ISSUE TITLE
Add additional block elements

### ISSUE THREAD

**Issue by halfdan** [showdownjs/showdown#90]
The list of block elements in https://github.com/coreyti/showdown/blob/master/src/showdown.js#L328 is incomplete.

This is causing problems in rendering markdown as showdown adds additional `<br />` to block elements that aren't on that list. We currently experience this issue in https://github.com/TryGhost/Ghost/issues/2312 where an `<audio>` tag breaks because of showdown adding additional HTML line breaks inside the element.

@coreyti Not sure if this project is still active, but if you are up to merging a PR for this I'd be happy to send one.

**Comment by pdeschen** [comment]
We're now back accepting PR. Feel free to send over. Otherwise, I'll just redo. Let us know.
