### ISSUE TITLE
The same content is displayed in the official website demo and your own demo, and the results are completely differen

### ISSUE THREAD

**Issue by 404area** [showdownjs/showdown#912]
qs：The same data shows different results
     <code> 

own demo:
![image](https://user-images.githubusercontent.com/50036307/163566955-f5dc6fa6-b39c-40d3-81ce-652207711a50.png)

official website demo:
![image](https://user-images.githubusercontent.com/50036307/163567001-3c1a94f4-5fc2-4cca-b4d2-41aef2ebe99c.png)

**Comment by bandantonio** [comment]
If you inspect the code that you are getting, both editors generate the same HTML:

**Your own**
<img width="877" alt="own" src="https://user-images.githubusercontent.com/16765690/163608364-4dd81ec9-75a9-45a1-a8aa-cbbcddedb866.png">

**Live**
<img width="614" alt="live" src="https://user-images.githubusercontent.com/16765690/163608370-89f7d971-a190-4e1a-94ea-7b5dfc46bcab.png">


The only difference is that the live editor uses css styling for `<pre>` tags:

```
background-color: #f8f8f8;
border: 1px solid #dfdfdf;
```
