### ISSUE TITLE
Unexpected image url format with makeMarkdown()

### ISSUE THREAD

**Issue by hanson2010** [showdownjs/showdown#925]
In the definition of [Markdown syntax](https://daringfireball.net/projects/markdown/syntax#img), image URL is surrounded by `()`, but not `(<>)`.

Why is it `![Alt text](</path/to/img.jpg>)` instead of `![Alt text](/path/to/img.jpg)`?

**Comment by tivie** [comment]
Both syntaxes are correct and were supported by the original markdown parser made by Gruber, even if he didn't document it.

makeMarkdown uses this syntax because it's safer: weird image links might (such as `/path/to/weird.image.name(.` will produce wrong markdown.
