### ISSUE TITLE
Strip more international punctuation characters from header ids in `ghCompatibleHeaderId` mode

### ISSUE THREAD

**Issue by tunetheweb** [showdownjs/showdown#949]
GitHub currently strips the following extended punctuation characters when creating headers in markdown files, but Showdown does not.

- Inverted exclamation and question marks (`¡` and `¿`) - [used in Spanish](https://en.wikipedia.org/wiki/Inverted_question_and_exclamation_marks)
- Various full width punctuation marks (e.g. `？`, `：`...etc) - [used a lot in Japanese](https://en.wikipedia.org/wiki/Japanese_punctuation)

Evidence in this gist: https://gist.github.com/tunetheweb/ecbfed99663425a668748770568bdafb#some-header-with--chars

Seems an easy enough fix to add these so will submit a PR.

**Comment by tivie** [comment]
Hey. 

Do you mean GitHub strips these characters from ids?

**Comment by tunetheweb** [comment]
Correct. If you look at that gist example (markdown gists automatically creates ids) you see it:

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/10931297/201726426-a3a0002b-3512-43e2-8d77-abdd5d2b194a.png">

**Comment by tivie** [comment]
Thank you. Will be merging the PR.
