### ISSUE TITLE
Underscores in words

### ISSUE THREAD

**Issue by SystemParadox** [showdownjs/showdown#96]
As described in Github flavoured markdown, it makes no sense to italicise parts of a word.

Underscores in words usually refer to something like a variable or field name so it is particularly bad when these are parsed out and converted to italics.

Please can showdown be changed to use the github rules for this.

Thanks.

**Comment by zachad** [comment]
We're running into this too. Is it an easy fix to make to the parser?  There should be a non-character (space, or beginning of the line) before the underscore in order for it to trigger the italicized output.

**Comment by pdeschen** [comment]
@zachad thanks for posting the work around!

**Comment by tivie** [comment]
@pdeschen It's not a bug, it's by design

> As described in Github flavoured markdown, it makes no sense to italicise parts of a word.

Showdown is vanilla markdown. As stated in the [original specifications](http://daringfireball.net/projects/markdown/syntax#em):

> Emphasis can be used in the middle of a word:
> ```md
> un*frigging*believable
> ```
>But if you surround an * or _ with spaces, it’ll be treated as a literal asterisk or underscore.

The correct way to prevent the behavior (or to create a literal asterisk or underscore) is to escape it with backslash, as stated in the specs:

>To produce a literal asterisk or underscore at a position where it would otherwise be used as an emphasis delimiter, you can backslash escape it:
>
>`\*this text is surrounded by literal asterisks\*`

**Comment by tivie** [comment]
Also I could not reproduce the issue @shhQuiet refers to! 

Please provide an example where showdown incorrectly parses links and images with underscore so we can have a better understanding of the issue.

**Comment by SystemParadox** [comment]
> Showdown is vanilla markdown

But vanilla markdown is unmaintained and broken in this behaviour. Could an option be added to support github flavoured markdown?

Thanks.

**Comment by tivie** [comment]
@SystemParadox @pdeschen https://github.com/showdownjs/showdown/issues/164

**Comment by tivie** [comment]
<http://www.google.com>
