### ISSUE TITLE
Strikethroughs won't render.

### ISSUE THREAD

**Issue by HotdoGuy90** [showdownjs/showdown#988]
Whenever I try to use a strikethrough example: `~~The earth is flat~~` what *should* happen is output with: "~~The earth is flat~~", however it doesn't. If you haven't implemented it yet, please do. And if it is but wont render, please fix it. (btw i think the html equivalent is the "del" tag)

**Comment by pwbriggs** [comment]
@HotdoGuy90 In order to use the strikethrough syntax, you must enable the `strikethrough` option in the [configuration](https://github.com/showdownjs/showdown#options). It defaults to `false`, which is why it isn't working for you.

**Comment by HotdoGuy90** [comment]
Oh Thanks :)
