### ISSUE TITLE
Dom elements and templates together can cause problems.

### ISSUE THREAD

**Issue by rmtmckenzie** [showdownjs/showdown#99]
I'm having a small issue with showdown that is causing problems with my rendering.

    {{#markdown}}
    This is parsed.

    <p>{{> test}}</p>

    #This is not parsed.

    <p>
    {{> test}}
    </p>

    This is parsed.

    {{/markdown}}

And the test template:

    <template name="test">Testtext</template>

This is resulting in the part with '#' not being parsed. If I remove the newline between the \<p> and {{> test}} it works fine.

This is the resulting html:

    <p>This is parsed.</p>

    <p>Testtext</p>

    #This is not parsed.

    <p>
    Testtext
    </p>

    <p>This is parsed.</p>

I've ended up switching to metoer-markdown as it seems to handle this fine. I could just eliminate the newline but as my \<p> and templates have way more attributes than this simple example I'd prefer not to for clean-ness. It if could be fixed it might save someone else some confusion in the future!

**Comment by tivie** [comment]
I will look into it

**Comment by pdeschen** [comment]
I thought meteor-markdown was actually using showdown underneath?

**Comment by tivie** [comment]
I can't really reproduce this issue... this is probably an issue with moustachejs being used with showdown (if that is moustachejs).

More info needed.

**Comment by tivie** [comment]
I will close it for now. If more info is provided I can reopen and try to find a solution
